# APIS

![apis_gif](https://media.giphy.com/media/wepUQluC5smgEd4Qz4/giphy.gif)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#APIS" data-toc-modified-id="APIS-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>APIS</a></span><ul class="toc-item"><li><span><a href="#Web-Communication-Fundamentals" data-toc-modified-id="Web-Communication-Fundamentals-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Web Communication Fundamentals</a></span><ul class="toc-item"><li><span><a href="#DNS,-IP" data-toc-modified-id="DNS,-IP-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>DNS, IP</a></span></li><li><span><a href="#HTTP" data-toc-modified-id="HTTP-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>HTTP</a></span></li><li><span><a href="#URL" data-toc-modified-id="URL-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>URL</a></span></li></ul></li><li><span><a href="#HTTP-Requests-and-Responses" data-toc-modified-id="HTTP-Requests-and-Responses-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>HTTP Requests and Responses</a></span><ul class="toc-item"><li><span><a href="#Requests" data-toc-modified-id="Requests-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Requests</a></span></li><li><span><a href="#Response" data-toc-modified-id="Response-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Response</a></span></li></ul></li><li><span><a href="#APIs" data-toc-modified-id="APIs-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>APIs</a></span><ul class="toc-item"><li><span><a href="#RESTful-APIs" data-toc-modified-id="RESTful-APIs-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>RESTful APIs</a></span></li></ul></li><li><span><a href="#Requests-in-Python" data-toc-modified-id="Requests-in-Python-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Requests in Python</a></span><ul class="toc-item"><li><span><a href="#GET" data-toc-modified-id="GET-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>GET</a></span><ul class="toc-item"><li><span><a href="#Accessing-an-endpoint" data-toc-modified-id="Accessing-an-endpoint-1.4.1.1"><span class="toc-item-num">1.4.1.1&nbsp;&nbsp;</span>Accessing an endpoint</a></span></li><li><span><a href="#Response-headers" data-toc-modified-id="Response-headers-1.4.1.2"><span class="toc-item-num">1.4.1.2&nbsp;&nbsp;</span>Response headers</a></span></li><li><span><a href="#Parameters" data-toc-modified-id="Parameters-1.4.1.3"><span class="toc-item-num">1.4.1.3&nbsp;&nbsp;</span>Parameters</a></span></li><li><span><a href="#Request-Headers" data-toc-modified-id="Request-Headers-1.4.1.4"><span class="toc-item-num">1.4.1.4&nbsp;&nbsp;</span>Request Headers</a></span></li></ul></li></ul></li><li><span><a href="#APIs-examples" data-toc-modified-id="APIs-examples-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>APIs examples</a></span><ul class="toc-item"><li><span><a href="#NewsAPI" data-toc-modified-id="NewsAPI-1.5.1"><span class="toc-item-num">1.5.1&nbsp;&nbsp;</span>NewsAPI</a></span><ul class="toc-item"><li><span><a href="#💡-Check-for-understanding" data-toc-modified-id="💡-Check-for-understanding-1.5.1.1"><span class="toc-item-num">1.5.1.1&nbsp;&nbsp;</span>💡 Check for understanding</a></span></li></ul></li><li><span><a href="#Pokemon-API" data-toc-modified-id="Pokemon-API-1.5.2"><span class="toc-item-num">1.5.2&nbsp;&nbsp;</span>Pokemon API</a></span><ul class="toc-item"><li><span><a href="#json_normalize()" data-toc-modified-id="json_normalize()-1.5.2.1"><span class="toc-item-num">1.5.2.1&nbsp;&nbsp;</span>json_normalize()</a></span></li></ul></li><li><span><a href="#Coincap-API" data-toc-modified-id="Coincap-API-1.5.3"><span class="toc-item-num">1.5.3&nbsp;&nbsp;</span>Coincap API</a></span></li><li><span><a href="#💡-Check-for-understanding" data-toc-modified-id="💡-Check-for-understanding-1.5.4"><span class="toc-item-num">1.5.4&nbsp;&nbsp;</span>💡 Check for understanding</a></span></li></ul></li><li><span><a href="#API-Wrappers" data-toc-modified-id="API-Wrappers-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>API Wrappers</a></span></li><li><span><a href="#Summary" data-toc-modified-id="Summary-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Summary</a></span></li><li><span><a href="#Glossary" data-toc-modified-id="Glossary-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Glossary</a></span></li><li><span><a href="#Further-materials" data-toc-modified-id="Further-materials-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Further materials</a></span></li></ul></li></ul></div>

## Web Communication Fundamentals

![enjuto](https://www.publico.es/files/article_main/uploads//2014/12/13/548bb18f1d9ef.jpg)

### DNS, IP

[How do we connect to www.google.com?](https://www.youtube.com/watch?v=sUhEqT_HSBI&ab_channel=ProfeSang)
* **DNS (Domain Name System)**: it's essentially the phonebook of the internet. Humans access information online through domain names, like "google.com". Web browsers, however, interact through Internet Protocol (IP) addresses. In this example, the DNS maps the internet address www.google.com to the server's IP: 216.58.222.196
 * **IP**: Server identification. A code that allows information to be sent and received by the correct parties
 * **Domain Providers**: Sell and purchase Internet domains

*When making API calls to specific domains, the DNS translates the human-readable domain name into an IP address.*

### HTTP

**H**yper **T**ext **T**ransfer **P**rotocol
- HTTP is a communications protocol that provides a structure for requests between the client and the server on a network.
- For example, the web browser on the user's computer (the client) uses the HTTP protocol to request information from a website on a server.

*We will use APIs that employ the **HTTP** protocol as transport.*

### URL
Contains information about the resource being requested from the **server**.

![](https://github.com/data-bootcamp-v4/lessons/blob/main/img/http.png?raw=true)

Examples:

- https://www.google.com/webhp?authuser=2
- https://www.towardsdatascience.com
- https://www.ironhack.com/
    - Protocol: https (https == http is the same, but https is encrypted)
    - Domain Name --> ironhack
    - TLD (Top-Level Domain) --> .com

*When calling an API, you specify the URL of the API endpoint, which tells the system where to send the request.*

## HTTP Requests and Responses

![](https://github.com/data-bootcamp-v4/lessons/blob/main/img/request-response.png?raw=true)

**Requests** and **responses** are fundamental components of the client-server communication model.

### Requests

These are queries or calls **sent by the client** (such as a web browser or other software) **to the server** in order to receive information (a **response**).

A request typically consists of:
- A method (such as GET, POST, PUT, DELETE) that defines the action to be performed
     * GET: read the information of the resource, without modifying it in any way. Accessing the website from the browser **gets** information.
- The URL or endpoint specifying the resource
- Optional additional information such as:
    - Headers (metadata): User-Agent, Accept-Language
    - Parameters
    - Body content.
    
For example, a client might send a GET request to retrieve information from a web page or a POST request to submit form data.

### Response

These are the answers or data sent **by the server back to the client in reply to a request**.

A response typically includes:
- A status code that indicates the success or failure of the request
- Headers with meta-information about the server's behavior
- The actual content or data (if applicable), such as HTML, JSON (similar to a Python dictionary), images, or other media types.

An important part of the **header** is the **status code**. This code is a numerical value that indicates the server's result. There are different status codes depending on whether the server has managed to carry out the request or has not managed to do anything. These are some groups of status codes:

- **2xx successful**: the request was successfully received, understood, and accepted
- **3xx redirection**: more actions are required to complete the request
- **4xx client error**: the request contains incorrect syntax or cannot be fulfilled
- **5xx server error**: the server has failed to complete an apparently valid request

Complete list:
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

Much more fun:
https://http.cat/

## APIs

**A**pplication **P**rogramming **I**nterface

- APIs define a set of rules and protocols that allow different software applications to communicate with each other.
- The client calls the server through an API, and the server responds.
-  Within a project, the backend may want to share information with the frontend without access to the database.

![](https://github.com/data-bootcamp-v4/lessons/blob/main/img/api.png?raw=true)

### RESTful APIs

As a data analyst, you often need to access data from various sources. RESTful APIs provide a **standardized way** to retrieve, update, or delete data from other systems.

- Usually, **we (the client) send a request, and they (the server) return a response, often in JSON - JavaScript Object Notation - format**. While JSON looks similar to the dictionaries we're used to in Python, it's worth noting that when represented as raw text (e.g., in an API response), the entire JSON structure is a *string*. However, within that structure, JSON can represent various data types like numbers, booleans, and arrays, not just strings.

- APIs always need to provide documentation for their various services: **endpoints**.  Each endpoint is a different URL.  
- Sometimes we have to pass **parameters** to an API endpoint, similar to when we pass parameters to a Python function.

At this point in the Bootcamp, **reading documentation becomes essential**, as each API will "work" differently, and to use it, we will need to know what it requires.

[Here](https://github.com/public-apis/public-apis) is a repository where you can find several free APIs if you feel like exploring a bit.

## Requests in Python

You can make requests to RESTful APIs using libraries like `requests`.

In [1]:
# If you don't have it installed you can do use using pip or pip3

!conda install requests -y

In [2]:
import requests

### GET

Making a `GET request` to the API is simply a call to a `URL` that returns information when provided with the appropriate `parameters`. We will only perform **GET** requests.

Here is an example on how to make a request with Python:

```python
url = "https://api.example.com/products"
response = requests.get(url)

if response.status_code == 200:
    products = response.json()
    # Now you can analyze and work with the products data in Python
```

#### Accessing an endpoint

As we mentioned above, APIs always need to provide documentation for their various services: **endpoints**.  Each endpoint is a different URL.  

**Example: ISS API**

Let's get information from ISS (International Space Station)! We'll start looking at the [ISS API documentation](https://wheretheiss.at/w/developer)

This API allows you to access various data related to the International Space Station (ISS), including its current, past, or future position, timezone information for specific coordinates, and more.

**Key Features**
- **Authentication**: No authentication is currently required, but future endpoints may include this.
- **Rate Limiting**: Limited to approximately 1 request per second.
- **Responses**: Default to JSON format, with optional parameters to modify response appearance.
- **Endpoints**: Several endpoints provide different types of information:
    - **satellites**: Information about satellites, including the ISS.
    - **satellites/[id]**: Position, velocity, and related information for a satellite.
    - **satellites/[id]/positions**: Position data for specific timestamps.
    - **satellites/[id]/tles**: TLE (Two-Line Element Set) data in either JSON or text format.
    - **coordinates/[lat,lon]**: Timezone information for specific coordinates.

**Examples**
- Satellite details: `https://api.wheretheiss.at/v1/satellites`
- ISS position: `https://api.wheretheiss.at/v1/satellites/25544`
- Coordinates information: `https://api.wheretheiss.at/v1/coordinates/37.795517,-122.393693`

**Endpoint satellites**

In [3]:
# We'll use the endpoint satellites, we read it gives us information about satellites

url = "https://api.wheretheiss.at/v1/satellites"

In [4]:
response = requests.get(url) # We use get method to make the request and get information from the API

In [5]:
type(response) # Lets look at the type of the response

requests.models.Response

In [6]:
response.status_code # We can access status code. 200 is OK

200

We can access the response content, which returns a string

In [7]:
response.content

b'[{"name":"iss","id":25544}]'

If response Content-Type is json, we can access it better with `.json()`

In [8]:
info = response.json()

In [9]:
info

[{'name': 'iss', 'id': 25544}]

In [10]:
type(info) # It returns a list of dictionaries

list

In [11]:
info[0]["id"] # So we can access the id like this

25544

#### Response headers

Response headers are part of the HTTP response that a server sends back to the client after a request has been made. These headers provide meta-information about the response and can affect how the client handles the response.

Here are some common response headers and what they typically represent:

1. **`Date`**: Represents the date and time at which the response was sent.

2. **`Server`**: Provides information about the software used by the originating server.

3. **`X-Rate-Limit`**: Sometimes used in APIs to inform the client about rate limiting policies, such as the number of allowed requests in a given time frame.

4. **`Content-Type`**: Specifies the media type of the resource or data the server is sending back. For example, it could be `application/json` for a JSON object, `text/html` for an HTML page, or `image/png` for an image.

And more.

In [12]:
response.headers # We can also access the response headers

{'Date': 'Mon, 06 Oct 2025 13:04:13 GMT', 'Server': 'Apache/2.2.22 (Ubuntu)', 'X-Powered-By': 'PHP/5.3.10-1ubuntu3.26', 'X-Rate-Limit-Limit': '350', 'X-Rate-Limit-Remaining': '349', 'X-Rate-Limit-Interval': '5 minutes', 'Access-Control-Allow-Origin': '*', 'X-Apache-Time': 'D=12411', 'Cache-Control': 'max-age=0, no-cache', 'Content-Length': '27', 'Keep-Alive': 'timeout=15, max=100', 'Connection': 'Keep-Alive', 'Content-Type': 'application/json'}

#### Parameters

As we mentioned above, sometimes we can pass **parameters** to an API endpoint, similar to when we pass parameters to a Python function.

In the example above, we didn't use any parameters in the endpoint `satellites` since the [documentation]("https://wheretheiss.at/w/developer") said *Parameters: None*.

API parameters are specific values that you include in a request to an API endpoint to filter, sort, or detail the data that you want to retrieve. They allow you to customize the request to get exactly the information you need.

There are several types of parameters that can be used in API requests, such as Path Parameters, Query Parameters, Header Parameters and Request Body Parameters. Let's look at them with an example using another endpoint.

##### 1. **Path Parameters**

These are embedded in the URL path and are used to identify a specific resource. For example, in the URL above `https://api.wheretheiss.at/v1/satellites/25544`, the number `25544` is a path parameter that identifies a specific sattelite.

**Endpoint satellites/id**

Lets use endpoint satellites/[id] with the id we got from the previous endpoint.
Important, we need to provide the whole url for the endpoint as a `string`.

In [13]:
url_iss_position = "https://api.wheretheiss.at/v1/satellites/"+str(info[0]["id"])

In [14]:
response = requests.get(url_iss_position)

In [15]:
response.status_code

200

In [16]:
response.json()

{'name': 'iss',
 'id': 25544,
 'latitude': 51.308453697637,
 'longitude': -16.981678674776,
 'altitude': 423.8448428009,
 'velocity': 27587.526571459,
 'visibility': 'daylight',
 'footprint': 4526.9727969028,
 'timestamp': 1759755863,
 'daynum': 2460955.0447106,
 'solar_lat': -5.3405206201955,
 'solar_lon': 340.90987394279,
 'units': 'kilometers'}

Every time we call the endpoint, the information changes since it gives us the current position of the satellite. Let's check that with a loop to gather information at different times.

In [17]:
import time

positions = []

for i in range(10):
    response = requests.get(url_iss_position)
    data = response.json()

    positions.append(data)
    time.sleep(0.5)

In [18]:
type(positions) # We created a list with responses

list

In [19]:
type(positions[0]) # Is a list of dictionaries

dict

In [20]:
positions[0] # So we can access each dictionary by its position in the list

{'name': 'iss',
 'id': 25544,
 'latitude': 51.430119930329,
 'longitude': -15.608516428906,
 'altitude': 423.86490273572,
 'velocity': 27587.543183218,
 'visibility': 'daylight',
 'footprint': 4527.074315273,
 'timestamp': 1759755877,
 'daynum': 2460955.0448727,
 'solar_lat': -5.3405826844042,
 'solar_lon': 340.85152876807,
 'units': 'kilometers'}

In [21]:
positions[9]

{'name': 'iss',
 'id': 25544,
 'latitude': 51.750580610688,
 'longitude': -3.9615776705358,
 'altitude': 423.87082671291,
 'velocity': 27587.776729438,
 'visibility': 'daylight',
 'footprint': 4527.1042945254,
 'timestamp': 1759755994,
 'daynum': 2460955.0462269,
 'solar_lat': -5.3411013623858,
 'solar_lon': 340.36393009705,
 'units': 'kilometers'}

Let's extract 10 latitudes from the 10 dictionaries in the list, with 2 decimals.

In [22]:
latitudes = [round(position["latitude"], 2) for position in positions]

In [23]:
latitudes

[51.43, 51.54, 51.57, 51.65, 51.7, 51.75, 51.77, 51.79, 51.78, 51.75]

In [24]:
import pandas as pd
pd.DataFrame(positions) # We can create a dataframe from the API response to work with it better

,name,id,latitude,longitude,altitude,velocity,visibility,footprint,timestamp,daynum,solar_lat,solar_lon,units
0,iss,25544,51.430120,-15.608516,423.864903,27587.543183,daylight,4527.074315,1759755877,2.460955e+06,-5.340583,340.851529,kilometers
1,iss,25544,51.541000,-14.129458,423.881859,27587.563616,daylight,4527.160123,1759755892,2.460955e+06,-5.340649,340.789016,kilometers
2,iss,25544,51.573451,-13.634861,423.886462,27587.571039,daylight,4527.183417,1759755897,2.460955e+06,-5.340671,340.768179,kilometers
3,iss,25544,51.647218,-12.345710,423.895964,27587.591784,daylight,4527.231504,1759755910,2.460955e+06,-5.340729,340.714001,kilometers
4,iss,25544,51.697616,-11.251800,423.901214,27587.610977,daylight,4527.258069,1759755921,2.460955e+06,-5.340778,340.668158,kilometers
5,iss,25544,51.751159,-9.656784,423.904265,27587.641592,daylight,4527.273509,1759755937,2.460955e+06,-5.340849,340.601478,kilometers
6,iss,25544,51.767196,-8.957897,423.903887,27587.655995,daylight,4527.271598,1759755944,2.460955e+06,-5.340880,340.572306,kilometers
7,iss,25544,51.786383,-7.458975,423.899563,27587.688930,daylight,4527.249715,1759755959,2.460955e+06,-5.340946,340.509793,kilometers
8,iss,25544,51.779732,-5.459708,423.886336,27587.737230,daylight,4527.182783,1759755979,2.460955e+06,-5.341035,340.426443,kilometers
9,iss,25544,51.750581,-3.961578,423.870827,27587.776729,daylight,4527.104295,1759755994,2.460955e+06,-5.341101,340.363930,kilometers


##### 2. **Query Parameters**

These are added to the end of the URL after a question mark (`?`) and are often used to filter or sort the response.

For example, in the ISS documentation, it mentions that there is a parameter `units` that can take values `miles` or `kilometers`. So in the URL `https://api.wheretheiss.at/v1/satellites/25544?units=miles`, we added `units=miles` which is a query parameter that shows the data in "miles".

In general, we add the parameters like this `?param1=value1&param2=value2...` at the end of the URL.

In [25]:
url_iss_position

'https://api.wheretheiss.at/v1/satellites/25544'

In [26]:
# We saw in the documentation that we can add a parameter units to use miles or kilometers

url_iss_position2 = 'https://api.wheretheiss.at/v1/satellites/25544?units=miles'

In [27]:
response = requests.get(url_iss_position2)

In [28]:
response.status_code

200

In [29]:
response.json()

{'name': 'iss',
 'id': 25544,
 'latitude': 51.70076674271,
 'longitude': -2.4661586149581,
 'altitude': 263.36843280645,
 'velocity': 17142.270687133,
 'visibility': 'daylight',
 'footprint': 2812.9475239153,
 'timestamp': 1759756009,
 'daynum': 2460955.0464005,
 'solar_lat': -5.341167859426,
 'solar_lon': 340.30141743424,
 'units': 'miles'}

We can also do it by passing to the argument `params` a dictionary with the parameters in the `get` method.

In [30]:
parameters = {"units": "miles"}

In [31]:
url_iss_position

'https://api.wheretheiss.at/v1/satellites/25544'

In [32]:
response = requests.get(
    url=url_iss_position,
    params=parameters
)

In [33]:
response.json()

{'name': 'iss',
 'id': 25544,
 'latitude': 51.62494972806,
 'longitude': -0.87560873854692,
 'altitude': 263.3517260606,
 'velocity': 17142.300595398,
 'visibility': 'daylight',
 'footprint': 2812.8629731541,
 'timestamp': 1759756025,
 'daynum': 2460955.0465856,
 'solar_lat': -5.3412387897223,
 'solar_lon': 340.23473711532,
 'units': 'miles'}


##### 3. **Header Parameters**

These are included in the request header and can be used for various purposes, such as authentication (e.g., sending an API key or token), content negotiation (e.g., defining the response format), or custom settings defined by the API. If the API requires authentication, you might include an `Authorization` header with your API key.

ISS API mentions that *currently there is no authentication required*. So we'll look at an example with a different API of `authentication` in `header parameters`.

#### Request Headers

Request headers are key-value pairs sent in an HTTP request to provide information about the request itself.

Some request headers are:

1. **Content-Type**: Specifies the media type of the resource or data. Common examples include "application/json" for JSON data, "text/html" for HTML content, and "application/xml" for XML data.

3. **Authorization**: Contains credentials for authenticating the client with the server, often used with tokens or other forms of authentication.

4. **User-Agent**: Provides information about the client (browser or other client), including its version and operating system.


In Python's `requests` library, you can include headers in a request by using the `headers` argument, like this:

```python
headers = {'Content-Type': 'application/json', 'Authorization': 'Bearer YOUR_TOKEN'}
response = requests.get(url, headers=headers)
```

⚠️🚨 ¡Careful with the authentication token! ⚠️🚨  A token is a personal credential for accessing an API, through which your request quota to the API is managed. Therefore, the ideal procedure is to ensure security by storing the token as a variable in an .env file. This way, you can call the environment variable without having to publicly display the token.

**Example: News API**

The *News API* lets you locate articles and breaking news headlines from news sources and blogs across the web.

- Let's look at the [NewsAPI Authentication documentation](https://newsapi.org/docs/authentication). It mentions:
```
You can attach your API key to a request in one of three ways:

- Via the apiKey querystring parameter.
- Via the X-Api-Key HTTP header.
- Via the Authorization HTTP header. Including Bearer is optional, and be sure not to base 64 encode it like you may have seen in other authentication tutorials.
We strongly recommend the either of last two so that your API key isn't visible to others in logs or via request sniffing.

If you don't append your API key correctly, or your API key is invalid, you will receive a 401 - Unauthorized HTTP error.
```

- Let's look at the documentation for the endpoints to see what **parameters** they accept: [NewsAPI endpoints](https://newsapi.org/docs/endpoints). We see we have the endpoint `/v2/top-headlines` – *returns breaking news headlines for countries, categories, and singular publishers. This is perfect for use with news tickers or anywhere you want to use live up-to-date news headlines.*
If we look at the [documentation of that endpoint](https://newsapi.org/docs/endpoints/top-headlines) we see we have more parameters we can add such as `country` or `category`.

In [34]:
url = "http://newsapi.org/v2/top-headlines"

In [35]:
response = requests.get(url)

In [36]:
response.status_code

401

Let's try a made up key, using the apiKey querystring parameter. As we read in the documentation, this is not the recommended way.

In [37]:
url = f"http://newsapi.org/v2/top-headlines?country=us&apiKey=manolonodoesnthavekey"

In [38]:
url

'http://newsapi.org/v2/top-headlines?country=us&apiKey=manolonodoesnthavekey'

In [39]:
response = requests.get(url)

In [40]:
response.status_code

401

**4xx**: client error. This means, it is our error.

Lets do with a correct key. You should get your own API key through their website. Once we've saved our key, we'll send it via the X-Api-Key HTTP header.

##### Saving the API Key

Storing an API key directly in your code can expose sensitive information, especially if your code is publicly available (e.g., on a public GitHub repository). The best practice for saving and loading an API key in your code involves the following steps:

1. **Storing the API Key**:
    - **Use Environment Variables**: Store your API key in an environment variable on your system. This keeps the key out of your codebase and allows you to change it without altering your code.


    - **Create a .env File**: If you prefer, you can create a `.env` file (just call it `.env` nothing else before the `.`) in your project directory to store the API key. Inside this file, you would have something like:
   
       ```
       API_KEY=your-api-key-here
       ```

        - **Add .env to .gitignore**: If you're using a version control system like Git, make sure to add the `.env` file to your `.gitignore` file. This prevents the `.env` file (and therefore your API key) from being uploaded to any public repositories. We'll talk about Git and .gitignore in more detail soon.

2. **Load the Key in Your Code**:

    You can use libraries like `python-dotenv` to load the key into your code.
    You would need to install `python-dotenv` first.
    ```python
    !pip install python-dotenv

    from dotenv import load_dotenv
    import os

    load_dotenv()
    api_key = os.getenv("API_KEY")
    ```

       
    Now, `api_key` contains the value of your API key, and you can use it to authenticate your requests to the API.

Lets do the second approach. Lets save it in an env file and save it in a variable.

`Make sure your file is named .env and not .env.txt! Is one of the most common errors. If you need, look at the document properties to make sure it doesn't have .txt at the end even if its not showing the .txt when looking at your folder.`

In [41]:
!conda install kvedala::newsapi-python -y
!conda install python-dotenv -y

Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.1.1)
Requirement already satisfied: newsapi-python in /usr/local/lib/python3.12/dist-packages (0.2.7)
Requirement already satisfied: requests<3.0.0 in /usr/local/lib/python3.12/dist-packages (from newsapi-python) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0->newsapi-python) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0->newsapi-python) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0->newsapi-python) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0->newsapi-python) (2025.8.3)

Make sure to create a file named `.env` in the same folder as your jupyter notebook with the following content:

````
NEWS_API_KEY="your_api_key"
````

In [137]:
import os
from dotenv import load_dotenv, find_dotenv

# .env
load_dotenv(override=True)

news_api_key = os.getenv("NEWS_API_KEY")

If you get an error, make sure you saved the .env file in the same directory as your jupyter notebook. You can use `os.getcwd()` to do so.

##### Using the API Key in the Header Parameters

In [138]:
#url_top_headlines = "http://newsapi.org/v2/top-headlines"

from newsapi import NewsApiClient

newsapi = NewsApiClient(api_key=news_api_key)

top_headlines = newsapi.get_top_headlines(q='bitcoin',
                                          category='business',
                                          language='en',
                                          country='us')

top_headlines

{'status': 'ok',
 'totalResults': 1,
 'articles': [{'source': {'id': 'bloomberg', 'name': 'Bloomberg'},
   'author': 'Muyao Shen, Emily Nicolle',
   'title': 'Bitcoin Rises to a Record as ‘Debasement’ Trade Spurs Risk Rally - Bloomberg.com',
   'description': 'Bitcoin set another all-time high as a broader risk rally around the US government shutdown buoyed the world’s largest cryptocurrency.',
   'url': 'https://www.bloomberg.com/news/articles/2025-10-05/bitcoin-rises-to-a-record-as-debasement-trade-spurs-risk-rally',
   'urlToImage': 'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iq26eORKPasg/v0/1200x800.jpg',
   'publishedAt': '2025-10-05T04:54:00Z',
   'content': 'Bitcoin set another all-time high as a broader risk rally around the US government shutdown buoyed the worlds largest cryptocurrency.\r\nThe token climbed to as high as $125,689 on Sunday in Asia, topp… [+326 chars]'}]}

In [63]:
type(top_headlines)

dict

## APIs examples

### NewsAPI

In [99]:
type(top_headlines) # returns a dictionary

dict

In [100]:
top_headlines.keys() # we can get the keys with method keys()

dict_keys(['status', 'totalResults', 'articles'])

In [66]:
top_headlines['status']
#data.get("status") # we can get a key's value by using get method

'ok'

In [101]:
top_headlines["totalResults"] # or by using dictionary notation to access values

1

In [68]:
# this is the same as above
top_headlines.get("totalResults")

1

`dict[key]` raises error if the key does not exits  
`dict.get(key)` does not raise an error if the key does not exist

In [102]:
# lets look at the articles
articles = top_headlines.get("articles")

In [103]:
type(articles) # lets see what type it is to know how to access it

list

In [104]:
len(articles)

1

In [105]:
articles[0] # since articles is a list, we can access its elements by the index

{'source': {'id': 'bloomberg', 'name': 'Bloomberg'},
 'author': 'Muyao Shen, Emily Nicolle',
 'title': 'Bitcoin Rises to a Record as ‘Debasement’ Trade Spurs Risk Rally - Bloomberg.com',
 'description': 'Bitcoin set another all-time high as a broader risk rally around the US government shutdown buoyed the world’s largest cryptocurrency.',
 'url': 'https://www.bloomberg.com/news/articles/2025-10-05/bitcoin-rises-to-a-record-as-debasement-trade-spurs-risk-rally',
 'urlToImage': 'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iq26eORKPasg/v0/1200x800.jpg',
 'publishedAt': '2025-10-05T04:54:00Z',
 'content': 'Bitcoin set another all-time high as a broader risk rally around the US government shutdown buoyed the worlds largest cryptocurrency.\r\nThe token climbed to as high as $125,689 on Sunday in Asia, topp… [+326 chars]'}

In [106]:
type(articles[0]) # each element inside the list is a dictionary

dict

In [107]:
[art["title"] for art in articles] # lets get all the titles using list comprehension

['Bitcoin Rises to a Record as ‘Debasement’ Trade Spurs Risk Rally - Bloomberg.com']

In [108]:
df = pd.DataFrame(articles) # lets create a dataframe with the articles

In [109]:
df.head()

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': 'bloomberg', 'name': 'Bloomberg'}","Muyao Shen, Emily Nicolle",Bitcoin Rises to a Record as ‘Debasement’ Trad...,Bitcoin set another all-time high as a broader...,https://www.bloomberg.com/news/articles/2025-1...,https://assets.bwbx.io/images/users/iqjWHBFdfx...,2025-10-05T04:54:00Z,Bitcoin set another all-time high as a broader...

#### 💡 Check for understanding

1. What data type is the column *source*?
2. Since the column *source* is not very useful as it is, create a column called *name* that contains only the name inside the column *source*.
3. How many times each unique name appears in the "name" column?

In [110]:
# Your answer goes here

# 1. What data type is the column source?
df.dtypes['source']
# 2. Since the column source is not very useful as it is, create a column called name that contains only the name inside the column source.
df['name'] = [dict(item)['name'] for item in df['source']]
# 3. How many times each unique name appears in the "name" column?
df['name'].value_counts()

name
Bloomberg    1
Name: count, dtype: int64

### Pokemon API

[PokeAPI](https://pokeapi.co/) is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.

In the documentation we see that we can get lot's of data. Let's look at the endpoint *pokemon*: ```https://pokeapi.co/api/v2/pokemon/{id or name}/```

In [111]:
res=requests.get('https://pokeapi.co/api/v2/pokemon/25')
res.status_code

200

In [112]:
data=res.json()
data

{'abilities': [{'ability': {'name': 'static',
    'url': 'https://pokeapi.co/api/v2/ability/9/'},
   'is_hidden': False,
   'slot': 1},
  {'ability': {'name': 'lightning-rod',
    'url': 'https://pokeapi.co/api/v2/ability/31/'},
   'is_hidden': True,
   'slot': 3}],
 'base_experience': 112,
 'cries': {'latest': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/25.ogg',
  'legacy': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/legacy/25.ogg'},
 'forms': [{'name': 'pikachu',
   'url': 'https://pokeapi.co/api/v2/pokemon-form/25/'}],
 'game_indices': [{'game_index': 84,
   'version': {'name': 'red', 'url': 'https://pokeapi.co/api/v2/version/1/'}},
  {'game_index': 84,
   'version': {'name': 'blue', 'url': 'https://pokeapi.co/api/v2/version/2/'}},
  {'game_index': 84,
   'version': {'name': 'yellow',
    'url': 'https://pokeapi.co/api/v2/version/3/'}},
  {'game_index': 25,
   'version': {'name': 'gold', 'url': 'https://pokeapi.co/api/v2/version/4/'}},
  {'game_index': 25,
   'version': {'name': 'silver',
    'url': 'https://pokeapi.co/api/v2/version/5/'}},
  {'game_index': 25,
   'version': {'name': 'crystal',
    'url': 'https://pokeapi.co/api/v2/version/6/'}},
  {'game_index': 25,
   'version': {'name': 'ruby', 'url': 'https://pokeapi.co/api/v2/version/7/'}},
  {'game_index': 25,
   'version': {'name': 'sapphire',
    'url': 'https://pokeapi.co/api/v2/version/8/'}},
  {'game_index': 25,
   'version': {'name': 'emerald',
    'url': 'https://pokeapi.co/api/v2/version/9/'}},
  {'game_index': 25,
   'version': {'name': 'firered',
    'url': 'https://pokeapi.co/api/v2/version/10/'}},
  {'game_index': 25,
   'version': {'name': 'leafgreen',
    'url': 'https://pokeapi.co/api/v2/version/11/'}},
  {'game_index': 25,
   'version': {'name': 'diamond',
    'url': 'https://pokeapi.co/api/v2/version/12/'}},
  {'game_index': 25,
   'version': {'name': 'pearl',
    'url': 'https://pokeapi.co/api/v2/version/13/'}},
  {'game_index': 25,
   'version': {'name': 'platinum',
    'url': 'https://pokeapi.co/api/v2/version/14/'}},
  {'game_index': 25,
   'version': {'name': 'heartgold',
    'url': 'https://pokeapi.co/api/v2/version/15/'}},
  {'game_index': 25,
   'version': {'name': 'soulsilver',
    'url': 'https://pokeapi.co/api/v2/version/16/'}},
  {'game_index': 25,
   'version': {'name': 'black',
    'url': 'https://pokeapi.co/api/v2/version/17/'}},
  {'game_index': 25,
   'version': {'name': 'white',
    'url': 'https://pokeapi.co/api/v2/version/18/'}},
  {'game_index': 25,
   'version': {'name': 'black-2',
    'url': 'https://pokeapi.co/api/v2/version/21/'}},
  {'game_index': 25,
   'version': {'name': 'white-2',
    'url': 'https://pokeapi.co/api/v2/version/22/'}}],
 'height': 4,
 'held_items': [{'item': {'name': 'oran-berry',
    'url': 'https://pokeapi.co/api/v2/item/132/'},
   'version_details': [{'rarity': 50,
     'version': {'name': 'ruby',
      'url': 'https://pokeapi.co/api/v2/version/7/'}},
    {'rarity': 50,
     'version': {'name': 'sapphire',
      'url': 'https://pokeapi.co/api/v2/version/8/'}},
    {'rarity': 50,
     'version': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version/9/'}},
    {'rarity': 50,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rarity': 50,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rarity': 50,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}},
    {'rarity': 50,
     'version': {'name': 'heartgold',
      'url': 'https://pokeapi.co/api/v2/version/15/'}},
    {'rarity': 50,
     'version': {'name': 'soulsilver',
      'url': 'https://pokeapi.co/api/v2/version/16/'}},
    {'rarity': 50,
     'version': {'name': 'black',
      'url': 'https://pokeapi.co/api/v2/version/17/'}},
    {'rarity': 50,
     'version': {'name': 'white',
      'url': 'https://pokeapi.co/api/v2/version/18/'}}]},
  {'item': {'name': 'light-ball',
    'url': 'https://pokeapi.co/api/v2/item/213/'},
   'version_details': [{'rarity': 5,
     'version': {'name': 'ruby',
      'url': 'https://pokeapi.co/api/v2/version/7/'}},
    {'rarity': 5,
     'version': {'name': 'sapphire',
      'url': 'https://pokeapi.co/api/v2/version/8/'}},
    {'rarity': 5,
     'version': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version/9/'}},
    {'rarity': 5,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rarity': 5,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rarity': 5,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}},
    {'rarity': 5,
     'version': {'name': 'heartgold',
      'url': 'https://pokeapi.co/api/v2/version/15/'}},
    {'rarity': 5,
     'version': {'name': 'soulsilver',
      'url': 'https://pokeapi.co/api/v2/version/16/'}},
    {'rarity': 1,
     'version': {'name': 'black',
      'url': 'https://pokeapi.co/api/v2/version/17/'}},
    {'rarity': 1,
     'version': {'name': 'white',
      'url': 'https://pokeapi.co/api/v2/version/18/'}},
    {'rarity': 5,
     'version': {'name': 'black-2',
      'url': 'https://pokeapi.co/api/v2/version/21/'}},
    {'rarity': 5,
     'version': {'name': 'white-2',
      'url': 'https://pokeapi.co/api/v2/version/22/'}},
    {'rarity': 5,
     'version': {'name': 'x', 'url': 'https://pokeapi.co/api/v2/version/23/'}},
    {'rarity': 5,
     'version': {'name': 'y', 'url': 'https://pokeapi.co/api/v2/version/24/'}},
    {'rarity': 5,
     'version': {'name': 'omega-ruby',
      'url': 'https://pokeapi.co/api/v2/version/25/'}},
    {'rarity': 5,
     'version': {'name': 'alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version/26/'}},
    {'rarity': 5,
     'version': {'name': 'sun',
      'url': 'https://pokeapi.co/api/v2/version/27/'}},
    {'rarity': 5,
     'version': {'name': 'moon',
      'url': 'https://pokeapi.co/api/v2/version/28/'}},
    {'rarity': 5,
     'version': {'name': 'ultra-sun',
      'url': 'https://pokeapi.co/api/v2/version/29/'}},
    {'rarity': 5,
     'version': {'name': 'ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version/30/'}}]}],
 'id': 25,
 'is_default': True,
 'location_area_encounters': 'https://pokeapi.co/api/v2/pokemon/25/encounters',
 'moves': [{'move': {'name': 'mega-punch',
    'url': 'https://pokeapi.co/api/v2/move/5/'},
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'}}]},
  {'move': {'name': 'pay-day', 'url': 'https://pokeapi.co/api/v2/move/6/'},
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'}}]},
  {'move': {'name': 'thunder-punch',
    'url': 'https://pokeapi.co/api/v2/move/9/'},
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'scarlet-violet',
      'url': 'https://pokeapi.co/api/v2/version-group/25/'}}]},
  {'move': {'name': 'slam', 'url': 'https://pokeapi.co/api/v2/move/21/'},
   'version_group_details': [{'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'ruby-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/5/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
    {'level_learned_at': 21,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'}},
    {'level_learned_at': 21,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'}},
    {'level_learned_at': 21,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'}},
    {'level_learned_at': 26,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'black-white',
      'url': 'https://pokeapi.co/api/v2/version-group/11/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'colosseum',
      'url': 'https://pokeapi.co/api/v2/version-group/12/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'xd',
      'url': 'https://pokeapi.co/api/v2/version-group/13/'}},
    {'level_learned_at': 26,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'}},
    {'level_learned_at': 26,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'x-y',
      'url': 'https://pokeapi.co/api/v2/version-group/15/'}},
    {'level_learned_at': 37,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'}},
    {'level_learned_at': 37,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'sun-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/17/'}},
    {'level_learned_at': 37,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'}},
    {'level_learned_at': 24,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'}},
    {'level_learned_at': 28,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'}},
    {'level_learned_at': 28,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'brilliant-diamond-and-shining-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/23/'}}]},
  {'move': {'name': 'double-kick',
    'url': 'https://pokeapi.co/api/v2/move/24/'},
   'version_group_details': [{'level_learned_at': 9,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'}}]},
  {'move': {'name': 'mega-kick', 'url': 'https://pokeapi.co/api/v2/move/25/'},
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'}}]},
  {'move': {'name': 'headbutt', 'url': 'https://pokeapi.co/api/v2/move/29/'},
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'crystal',

In [113]:
type(data)

dict

In [114]:
data.keys()

dict_keys(['abilities', 'base_experience', 'cries', 'forms', 'game_indices', 'height', 'held_items', 'id', 'is_default', 'location_area_encounters', 'moves', 'name', 'order', 'past_abilities', 'past_types', 'species', 'sprites', 'stats', 'types', 'weight'])

In [82]:
# Lets look at the following attributes
print(data["name"])
print(data["weight"])
print(data["sprites"])

pikachu
60
{'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/25.png', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/female/25.png', 'other': {'dream_world': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/25.svg', 'front_female': None}, 'home': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/shiny/female/25.png'}, 'official-artwork': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/25.png'}, 'showdown': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/back/25.gif', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/back/female/25.gif', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/back/shiny/25.gif', 'back_shiny_female': None, 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/25.gif', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/female/25.gif', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/shiny/25.gif', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/shiny/female/25.gif'}}, 'versions': {'generation-i': {'red-blue': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/back/25.png', 'back_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/back/gray/25.png', 'back_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/back/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/25.png', 'front_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/gray/25.png', 'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/25.png'}, 'yellow': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/back/25.png', 'back_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/back/gray/25.png', 'back_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/transparent/back/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/25.png', 'front_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/gray/25.png', 'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/transparent/25.png'}}, 'generation-ii': {'crystal': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/back/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/back/shiny/25.png', 'back_shiny_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/transparent/back/shiny/25.png', 'back_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/transparent/back/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/shiny/25.png', 'front_shiny_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/transparent/shiny/25.png', 'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/transparent/25.png'}, 'gold': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/gold/back/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/gold/back/shiny/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/gold/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/gold/shiny/25.png', 'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/gold/transparent/25.png'}, 'silver': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/silver/back/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/silver/back/shiny/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/silver/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/silver/shiny/25.png', 'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/silver/transparent/25.png'}}, 'generation-iii': {'emerald': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/emerald/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/emerald/shiny/25.png'}, 'firered-leafgreen': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/firered-leafgreen/back/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/firered-leafgreen/back/shiny/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/firered-leafgreen/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/firered-leafgreen/shiny/25.png'}, 'ruby-sapphire': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/ruby-sapphire/back/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/ruby-sapphire/back/shiny/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/ruby-sapphire/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/ruby-sapphire/shiny/25.png'}}, 'generation-iv': {'diamond-pearl': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/25.png', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/female/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/shiny/25.png', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/shiny/female/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/shiny/female/25.png'}, 'heartgold-soulsilver': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/25.png', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/female/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/shiny/25.png', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/shiny/female/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/shiny/female/25.png'}, 'platinum': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/25.png', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/female/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/shiny/25.png', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/shiny/female/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/shiny/female/25.png'}}, 'generation-v': {'black-white': {'animated': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/25.gif', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/female/25.gif', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/shiny/25.gif', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/shiny/female/25.gif', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/25.gif', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/female/25.gif', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/shiny/25.gif', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/shiny/female/25.gif'}, 'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/25.png', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/female/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/shiny/25.png', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/shiny/female/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/shiny/female/25.png'}}, 'generation-vi': {'omegaruby-alphasapphire': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/shiny/female/25.png'}, 'x-y': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/shiny/female/25.png'}}, 'generation-vii': {'icons': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/icons/25.png', 'front_female': None}, 'ultra-sun-ultra-moon': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/shiny/female/25.png'}}, 'generation-viii': {'icons': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-viii/icons/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-viii/icons/female/25.png'}}}}

In [115]:
# Lets get the pokemon image from sprites - front_default.
# Remember we can read the documentation to understand how to get all the information
data['sprites']['front_default']

'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png'

We will define a function, `get_pokemon`, that takes an ID number as input. This function fetches details about a Pokémon from the PokeAPI using the given ID, extracts its name, weight, and front-facing image, and then returns this data in a dictionary format. If the ID is invalid or there's an issue with the request, a ValueError is raised.

In [116]:
def get_pokemon(id_number):
    res=requests.get(f'https://pokeapi.co/api/v2/pokemon/{id_number}')

    if(res.status_code==200):
        data = res.json()
        return {"id": id_number,'name':data['name'], "weight":data["weight"],'image':data['sprites']['front_default']}
    else:
        raise ValueError(f"Cannot get pokemon, {id_number} does not exist")

In [117]:
get_pokemon(25) # Lets use the function for pokemon id 25

{'id': 25,
 'name': 'pikachu',
 'weight': 60,
 'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png'}

In [118]:
[get_pokemon(i+1) for i in range(5)] # Lets use list comprehension to gather information for the first 5 pokemons

[{'id': 1,
  'name': 'bulbasaur',
  'weight': 69,
  'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png'},
 {'id': 2,
  'name': 'ivysaur',
  'weight': 130,
  'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png'},
 {'id': 3,
  'name': 'venusaur',
  'weight': 1000,
  'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png'},
 {'id': 4,
  'name': 'charmander',
  'weight': 85,
  'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png'},
 {'id': 5,
  'name': 'charmeleon',
  'weight': 190,
  'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png'}]

We will now define a function, `print_pokemon`, that takes in a Pokémon dictionary and displays its ID, name, weight, and its image.

In [119]:
from IPython.display import Image

def print_pokemon(poke):
    print(str(poke["id"])+" " +poke["name"]+ " "+str(poke["weight"]) + " kg")
    display(Image(url=poke['image']))

After defining this function, we will retrieve and display details for the first 10 Pokémon by iterating through their IDs and using both the `get_pokemon` and `print_pokemon` functions.

In [120]:
[print_pokemon(get_pokemon(i+1)) for i in range(10)]

1 bulbasaur 69 kg

2 ivysaur 130 kg

3 venusaur 1000 kg

4 charmander 85 kg

5 charmeleon 190 kg

6 charizard 905 kg

7 squirtle 90 kg

8 wartortle 225 kg

9 blastoise 855 kg

10 caterpie 29 kg

[None, None, None, None, None, None, None, None, None, None]

#### json_normalize()

Want the data as a DataFrame instead of a dictionary?

The following line creates a DataFrame from the items of the dictionary data. Each key-value pair will be treated as a row, with two columns: the first for the key and the second for the value.

In [121]:
df = pd.DataFrame(data.items())
df

,0,1
0,abilities,"[{'ability': {'name': 'static', 'url': 'https:..."
1,base_experience,112
2,cries,{'latest': 'https://raw.githubusercontent.com/...
3,forms,"[{'name': 'pikachu', 'url': 'https://pokeapi.c..."
4,game_indices,"[{'game_index': 84, 'version': {'name': 'red',..."
5,height,4
6,held_items,"[{'item': {'name': 'oran-berry', 'url': 'https..."
7,id,25
8,is_default,True
9,location_area_encounters,https://pokeapi.co/api/v2/pokemon/25/encounters
10,moves,"[{'move': {'name': 'mega-punch', 'url': 'https..."
11,name,pikachu
12,order,35
13,past_abilities,"[{'abilities': [{'ability': None, 'is_hidden':..."
14,past_types,[]
15,species,"{'name': 'pikachu', 'url': 'https://pokeapi.co..."
16,sprites,{'back_default': 'https://raw.githubuserconten...
17,stats,"[{'base_stat': 35, 'effort': 0, 'stat': {'name..."
18,types,"[{'slot': 1, 'type': {'name': 'electric', 'url..."
19,weight,60

That format is still very hard to work with. Lets use `json_normalize` instead. `json_normalize` is used to normalize semi-structured JSON data into a flat table (DataFrame). It's particularly useful when dealing with nested dictionaries or lists inside JSON.

In [122]:
df = pd.json_normalize(data)
df

,abilities,base_experience,forms,game_indices,height,held_items,id,is_default,location_area_encounters,moves,...,sprites.versions.generation-vi.x-y.front_shiny,sprites.versions.generation-vi.x-y.front_shiny_female,sprites.versions.generation-vii.icons.front_default,sprites.versions.generation-vii.icons.front_female,sprites.versions.generation-vii.ultra-sun-ultra-moon.front_default,sprites.versions.generation-vii.ultra-sun-ultra-moon.front_female,sprites.versions.generation-vii.ultra-sun-ultra-moon.front_shiny,sprites.versions.generation-vii.ultra-sun-ultra-moon.front_shiny_female,sprites.versions.generation-viii.icons.front_default,sprites.versions.generation-viii.icons.front_female
0,"[{'ability': {'name': 'static', 'url': 'https:...",112,"[{'name': 'pikachu', 'url': 'https://pokeapi.c...","[{'game_index': 84, 'version': {'name': 'red',...",4,"[{'item': {'name': 'oran-berry', 'url': 'https...",25,True,https://pokeapi.co/api/v2/pokemon/25/encounters,"[{'move': {'name': 'mega-punch', 'url': 'https...",...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,None,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...

A lot better, even though we still have nested dictionaries or lists inside the dataframe.

Let's see again the difference between creating a dataframe directly or using `json_normalize` by using `data["abilities"]`.

In [123]:
pd.DataFrame(data["abilities"])

                                             ability  is_hidden  slot
0  {'name': 'static', 'url': 'https://pokeapi.co/...      False     1
1  {'name': 'lightning-rod', 'url': 'https://poke...       True     3

In [92]:
pd.json_normalize(data["abilities"])

   is_hidden  slot   ability.name                            ability.url
0      False     1         static   https://pokeapi.co/api/v2/ability/9/
1       True     3  lightning-rod  https://pokeapi.co/api/v2/ability/31/

### Coincap API

CoinCap is a useful tool for real-time pricing and market activity for over 1,000 cryptocurrencies. Check the documentation at https://docs.coincap.io/

Again, this API is authenticated. Therefore, you need to register on the webpage, get an api key and add it your `.env` file and save it.

````
COIN_CAP_KEY="your key here"
````

In [157]:
url = "https://rest.coincap.io/v3/assets"#"http://api.coincap.io/v3/assets"

In [166]:
from requests.auth import HTTPBasicAuth

load_dotenv()
coincap_key = os.getenv("COIN_CAP_KEY")

headers = {"Authorization": f"Bearer {coincap_key}"}

response = requests.get(url, headers=headers)

In [167]:
print(response.status_code)

200

In [168]:
res = response.json()

In [169]:
res # it returns a dictionary with all the data

{'timestamp': 1759763896596,
 'data': [{'id': 'bitcoin',
   'rank': '1',
   'symbol': 'BTC',
   'name': 'Bitcoin',
   'supply': '19928203.000000000000000000',
   'maxSupply': '21000000.000000000000000000',
   'marketCapUsd': '2488036144550.000000000000000000',
   'volumeUsd24Hr': '57828072966.165931701660156250',
   'priceUsd': '124850.000000000000000000',
   'changePercent24Hr': '1.457872838382525',
   'vwap24Hr': '123556.2429027065',
   'explorer': 'https://blockchain.info/',
   'tokens': {}},
  {'id': 'ethereum',
   'rank': '2',
   'symbol': 'ETH',
   'name': 'Ethereum',
   'supply': '120703250.528552606701850891',
   'maxSupply': None,
   'marketCapUsd': '563089112943.234863281250000000',
   'volumeUsd24Hr': '35989208376.588737487792968750',
   'priceUsd': '4665.069999999999708962',
   'changePercent24Hr': '2.7593726595885175',
   'vwap24Hr': '4539.32445816351',
   'explorer': 'https://etherscan.io/',
   'tokens': {}},
  {'id': 'xrp',
   'rank': '3',
   'symbol': 'XRP',
   'name': 'XRP',
   'supply': '59871700035.000000000000000000',
   'maxSupply': '100000000000.000000000000000000',
   'marketCapUsd': '180255727295.374481201171875000',
   'volumeUsd24Hr': '4560175146.083730697631835938',
   'priceUsd': '3.010699999999999932',
   'changePercent24Hr': '0.5552925304491353',
   'vwap24Hr': '2.983206834522685',
   'explorer': 'https://xrpcharts.ripple.com/#/graph/',
   'tokens': {'56': ['0x1d2f0da169ceb9fc7b3144628db156f3f6c60dbe']}},
  {'id': 'tether',
   'rank': '4',
   'symbol': 'USDT',
   'name': 'Tether USDt',
   'supply': '177024150116.513061523437500000',
   'maxSupply': None,
   'marketCapUsd': '177112662191.571319580078125000',
   'volumeUsd24Hr': '885633862.723356604576110840',
   'priceUsd': '1.000499999999999945',
   'changePercent24Hr': '0.019994001799457962',
   'vwap24Hr': '1.0003890061924028',
   'explorer': 'https://www.omniexplorer.info/asset/31',
   'tokens': {'1': ['0xdac17f958d2ee523a2206206994597c13d831ec7'],
    '10': ['0x94b008aa00579c1307b0ef2c499ad98a8ce58e58'],
    '56': ['0x55d398326f99059ff775485246999027b3197955'],
    '101': ['es9vmfrzacermjfrf4h2fyd4kconky11mcce8benwnyb'],
    '137': ['0xc2132d05d31c914a87c6611c10748aeb04b58e8f'],
    '42161': ['0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9']}},
  {'id': 'binance-coin',
   'rank': '5',
   'symbol': 'BNB',
   'name': 'BNB',
   'supply': '139184626.180000007152557373',
   'maxSupply': None,
   'marketCapUsd': '169416651319.706298828125000000',
   'volumeUsd24Hr': '5003743187.550118446350097656',
   'priceUsd': '1217.208078000000114116',
   'changePercent24Hr': '4.928719960491016',
   'vwap24Hr': '1190.3960292707827',
   'explorer': 'https://etherscan.io/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52',
   'tokens': {'1': ['0xb8c77482e45f1f44de1745f52c74426c631bdd52'],
    '56': ['0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee']}},
  {'id': 'solana',
   'rank': '6',
   'symbol': 'SOL',
   'name': 'Solana',
   'supply': '545481721.028369784355163574',
   'maxSupply': None,
   'marketCapUsd': '128400396831.146942138671875000',
   'volumeUsd24Hr': '8313719265.986768722534179688',
   'priceUsd': '235.389000000000010004',
   'changePercent24Hr': '1.9918736174697016',
   'vwap24Hr': '231.05473489354802',
   'explorer': 'https://explorer.solana.com/',
   'tokens': {'101': ['so11111111111111111111111111111111111111112']}},
  {'id': 'usd-coin',
   'rank': '7',
   'symbol': 'USDC',
   'name': 'USDC',
   'supply': '75173931962.023651123046875000',
   'maxSupply': None,
   'marketCapUsd': '75136344996.042648315429687500',
   'volumeUsd24Hr': '3248939636.112485885620117188',
   'priceUsd': '0.999500000000000055',
   'changePercent24Hr': '-0.010004001600639153',
   'vwap24Hr': '0.9995540840491643',
   'explorer': 'https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
   'tokens': {'1': ['0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'],
    '10': ['0x0b2c639c533813f4aa9d7837caf62653d097ff85'],
    '56': ['0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d'],
    '101': ['epjfwdd5aufqssqem2qn1xzybapc8g4weggkzwytdt1v'],
    '137': ['0x3c499c542cef5e3811e1192ce70d8cc03d5c3359',
     '0x078d782b760474a361dda0af3839290b0ef57ad6'],
    '8453': ['0x833589fcd6edb6e08f4c7c32d4f71b54bda02913'],
    '42161': ['0xaf88d065e77c8cc2239327c5edb3a432268e5831'],
    '43114': ['0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e']}},
  {'id': 'dogecoin',
   'rank': '8',
   'symbol': 'DOGE',
   'name': 'Dogecoin',
   'supply': '151237736383.705230712890625000',
   'maxSupply': None,
   'marketCapUsd': '40161180896.692924499511718750',
   'volumeUsd24Hr': '3989070186.898902893066406250',
   'priceUsd': '0.265550000000000008',
   'changePercent24Hr': '3.9456686783298',
   'vwap24Hr': '0.25561962519791726',
   'explorer': 'http://dogechain.info/chain/Dogecoin',
   'tokens': {'56': ['0xba2ae424d960c26247dd6c32edc70b295c744c43']}},
  {'id': 'steth',
   'rank': '9',
   'symbol': 'STETH',
   'name': 'Lido Staked ETH',
   'supply': '8527012.721933510154485703',
   'maxSupply': None,
   'marketCapUsd': '39735879284.210159301757812500',
   'volumeUsd24Hr': '16928935.758858058601617813',
   'priceUsd': '4660.000000000000000000',
   'changePercent24Hr': '2.7155704461294263',
   'vwap24Hr': '4536.064802705256',
   'explorer': 'https://etherscan.io/token/0xae7ab96520de3a18e5e111b5eaab095312d7fe84',
   'tokens': {'1': ['0xae7ab96520de3a18e5e111b5eaab095312d7fe84']}},
  {'id': 'tron',
   'rank': '10',
   'symbol': 'TRX',
   'name': 'TRON',
   'supply': '94669413100.454605102539062500',
   'maxSupply': None,
   'marketCapUsd': '32749404725.869640350341796875',
   'volumeUsd24Hr': '1773681476.636003971099853516',
   'priceUsd': '0.345934379999999986',
   'changePercent24Hr': '1.002738686131375',
   'vwap24Hr': '0.3424525696067918',
   'explorer': 'https://tronscan.org/#/',
   'tokens': {'1': ['0x50327c6c5a14dcade707abad2e27eb517df87ab5'],
    '56': ['0xce7de646e7208a4ef112cb6ed5038fa6cc6b12e3']}},
  {'id': 'cardano',
   'rank': '11',
   'symbol': 'ADA',
   'name': 'Cardano',
   'supply': '35818890118.106613159179687500',
   'maxSupply': '45000000000.000000000000000000',
   'marketCapUsd': '31132623988.176399230957031250',
   'volumeUsd24Hr': '1138831233.928861856460571289',
   'priceUsd': '0.869167746000000019',
   'changePercent24Hr': '1.7284346910112325',
   'vwap24Hr': '0.8450338804858076',
   'explorer': 'https://cardanoexplorer.com/',
   'tokens': {'56': ['0x3ee2200efb3400fabb9aacf31297cbdd1d435d47']}},
  {'id': 'lido-finance-wsteth',
   'rank': '12',
   'symbol': 'WSTETH',
   'name': 'Lido wstETH',
   'supply': '3372452.310179899912327528',
   'maxSupply': None,
   'marketCapUsd': '19116424790.110115051269531250',
   'volumeUsd24Hr': '9986500.404059903696179390',
   'priceUsd': '5668.404778447517855966',
   'changePercent24Hr': '2.7632631699655477',
   'vwap24Hr': '5511.982073398085',
   'explorer': None,
   'tokens': {'1': ['0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0'],
    '10': ['0x1f32b1c2345538c0c6f582fcb022739c4a194ebb'],
    '137': ['0x03b54a6e9a984069379fae1a4fc4dbae93b3bccd'],
    '8453': ['0xc1cba3fcea344f92d9239c08c0568f6f2f0ee452'],
    '42161': ['0x5979d7b546e38e414f7e9822514be443a4800529']}},
  {'id': 'hyperliquid',
   'rank': '13',
   'symbol': 'HYPE',
   'name': 'Hyperliquid',
   'supply': '336685219.000000000000000000',
   'maxSupply': '1000000000.000000000000000000',
   'marketCapUsd': '16360881532.086000442504882813',
   'volumeUsd24Hr': '421799707.980705916881561279',
   'priceUsd': '48.594000000000001194',
   'changePercent24Hr': '-1.1030608922175218',
   'vwap24Hr': '48.44363472680348',
   'explorer': 'https://app.hyperliquid.xyz/explorer/token/0x0d01dc56dcaaca66ad901c959b4011ec',
   'tokens': {}},
  {'id': 'wrapped-bitcoin',
   'rank': '14',
   'symbol': 'WBTC',
   'name': 'Wrapped Bitcoin',
   'supply': '127204.907648359992890619',
   'maxSupply': None,
   'marketCapUsd': '15885503103.077716827392578125',
   'volumeUsd24Hr': '262652641.513930767774581909',
   'priceUsd': '124881.212499999979627319',
   'changePercent24Hr': '1.5076663183300065',
   'vwap24Hr': '123530.57857965223',
   'explorer': 'https://etherscan.io/token/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599',
   'tokens': {'1': ['0x2260fac5e5542a773aa44fbcfedf7c193bc2c599'],
    '10': ['0x68f180fcce6836688e9084f035309e29bf0a2095'],
    '101': ['3nz9jmvbmgaqocybic2c7lqcjscmgsaz6vqqtdzcqmjh'],
    '137': ['0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6'],
    '42161': ['0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f'],
    '43114': ['0x408d4cd0adb7cebd1f1a1c33a0ba2098e1295bab']}},
  {'id': 'weth',
   'rank': '15',
   'symbol': 'WETH',
   'name': 'WETH',
   'supply': '3375317.592646900098770857',
   'maxSupply': None,
   'marketCapUsd': '15702399098.550386428833007813',
   'volumeUsd24Hr': '523370524.134573519229888916',
   'priceUsd': '4652.124923816924820130',
   'changePercent24Hr': '2.439880672661239',
   'vwap24Hr': '4541.414050464285',
   'explorer': 'https://etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
   'tokens': {'1': ['0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'],
    '10': ['0x4200000000000000000000000000000000000006'],
    '56': ['0x2170ed0880ac9a755fd29b2688956bd959f933f8'],
    '101': ['2fpytwczlug1mdrwsyop4d6s1tm7hakhyrjknb5w6pxk'],
    '130': ['0x4200000000000000000000000000000000000006'],
    '137': ['0x7ceb23fd6bc0add59e62ac25578270cff1b9f619'],
    '8453': ['0x4200000000000000000000000000000000000006'],
    '42161': ['0x82af49447d8a07e3bd95bd0d56f35241523fbab1'],
    '43114': ['0x49d5c2bdffac6ce2bfdb6640f4f80f226bc10bab']}},
  {'id': 'chainlink',
   'rank': '16',
   'symbol': 'LINK',
   'name': 'Chainlink',
   'supply': '678099970.452586650848388672',
   'maxSupply': '1000000000.000000000000000000',
   'marketCapUsd': '15406431328.682767868041992188',
   'volumeUsd24Hr': '874152891.890310525894165039',
   'priceUsd': '22.719999999999998863',
   'changePercent24Hr': '0.8880994671403165',
   'vwap24Hr': '22.117470491837956',
   'explorer': 'https://etherscan.io/token/0x514910771af9ca656af840dff83e8264ecf986ca',
   'tokens': {'1': ['0x514910771af9ca656af840dff83e8264ecf986ca'],
    '10': ['0x350a791bfc2c21f9ed5d10980dad2e2638ffa7f6'],
    '56': ['0xf8a0bf9cf54bb92f17374d9e9a321e6a111a51bd'],
    '101': ['cwe8jptuyhdctzywpte1o5dfqfdjzwkc9wkz6rsjqudg'],
    '137': ['0x53e0bca35ec356bd5dddfebbd1fc0fd03fabad39'],
    '42161': ['0xf97f4df75117a78c1a5a0dbb814af92458539fb4'],
    '43114': ['0x5947bb275c521040051d82396192181b413227a3']}},
  {'id': 'ethena-usde',
   'rank': '17',
   'symbol': 'USDE',
   'name': 'Ethena USDe',
   'supply': '14818673589.908720016479492188',
   'maxSupply': None,
   'marketCapUsd': '14818673589.908720016479492188',
   'volumeUsd24Hr': '306813619.583478987216949463',
   'priceUsd': '1.000000000000000000',
   'changePercent24Hr': '0.030009002700806937',
   'vwap24Hr': '0.9997965102359158',
   'explorer': 'etherscan.io',
   'tokens': {'1': ['0x4c9edd5852cd905f086c759e8383e09bff1e68b3'],
    '56': ['0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34']}},
  {'id': 'sui',
   'rank': '18',
   'symbol': 'SUI',
   'name': 'Sui',
   'supply': '3625742933.075553894042968750',
   'maxSupply': '10000000000.000000000000000000',
   'marketCapUsd': '13302850821.454206466674804688',
   'volumeUsd24Hr': '951505376.043667912483215332',
   'priceUsd': '3.669000000000000039',
   'changePercent24Hr': '2.0555756446274116',
   'vwap24Hr': '3.589511670073843',
   'explorer': 'https://suiexplorer.com/',
   'tokens': {}},
  {'id': 'stellar',
   'rank': '19',
   'symbol': 'XLM',
   'name': 'Stellar',
   'supply': '31975422699.341747283935546875',
   'maxSupply': '50001806812.000000000000000000',
   'marketCapUsd': '13054270083.521911621093750000',
   'volumeUsd24Hr': '309959887.981677174568176270',
   'priceUsd': '0.408259499999999997',
   'changePercent24Hr': '2.7326371414192305',
   'vwap24Hr': '0.400374291426582',
   'explorer': 'https://dashboard.stellar.org/',
   'tokens': {}},
  {'id': 'avalanche',
   'rank': '20',
   'symbol': 'AVAX',
   'name': 'Avalanche',
   'supply': '422275285.489160835742950439',
   'maxSupply': '715748719.000000000000000000',
   'marketCapUsd': '13010301545.921045303344726563',
   'volumeUsd24Hr': '722524173.335880517959594727',
   'priceUsd': '30.809999999999998721',
   'changePercent24Hr': '2.4030312094924686',
   'vwap24Hr': '30.21788445700684',
   'explorer': 'https://avascan.info/',
   'tokens': {'56': ['0x1ce0c2827e2ef14d5c4f29a091d735a204794041'],
    '43114': ['0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7']}},
  {'id': 'wrapped-eeth',
   'rank': '21',
   'symbol': 'WEETH',
   'name': 'Wrapped eETH',
   'supply': '2458981.166399570181965828',
   'maxSupply': None,
   'marketCapUsd': '12340623932.784017562866210938',
   'volumeUsd24Hr': '824350.176415025489404798',
   'priceUsd': '5018.592294000000947563',
   'changePercent24Hr': '2.7299140235241945',
   'vwap24Hr': '4900.620204581458',
   'explorer': None,
   'tokens': {'1': ['0xcd5fe23c85820f7b72d0926fc9b05b43e359b7ee'],
    '10': ['0x5a7facb970d094b6c7ff1df0ea68d99e6e73cbff'],
    '56': ['0x04c0599ae5a44757c0af6f9ec3b93da8976c150a'],
    '8453': ['0x04c0599ae5a44757c0af6f9ec3b93da8976c150a'],
    '42161': ['0x35751007a407ca6feffe80b3cb397736d2cf4dbe']}},
  {'id': 'bitcoin-cash',
   'rank': '22',
   'symbol': 'BCH',
   'name': 'Bitcoin Cash',
   'supply': '19935315.625000000000000000',
   'maxSupply': '21000000.000000000000000000',
   'marketCapUsd': '11973150564.375000000000000000',
   'volumeUsd24Hr': '404575972.328049898147583008',
   'priceUsd': '600.600000000000022737',
   'changePercent24Hr': '0.8733624454148547',
   'vwap24Hr': '597.2939413073822',
   'explorer': 'https://blockchair.com/bitcoin-cash/blocks',
   'tokens': {'56': ['0x8ff795a6f4d97e7887c79bea79aba5cc76444adf']}},
  {'id': 'hedera-hashgraph',
   'rank': '23',
   'symbol': 'HBAR',
   'name': 'Hedera',
   'supply': '42392926541.718109130859375000',
   'maxSupply': '50000000000.000000000000000000',
   'marketCapUsd': '9742742377.817655563354492188',
   'volumeUsd24Hr': '228260116.543278753757476807',
   'priceUsd': '0.229819999999999997',
   'changePercent24Hr': '4.439900022722109',
   'vwap24Hr': '0.21917994326215368',
   'explorer': 'https://app.dragonglass.me/hedera/home',
   'tokens': {}},
  {'id': 'litecoin',
   'rank': '24',
   'symbol': 'LTC',
   'name': 'Litecoin',
   'supply': '76377020.733471348881721497',
   'maxSupply': '84000000.000000000000000000',
   'marketCapUsd': '9199612147.346624374389648438',
   'volumeUsd24Hr': '9700303432.448431015014648438',
   'priceUsd': '120.450000000000002842',
   'changePercent24Hr': '0.27798105333090223',
   'vwap24Hr': '119.77447681560938',
   'explorer': 'http://explorer.litecoin.net/chain/Litecoin',
   'tokens': {'56': ['0x4338665cbb7b2485a8855a139b75d5e34ab0db94']}},
  {'id': 'unus-sed-leo',
   'rank': '25',
   'symbol': 'LEO',
   'name': 'UNUS SED LEO',
   'supply': '922510901.899999976158142090',
   'maxSupply': None,
   'marketCapUsd': '8877414660.073890686035156250',
   'volumeUsd24Hr': '630388.033698247512802482',
   'priceUsd': '9.623100000000000875',
   'changePercent24Hr': '-0.04051106263633315',
   'vwap24Hr': '9.622076233395887',
   'explorer': 'https://eospark.com/account/bitfinexleo1',
   'tokens': {'1': ['0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3']}},
  {'id': 'bitcoin-bep2',
   'rank': '26',
   'symbol': 'BTCB',
   'name': 'Bitcoin BEP2',
   'supply': '65216.225183059999835677',
   'maxSupply': None,
   'marketCapUsd': '8152489808.101020812988281250',
   'volumeUsd24Hr': '20796385.452567998319864273',
   'priceUsd': '125007.078916592072346248',
   'changePercent24Hr': '1.58634147157325',
   'vwap24Hr': '123640.1623563688',
   'explorer': 'https://explorer.binance.org/asset/BTCB-1DE',
   'tokens': {'56': ['0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c']}},
  {'id': 'mantle',
   'rank': '27',
   'symbol': 'MNT',
   'name': 'Mantle',
   'supply': '3252944055.736840724945068359',
   'maxSupply': '6219316795.000000000000000000',
   'marketCapUsd': '7634984993.219939231872558594',
   'volumeUsd24Hr': '840837103.561173677444458008',
   'priceUsd': '2.347100000000000186',
   'changePercent24Hr': '13.026100356351739',
   'vwap24Hr': '2.153220571540249',
   'explorer': 'https://mantlescan.xyz/',
   'tokens': {'1': ['0x3c3a81e81dc49a522a592e7622a7e711c06bf354']}},
  {'id': 'shiba-inu',
   'rank': '28',
   'symbol': 'SHIB',
   'name': 'Shiba Inu',
   'supply': '589245796347436.500000000000000000',
   'maxSupply': '589552695333683.000000000000000000',
   'marketCapUsd': '7583593398.991508483886718750',
   'volumeUsd24Hr': '137105379.017649084329605103',
   'priceUsd': '0.000012870000000000',
   'changePercent24Hr': '1.498422712933753',
   'vwap24Hr': '0.00001255859191622536',
   'explorer': 'https://etherscan.io/token/0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce',
   'tokens': {'1': ['0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce'],
    '8453': ['0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce']}},
  {'id': 'crypto-com-coin',
   'rank': '29',
   'symbol': 'CRO',
   'name': 'Cronos',
   'supply': '34856132209.163467407226562500',
   'maxSupply': '100000000000.000000000000000000',
   'marketCapUsd': '7391939957.597296714782714844',
   'volumeUsd24Hr': '39366170.050782054662704468',
   'priceUsd': '0.212070000000000008',
   'changePercent24Hr': '1.221898716051743',
   'vwap24Hr': '0.2085143144893867',
   'explorer': 'https://etherscan.io/token/0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b',
   'tokens': {'1': ['0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b'],
    '101': ['dvjmymvexgkxaixgkpzqthlog98nc7hsu7eanzsdcboa']}},
  {'id': 'toncoin',
   'rank': '30',
   'symbol': 'TON',
   'name': 'Toncoin',
   'supply': '2518576329.377509117126464844',
   'maxSupply': None,
   'marketCapUsd': '7158045785.723817825317382813',
   'volumeUsd24Hr': '134238873.673640280961990356',
   'priceUsd': '2.842099999999999849',
   'changePercent24Hr': '1.2504453152832173',
   'vwap24Hr': '2.8156721082429077',
   'explorer': None,
   'tokens': {'1': ['0x582d872a1b094fc48f5de31d3b73f2d9be47def1'],
    '56': ['0x76a797a59ba2c17726896976b7b3747bfd1d220f']}},
  {'id': 'polkadot',
   'rank': '31',
   'symbol': 'DOT',
   'name': 'Polkadot',
   'supply': '1624126403.574950218200683594',
   'maxSupply': None,
   'marketCapUsd': '7142907922.922630310058593750',
   'volumeUsd24Hr': '377297799.694211423397064209',
   'priceUsd': '4.397999999999999687',
   'changePercent24Hr': '3.8979447200566986',
   'vwap24Hr': '4.191766547067562',
   'explorer': 'https://polkascan.io/polkadot',
   'tokens': {'56': ['0x7083609fce4d1d8dc0c979aab8c869ea2c873402']}},
  {'id': 'monero',
   'rank': '32',
   'symbol': 'XMR',
   'name': 'Monero',
   'supply': '18446744.073709551244974136',
   'maxSupply': None,
   'marketCapUsd': '5916602237.841176033020019531',
   'volumeUsd24Hr': '222661674.116559833288192749',
   'priceUsd': '320.739650000000040109',
   'changePercent24Hr': '-0.4451164104650037',
   'vwap24Hr': '320.818394306704',
   'explorer': 'http://moneroblocks.info/',
   'tokens': {}},
  {'id': 'multi-collateral-dai',
   'rank': '33',
   'symbol': 'DAI',
   'name': 'Dai',
   'supply': '5365382702.664872169494628906',
   'maxSupply': None,
   'marketCapUsd': '5361090396.502739906311035156',
   'volumeUsd24Hr': '69503239.915559843182563782',
   'priceUsd': '0.999199999999999977',
   'changePercent24Hr': '-0.030015007503759676',
   'vwap24Hr': '0.9994643976019632',
   'explorer': 'https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359',
   'tokens': {'1': ['0x6b175474e89094c44da98b954eedeac495271d0f']}},
  {'id': 'uniswap',
   'rank': '34',
   'symbol': 'UNI',
   'name': 'Uniswap',
   'supply': '630330527.710000038146972656',
   'maxSupply': None,
   'marketCapUsd': '5275831218.423149108886718750',
   'volumeUsd24Hr': '216492115.338057398796081543',
   'priceUsd': '8.369944000000000273',
   'changePercent24Hr': '2.0250071084601315',
   'vwap24Hr': '8.16002197071221',

In [164]:
# Again, let's try to have it as a dataframe
data = pd.DataFrame(res["data"])
data.head()

,id,rank,symbol,name,supply,maxSupply,marketCapUsd,volumeUsd24Hr,priceUsd,changePercent24Hr,vwap24Hr,explorer,tokens
0,bitcoin,1,BTC,Bitcoin,19928203.000000000000000000,21000000.000000000000000000,2485644361625.939941406250000000,57738751208.125450134277343750,124729.979999999995925464,1.360340007801323,123556.2429027065,https://blockchain.info/,{}
1,ethereum,2,ETH,Ethereum,120703250.528552606701850891,None,561726373244.767578125000000000,35827290257.990310668945312500,4653.779999999999745341,2.510683290012766,4539.32445816351,https://etherscan.io/,{}
2,xrp,3,XRP,XRP,59871700035.000000000000000000,100000000000.000000000000000000,179902484265.167999267578125000,4548953097.627026557922363281,3.004799999999999915,0.35823662121551797,2.983206834522685,https://xrpcharts.ripple.com/#/graph/,{'56': ['0x1d2f0da169ceb9fc7b3144628db156f3f6c...
3,tether,4,USDT,Tether USDt,177024150116.513061523437500000,None,177115790930.955535888671875000,881210768.360719323158264160,1.000517674082220809,0.0217608799580968,1.0003890061924028,https://www.omniexplorer.info/asset/31,{'1': ['0xdac17f958d2ee523a2206206994597c13d83...
4,binance-coin,5,BNB,BNB,139184626.180000007152557373,None,169361244982.085815429687500000,4990606574.918001174926757813,1216.809999999999945430,4.894403876216351,1190.3960292707827,https://etherscan.io/token/0xB8c77482e45F1F44d...,{'1': ['0xb8c77482e45f1f44de1745f52c74426c631b...

In [165]:
# Lets see if the result would differ in this case using json_normalize
pd.json_normalize(res["data"])

,id,rank,symbol,name,supply,maxSupply,marketCapUsd,volumeUsd24Hr,priceUsd,changePercent24Hr,...,tokens.56,tokens.1,tokens.10,tokens.101,tokens.137,tokens.42161,tokens.8453,tokens.43114,tokens.130,tokens.480
0,bitcoin,1,BTC,Bitcoin,19928203.000000000000000000,21000000.000000000000000000,2485644361625.939941406250000000,57738751208.125450134277343750,124729.979999999995925464,1.360340007801323,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ethereum,2,ETH,Ethereum,120703250.528552606701850891,None,561726373244.767578125000000000,35827290257.990310668945312500,4653.779999999999745341,2.510683290012766,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,xrp,3,XRP,XRP,59871700035.000000000000000000,100000000000.000000000000000000,179902484265.167999267578125000,4548953097.627026557922363281,3.004799999999999915,0.35823662121551797,...,[0x1d2f0da169ceb9fc7b3144628db156f3f6c60dbe],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,tether,4,USDT,Tether USDt,177024150116.513061523437500000,None,177115790930.955535888671875000,881210768.360719323158264160,1.000517674082220809,0.0217608799580968,...,[0x55d398326f99059ff775485246999027b3197955],[0xdac17f958d2ee523a2206206994597c13d831ec7],[0x94b008aa00579c1307b0ef2c499ad98a8ce58e58],[es9vmfrzacermjfrf4h2fyd4kconky11mcce8benwnyb],[0xc2132d05d31c914a87c6611c10748aeb04b58e8f],[0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9],NaN,NaN,NaN,NaN
4,binance-coin,5,BNB,BNB,139184626.180000007152557373,None,169361244982.085815429687500000,4990606574.918001174926757813,1216.809999999999945430,4.894403876216351,...,[0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee],[0xb8c77482e45f1f44de1745f52c74426c631bdd52],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,aerodrome-finance,96,AERO,Aerodrome Finance,902056147.990365743637084961,None,1061990703.029057621955871582,48190212.483846187591552734,1.177300000000000013,1.666666666666675,...,NaN,NaN,NaN,NaN,NaN,NaN,[0x940181a94a35a4569e4529a3cdfb74e38fd98631],NaN,NaN,NaN
96,dexe,97,DEXE,DeXe,83733647.455131724476814270,None,989019976.916288256645202637,10898428.230733722448348999,11.811499999999998778,-0.11416490486258363,...,[0x6e88056e8376ae7709496ba64d37fa2f8015ce3e],[0xde4ee8057785a7e8e800db58f9784845a5c2cbd6],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,floki-inu,98,FLOKI,FLOKI,9539435236606.406250000000000000,None,982180251.960995674133300781,167388165.925057351589202881,0.000102960000000000,0.19462826002336012,...,[0xfb5b838b6cfeedc2873ab27866079ac55363d37e],[0xcf0c122c6b73ff809c693db761e7baebe62b6a2e],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,tether-gold,99,XAUT,Tether Gold,246524.000000000000000000,None,974681938.799999952316284180,9760275615.968353271484375000,3953.699999999999818101,1.5983553899524556,...,NaN,[0x68749665ff8d2d112fa859aa293f07a622782f38],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,pyth-network,100,PYTH,Pyth Network,5749983335.930120468139648438,10000000000.000000000000000000,959097220.433144092559814453,78531697.025366812944412231,0.166800000000000004,4.054897067997508,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 💡 Check for understanding

Choose one API from the [Public APIs list](https://github.com/public-apis/public-apis). Attempt to call your selected API, either with or without parameters, and retrieve some valuable information. Document your findings.

In [2]:
# Chosen API: Open-Meteo (https://open-meteo.com/) -- a free weather
# forecast API that needs no API key/authentication, so it's a quick way
# to try parameters without dealing with .env setup first.

weather_url = "https://api.open-meteo.com/v1/forecast"
weather_params = {
    "latitude": 40.4168,      # Madrid
    "longitude": -3.7038,
    "current": "temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code",
    "timezone": "Europe/Madrid",
}

weather_response = requests.get(weather_url, params=weather_params)
print(weather_response.status_code)

weather_data = weather_response.json()
weather_data

200

{'latitude': 40.4375,
 'longitude': -3.6875,
 'generationtime_ms': 0.0730752944946289,
 'utc_offset_seconds': 7200,
 'timezone': 'Europe/Madrid',
 'timezone_abbreviation': 'GMT+2',
 'elevation': 666.0,
 'current_units': {'time': 'iso8601',
  'interval': 'seconds',
  'temperature_2m': '°C',
  'relative_humidity_2m': '%',
  'wind_speed_10m': 'km/h',
  'weather_code': 'wmo code'},
 'current': {'time': '2026-09-08T09:00',
  'interval': 900,
  'temperature_2m': 23.5,
  'relative_humidity_2m': 39,
  'wind_speed_10m': 2.2,
  'weather_code': 2}}

**Findings**: Open-Meteo needs no auth at all -- just lat/long plus a `current` param listing which fields to return, and it replies immediately with current conditions for that point (temperature, humidity, wind, a WMO weather code). Useful pattern worth keeping in mind for future APIs: check the docs for a no-auth quickstart before assuming every API needs a `.env` key -- some genuinely don't.

## API Wrappers

A Python wrapper is a Python library or module that provides a more convenient or more "Pythonic" interface to another software component, such as a library in another language, a system tool, or a web API. It "wraps" the functionality of that component in a way that abstracts away its complexities and makes it easier to use in a Python context. 🙌🏻

One example is the `tweepy` library, which makes obtaining data from Twitter's API relatively straightforward.

## Summary
- Import the `requests` library.
- Store the necessary credentials, such as API key or OAuth tokens, if the API requires them.
- Execute a `request.get` to the desired API endpoint (the API's documentation will provide details on available endpoints).
- The API returns a JSON response.
- This JSON can be converted into a dataframe, or you can further explore its elements (typically a list of dictionaries).

## Glossary

* DNS: domain name system.
* HTTP: is the protocol used to transfer data over the web.
* API: application programming interface.
* REST: series of rules, architectural style.

* `requests`: Python library for interacting with APIs.
* URL: server name you want to ask information for.
* endpoint: server service you want to ask information for.
* parameters: extra parameters to your query.
* headers: metadata, invisible information.

## Further materials

[5 Simple-To-Use APIs for Beginners](https://dev.to/alanconstantino/5-simple-to-use-apis-for-beginners-2e0n)

[RapidAPI](https://rapidapi.com/category/Sports): access thousands of APIs.