# Web Scraping

![legtsgo](https://media.giphy.com/media/dwmNhd5H7YAz6/giphy.gif)

By the end of this lesson, you will be able to:

- Identify the primary components of web technologies and their roles: HTML, CSS, and JavaScript.
- Explain the hierarchical structure of HTML and the significance of tags, attributes, and their relationship.
- Utilize the **requests** and **Beautiful Soup** libraries to scrape data from a static web page.
- Construct and execute a script to scrape data from a webpage and export it into a structured text file using the pandas library.

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Web-Scraping" data-toc-modified-id="Web-Scraping-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Web Scraping</a></span><ul class="toc-item"><li><span><a href="#What-is-Web-Scraping" data-toc-modified-id="What-is-Web-Scraping-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>What is Web Scraping</a></span></li><li><span><a href="#Web-structure" data-toc-modified-id="Web-structure-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Web structure</a></span></li><li><span><a href="#HTML" data-toc-modified-id="HTML-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>HTML</a></span><ul class="toc-item"><li><span><a href="#Exploring-Web-Page-Structures" data-toc-modified-id="Exploring-Web-Page-Structures-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Exploring Web Page Structures</a></span></li><li><span><a href="#Fact-1:-HTML-is-Built-on-Tags" data-toc-modified-id="Fact-1:-HTML-is-Built-on-Tags-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Fact 1: HTML is Built on Tags</a></span></li><li><span><a href="#Fact-2:-Tags-Can-Have-Attributes" data-toc-modified-id="Fact-2:-Tags-Can-Have-Attributes-1.3.3"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>Fact 2: Tags Can Have Attributes</a></span></li><li><span><a href="#Fact-3:-Tags-Can-Be-Nested" data-toc-modified-id="Fact-3:-Tags-Can-Be-Nested-1.3.4"><span class="toc-item-num">1.3.4&nbsp;&nbsp;</span>Fact 3: Tags Can Be Nested</a></span></li><li><span><a href="#Selecting-Specific-Elements-in-Web-Scraping" data-toc-modified-id="Selecting-Specific-Elements-in-Web-Scraping-1.3.5"><span class="toc-item-num">1.3.5&nbsp;&nbsp;</span>Selecting Specific Elements in Web Scraping</a></span></li></ul></li><li><span><a href="#Web-Scraping-with-Python" data-toc-modified-id="Web-Scraping-with-Python-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Web Scraping with Python</a></span><ul class="toc-item"><li><span><a href="#Requests:-Fetching-a-Web-Page" data-toc-modified-id="Requests:-Fetching-a-Web-Page-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Requests: Fetching a Web Page</a></span></li><li><span><a href="#Parsing-HTML-with-Beautiful-Soup" data-toc-modified-id="Parsing-HTML-with-Beautiful-Soup-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>Parsing HTML with Beautiful Soup</a></span><ul class="toc-item"><li><span><a href="#Extracting-Data" data-toc-modified-id="Extracting-Data-1.4.2.1"><span class="toc-item-num">1.4.2.1&nbsp;&nbsp;</span>Extracting Data</a></span></li><li><span><a href="#More-filtering-options" data-toc-modified-id="More-filtering-options-1.4.2.2"><span class="toc-item-num">1.4.2.2&nbsp;&nbsp;</span>More filtering options</a></span></li><li><span><a href="#Creating-a-DataFrame-with-the-data" data-toc-modified-id="Creating-a-DataFrame-with-the-data-1.4.2.3"><span class="toc-item-num">1.4.2.3&nbsp;&nbsp;</span>Creating a DataFrame with the data</a></span></li><li><span><a href="#💡-Check-for-understanding" data-toc-modified-id="💡-Check-for-understanding-1.4.2.4"><span class="toc-item-num">1.4.2.4&nbsp;&nbsp;</span>💡 Check for understanding</a></span></li><li><span><a href="#Scraping-many-pages" data-toc-modified-id="Scraping-many-pages-1.4.2.5"><span class="toc-item-num">1.4.2.5&nbsp;&nbsp;</span>Scraping many pages</a></span></li><li><span><a href="#CSS-selectors" data-toc-modified-id="CSS-selectors-1.4.2.6"><span class="toc-item-num">1.4.2.6&nbsp;&nbsp;</span>CSS selectors</a></span></li></ul></li><li><span><a href="#More-examples" data-toc-modified-id="More-examples-1.4.3"><span class="toc-item-num">1.4.3&nbsp;&nbsp;</span>More examples</a></span><ul class="toc-item"><li><span><a href="#BBC" data-toc-modified-id="BBC-1.4.3.1"><span class="toc-item-num">1.4.3.1&nbsp;&nbsp;</span>BBC</a></span></li></ul></li></ul></li><li><span><a href="#Comments" data-toc-modified-id="Comments-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Comments</a></span></li><li><span><a href="#Summary" data-toc-modified-id="Summary-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Summary</a></span></li><li><span><a href="#Further-materials" data-toc-modified-id="Further-materials-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Further materials</a></span><ul class="toc-item"><li><span><a href="#How-to-Solve-a-403-Error" data-toc-modified-id="How-to-Solve-a-403-Error-1.7.1"><span class="toc-item-num">1.7.1&nbsp;&nbsp;</span>How to Solve a 403 Error</a></span></li></ul></li></ul></li></ul></div>

## What is Web Scraping

Web scraping is a method employed by data analysts and developers to retrieve information from web pages. It involves fetching a web page and then parsing that page to obtain desired information. This technique is especially useful when the desired data isn't available through APIs. The extracted data can then be cleaned, analyzed, or stored in databases for further data analytics tasks.

## Web structure

The fundamental web technologies that form the structure of the websites we aim to scrape are:

- **HTML**: Standing as the backbone of almost all websites, HTML, the core markup language, is instrumental in creating web pages. It houses all the content available on a webpage.
  
- **CSS**: This stylesheet language works alongside HTML, taking charge of the presentation aspect of the webpages. It controls how HTML elements are displayed, setting the stage for a visually pleasing and organized web interface.

- **JavaScript**: Adding a dynamic touch to the websites, JavaScript comes into play to create interactive and animated content. This programming language has the power to alter webpage content even after it has loaded, bringing a dynamic and responsive element to web designs.

In this lesson, we will work with the HTML from the websites.

## HTML

In the realm of web scraping, understanding HTML (Hypertext Markup Language) is crucial.

HTML is the standard markup language used to create web pages. Think of it as the skeleton or blueprint of a website. It structures content on the web, defining elements like paragraphs, headings, links, lists, and images. These elements are represented by "tags", which enclose content to give it meaning and context.

When web scraping, you'll often navigate through this HTML structure to pinpoint and extract the exact data you need. Tools like web browsers' "Inspect" or "View Source" features allow you to see the underlying HTML of a page, which is invaluable when determining how to access specific pieces of content programmatically.

![](https://github.com/data-bootcamp-v4/lessons/blob/main/img/html.png?raw=true)

### Exploring Web Page Structures

To inspect the underlying HTML of a web page, right-click anywhere on the page. Choose "View Page Source" in browsers like Chrome or Firefox. For Internet Explorer, choose "View Source," and for Safari, select "Show Page Source." (In Safari, if this option isn't visible, navigate to Safari Preferences, click on the Advanced tab, and enable "Show Develop menu in menu bar.")

To embark on your web scraping journey, you just need to grasp **three foundational aspects** of HTML.

### Fact 1: HTML is Built on Tags

At its core, HTML is composed of content enveloped in `<tags>`. It typically houses the textual content we aim to scrape, highlighted by these "tags" enclosed by angle brackets. These tags give structure and meaning, instructing the browser on how to present the content. The acronym "HTML" stands for Hyper Text Markup Language.

HTML follows a tree-like structure, encompassing parent tags, child tags, and sibling tags:
```
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
        <h1>My First Heading</h1>
        <p>My first paragraph.</p>
    </body>
</html>
```

For instance, consider the `<strong>` tag, signaling bold formatting. If "Jan. 21" is encapsulated between an opening `<strong>` tag and its corresponding closing `</strong>` tag, it denotes where the bold styling begins and ends. This pair of tags instructs the browser to render the enclosed text, "Jan. 21", in bold.

Tags come in various types, each suited to encapsulate specific content:
 * **Headings**: `<h1>`, `<h2>`, `<h3>`, `<h4>`...
 * **Phrasing**: `<b>`, `<strong>`, `<sub>`, `<i>`, `<a>`...
 * **Embedded Content**: `<audio>`, `<img>`, `<video>`, `<iframe>`...
 * **Tabulated Data**: `<table>`, `<tr>`, `<td>`, `<tbody>`...
 * **Page Sections**: `<header>`, `<section>`, `<nav>`, `<article>`...
 * **Metadata and Scripts**: `<meta>`, `<title>`, `<script>`, `<link>`...

### Fact 2: Tags Can Have Attributes

HTML tags can possess "attributes," which are defined within the opening tag itself.

Examine the following examples:

- `<span class="short-desc">`: Here, the `<span>` tag has a `class` attribute with the value "short-desc".
- `<div> Zapas Marca Joma X54 </div>`: This tag doesn't contain any attributes.
- `<div class="price-item" id="offer"> Zapas Marca Joma X54 </div>`: The `div` tag here has two attributes - `class` with the value "price-item" and `id` with the value "offer".
- `<a class="text-monospace" id="name_132" href="http://www.example.com"> Page Content </a>
`: This `div` tag encompasses the following attributes:
    + `class`: With the value "text-monospace". Remember, the class isn't unique across the page.
    + `id`: With the value "name_132". IDs are meant to be unique identifiers for tags on the page.
    + `href`: With the value www.example.com. The href commonly represents a link to another section of the page or to an external website.

**Key Notes**:
- The `id` attribute should be unique for a tag; no two tags should share the same `id`.
- The `class` attribute isn't meant to be unique. Instead, it often groups tags exhibiting similar behavior or styles.

For web scraping purposes, **understanding the semantics** behind terms like `<span>`, `class`, or `short-desc` **isn't crucial**. The key takeaway is recognizing that tags can possess attributes and understanding their structural representation. When extracting content, our goal is to pinpoint the right tags within a webpage's HTML.

**Other commonly used attributes in HTML**

Several attributes in HTML provide additional information or modify elements. Some of these frequently used attributes include:

 * **`dir`**: Determines the text direction within an element, allowing for either forward or backward writing.
 * **`lang`**: Designates the language of the content within an element.
 * **`style`**: Applies inline styling to an element (Note: This shouldn't be mixed up with the `<style>` tag).
 * **`title`**: Offers supplementary details about an element, often displayed as a tooltip (Important: This is distinct from the `<title>` tag).

...and many more.


### Fact 3: Tags Can Be Nested

Imagine the following segment of HTML code:

`Hello <strong><em>Ironhack</em> students</strong>`

Here, the phrase **Ironhack students** would be displayed in bold since it resides between the `<strong>` and `</strong>` tags. Additionally, the word ***Ironhack*** would be italicized due to the `<em>` tag, which signifies italic formatting. However, the word "Hello" remains unaffected by any formatting, as it lies outside both the `<strong>` and `<em>` tags. This results in the display:

Hello ***Ironhack* students**

This example illustrates a key principle: **tags influence the text from their opening to their closing points,** even if they are nested within other tags.

### Selecting Specific Elements in Web Scraping

When diving into web scraping, it's essential to target specific elements efficiently. To hone in on the precise content you need, consider filtering tags based on:

 * **Tag Name**: The main type of the element (e.g., `<div>`, `<a>`, `<p>`).
 * **Class**: A descriptor that groups multiple elements with similar characteristics.
 * **ID**: A unique identifier assigned to a particular element.
 * **Other Attributes**: Additional properties like `href`, `title`, or `lang` that can further specify the elements of interest.

## Web Scraping with Python

In this lesson, we'll use the `requests` library to fetch web pages and `Beautiful Soup` from the `bs4` package to parse these pages and extract information.

Ensure you've installed the required packages:

In [1]:
!pip install requests beautifulsoup4

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.4.22)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)

### Requests: Fetching a Web Page

First, we use the `requests` library to fetch the content of a webpage.

In [7]:
import requests

url = "https://www.decathlon.com/collections/camp-hike"

# Now we identify ourserlves as "humans", and not bots to avoid being blocked.
# To know what to write below, open the following website:
# https://httpbin.org/user-agent
# And replace the dictionary by the given one.
headers = {
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36"
}
#"https://www.decathlon.com/products/xc50-mountain-bike-29-311942?_pos=2&_sid=149e6358f&_ss=r"#"https://www.decathlon.com/collections/mountain-bikes"
response = requests.get(url, headers=headers)
response

The provided code retrieves the webpage content from the given URL and saves it in a `response` object. This object possesses either a `text` or `content` attribute, holding the HTML code similar to what we observe when inspecting the source in a web browser.

In [8]:
response.content

b'<!doctype html>\n<html\n  \n  lang="en"\n>\n  <head><link\n        rel="icon"\n        type="image/png"\n        href="//www.decathlon.com/cdn/shop/files/favicon-large.png?crop=center&height=32&v=1749504383&width=32"\n      ><!-- Preload Decathon fonts ================================================== -->\n    \n    \n    \n    <link href="//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Brand-SemiBold.woff2?v=4101535601310826581777060469" as="font" type="font/woff2" crossorigin="anonymous" rel="preload">\n    <link href="//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Display-SemiBold.woff2?v=100345316253960588891777060469" as="font" type="font/woff2" crossorigin="anonymous" rel="preload">\n    <link href="//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Text-Medium.woff2?v=52324173899180483681777060469" as="font" type="font/woff2" crossorigin="anonymous" rel="preload">\n    <link href="//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Text-SemiBold.woff2?v=2220433650020876521777060469" as="font" type="font/woff2" crossorigin="anonymous" rel="preload">\n    <style data-shopify>\n    @font-face {\n      font-family: \'Decathlon Display\';\n      src: url(//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Display-SemiBold.woff2?v=100345316253960588891777060469)format(\'woff2\');\n      font-weight: 700;\n      font-style: normal;\n      font-display: swap;\n    }\n    @font-face {\n      font-family: \'Decathlon Brand\';\n      src: url(//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Brand-SemiBold.woff2?v=4101535601310826581777060469)format(\'woff2\');\n      font-weight: 700;\n      font-style: normal;\n      font-display: swap;\n    }\n    @font-face {\n      font-family: \'Decathlon Text\';\n      src: url(//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Text-SemiBold.woff2?v=2220433650020876521777060469)format(\'woff2\');\n      font-weight: 700;\n      font-style: normal;\n      font-display: swap;\n    }\n    @font-face {\n      font-family: \'Decathlon Text\';\n      src: url(//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Text-Medium.woff2?v=52324173899180483681777060469)format(\'woff2\');\n      font-weight: 500;\n      font-style: normal;\n      font-display: swap;\n    }\n\n    .font-sub-l {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 600;\n    font-size: 20px;\n    line-height: 150%;\n    letter-spacing: 0;\n    max-width: 720px;\n  }\n  .font-sub-m {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 600;\n    font-size: 16px;\n    line-height: 150%;\n    letter-spacing: 0;\n    max-width: 640px;\n  }\n  .font-body-l {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 500;\n    font-size: 20px;\n    line-height: 150%;\n    letter-spacing: 0;\n    max-width: 720px;\n  }\n  .font-body-m {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 500;\n    font-size: 16px;\n    line-height: 150%;\n    letter-spacing: 0;\n    max-width: 640px;\n  }\n  .font-body-s {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 500;\n    font-size: 14px;\n    line-height: 143%;\n    letter-spacing: 0;\n    max-width: 480px;\n  }\n  .font-cap {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 500;\n    font-size: 12px;\n    line-height: 133%;\n    letter-spacing: 0;\n  }\n  .font-link-l {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 500;\n    font-size: 20px;\n    line-height: 150%;\n    letter-spacing: 0;\n  }\n  .font-link-m {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 500;\n    font-size: 16px;\n    line-height: 150%;\n    letter-spacing: 0;\n  }\n  .font-link-s {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 500;\n    font-size: 14px;\n    line-height: 143%;\n    letter-spacing: 0;\n  }\n  .font-link-cap {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 500;\n    font-size: 12px;\n    line-height: 133%;\n    letter-spacing: 0;\n  }\n  .font-btn-m {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 500;\n    font-size: 14px;\n    line-height: 170%;\n    letter-spacing: 0;\n  }\n  .font-btn-s {\n    font-family: \'Decathlon Text\', sans-serif;\n    font-weight: 500;\n    font-size: 12px;\n    line-height: 130%;\n    letter-spacing: 0;\n  }\n  .font-brand-xl {\n    font-family: \'Decathlon Brand\', sans-serif;\n    font-weight: 600;\n    font-size: 48px;\n    line-height: 108%;\n    letter-spacing: 0;\n  }\n  .font-title-xl {\n    font-family: \'Decathlon Display\', sans-serif;\n    font-weight: 600;\n    font-size: 48px;\n    line-height: 108%;\n    letter-spacing: 0;\n  }\n  .font-title-l {\n    font-family: \'Decathlon Display\', sans-serif;\n    font-weight: 600;\n    font-size: 36px;\n    line-height: 111%;\n    letter-spacing: 0;\n  }\n  .font-title-m {\n    font-family: \'Decathlon Display\', sans-serif;\n    font-weight: 600;\n    font-size: 26px;\n    line-height: 123%;\n    letter-spacing: 0;\n  }\n  .font-title-s {\n    font-family: \'Decathlon Display\', sans-serif;\n    font-weight: 600;\n    font-size: 22px;\n    line-height: 118%;\n    letter-spacing: 0;\n  }\n  .font-overline {\n    font-family: \'Decathlon Display\', sans-serif;\n    font-weight: 600;\n    font-size: 14px;\n    line-height: 117%;\n    letter-spacing: 0;\n  }\n  /* Large Screens */\n  @media screen and (min-width: 390px) {\n    .font-brand-xl {\n      font-family: \'Decathlon Brand\', sans-serif;\n      font-weight: 600;\n      font-size: 56px;\n      line-height: 107%;\n      letter-spacing: 0;\n    }\n    .font-title-xl {\n      font-family: \'Decathlon Display\', sans-serif;\n      font-weight: 600;\n      font-size: 56px;\n      line-height: 107%;\n      letter-spacing: 0;\n    }\n    .font-title-l {\n      font-family: \'Decathlon Display\', sans-serif;\n      font-weight: 600;\n      font-size: 40px;\n      line-height: 110%;\n      letter-spacing: 0;\n    }\n    .font-title-m {\n      font-family: \'Decathlon Display\', sans-serif;\n      font-weight: 600;\n      font-size: 26px;\n      line-height: 123%;\n      letter-spacing: 0;\n    }\n    .font-title-s {\n      font-family: \'Decathlon Display\', sans-serif;\n      font-weight: 600;\n      font-size: 22px;\n      line-height: 118%;\n      letter-spacing: 0;\n    }\n    .font-overline {\n      font-family: \'Decathlon Display\', sans-serif;\n      font-weight: 600;\n      font-size: 16px;\n      line-height: 117%;\n      letter-spacing: 0;\n    }\n  }\n  /* Large Screens */\n  @media screen and (min-width: 1024px) {\n    .font-brand-xl {\n      font-family: \'Decathlon Brand\', sans-serif;\n      font-weight: 600;\n      font-size: 74px;\n      line-height: 108%;\n      letter-spacing: 0;\n    }\n    .font-title-xl {\n      font-family: \'Decathlon Display\', sans-serif;\n      font-weight: 600;\n      font-size: 74px;\n      line-height: 108%;\n      letter-spacing: 0;\n    }\n    .font-title-l {\n      font-family: \'Decathlon Display\', sans-serif;\n      font-weight: 600;\n      font-size: 48px;\n      line-height: 117%;\n      letter-spacing: 0;\n    }\n    .font-title-m {\n      font-family: \'Decathlon Display\', sans-serif;\n      font-weight: 600;\n      font-size: 32px;\n      line-height: 119%;\n      letter-spacing: 0;\n    }\n    .font-title-s {\n      font-family: \'Decathlon Display\', sans-serif;\n      font-weight: 600;\n      font-size: 22px;\n      line-height: 118%;\n      letter-spacing: 0;\n    }\n    .font-overline {\n      font-family: \'Decathlon Display\', sans-serif;\n      font-weight: 600;\n      font-size: 16px;\n      line-height: 129%;\n      letter-spacing: 0;\n    }\n  }\n\n  /*================== Decathlon Buttons ==================*/\n  /* Base */\n  .btn {\n    display: inline-flex;\n    align-items: center;\n    justify-content: center;\n    gap: 8px;\n    padding: 20px 32px; /* default size */\n    border: 0;\n    cursor: pointer;\n    transition: background-color 0.15s ease, color 0.15s ease;\n  }\n\n  /* Shape modifiers */\n  .btn--sqaure {\n    padding: 20px 32px;\n  }\n  .btn--pill {\n    padding: 12px 16px;\n    border-radius: 100px;\n  }\n\n  /* Color Variants */\n  .btn--brand {\n    background: var(--color-brand);\n    color: var(--color-white);\n  }\n  .btn--white {\n    background: var(--color-white);\n    color: var(--color-brand);\n    border: 1px solid var(--color-brand);\n  }\n  .btn--catchy {\n    background: var(--color-catchy);\n    color: var(--color-black);\n  }\n\n  /* Hover & active */\n  .btn--brand:hover {\n    background: var(--color-brand-hover);\n  }\n  .btn--brand:active {\n    background: var(--color-brand-active);\n  }\n\n  .btn--white:hover {\n    background: var(--color-white-hover);\n  }\n  .btn--white:active {\n    background: var(--color-white-active);\n  }\n\n  .btn--catchy:hover {\n    background: var(--color-catchy-hover);\n  }\n  .btn--catchy:active {\n    background: var(--color-catchy-active);\n  }\n\n  /* Disabled */\n  .btn[disabled],\n  .btn:disabled {\n    background: var(--color-gray-10);\n    color: var(--color-gray-40);\n    border-color: var(--color-gray-20);\n    cursor: not-allowed;\n  }\n\n  /* Focus-visible (keyboard) */\n  .btn:focus-visible {\n    outline: 2px solid var(--color-brand);\n    outline-offset: 2px;\n  }\n</style>\n\n\n    <!-- Microsft Calrity Script -->\n    <script async crossorigin fetchpriority="high" src="/cdn/shopifycloud/importmap-polyfill/es-modules-shim.2.4.0.js"></script>\n<script type="text/javascript">\n      (function (c, l, a, r, i, t, y) {\n        c[a] =\n          c[a] ||\n          function () {\n            (c[a].q = c[a].q || []).push(arguments);\n          };\n        t = l.createElement(r);\n        t.async = 1;\n        t.src = \'https://www.clarity.ms/tag/\' + i;\n        y = l.getElementsByTagName(r)[0];\n        y.parentNode.insertBefore(t, y);\n      })(window, document, \'clarity\', \'script\', \'s55kwp0oug\');\n    </script>\n\n    \n    \n    \n\n\n<meta charset="utf-8">\n<meta\n  http-equiv="X-UA-Compatible"\n  content="IE=edge"\n>\n<meta\n  name="viewport"\n  content="width=device-width,initial-scale=1"\n>\n<meta\n  name="view-transition"\n  content="same-origin"\n>\n<meta\n  name="theme-color"\n  content=""\n>\n\n<meta\n  property="og:site_name"\n  content="Decathlon"\n>\n<meta\n  property="og:url"\n  content="https://www.decathlon.com/collections/camp-hike"\n>\n<meta\n  property="og:title"\n  content="Hiking &amp; Backpacking Gear"\n>\n<meta\n  property="og:type"\n  content="website"\n>\n<meta\n  property="og:description"\n  content="Shop our selection of hiking and backpacking equipment designed by Decathlon. Enjoy free U.S. standard shipping on orders over $49! Free returns up to 90 days!"\n><meta\n    property="og:image"\n    content="http://www.decathlon.com/cdn/shop/collections/Collections-Herobanner-Camp-_-hike.jpg?v=1759928429"\n  >\n  <meta\n    property="og:image:secure_url"\n    content="https://www.decathlon.com/cdn/shop/collections/Collections-Herobanner-Camp-_-hike.jpg?v=1759928429"\n  >\n  <meta\n    property="og:image:width"\n    content="969"\n  >\n  <meta\n    property="og:image:height"\n    content="646"\n  ><meta\n  name="twitter:card"\n  content="summary_large_image"\n>\n<meta\n  name="twitter:title"\n  content="Hiking &amp; Backpacking Gear"\n>\n<meta\n  name="twitter:description"\n  content="Shop our selection of hiking and backpacking equipment designed by Decathlon. Enjoy free U.S. standard shipping on orders over $49! Free returns up to 90 days!"\n>\n\n<title>\n  Hiking &amp; Backpacking Gear\n &ndash; Decathlon</title>\n\n<link\n  rel="canonical"\n  href="https://www.decathlon.com/collections/camp-hike"\n>\n\n\n  <meta\n    name="description"\n    content="Shop our selection of hiking and backpacking equipment designed by Decathlon. Enjoy free U.S. standard shipping on orders over $49! Free returns up to 90 days!"\n  >\n\n<link href="//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.css?v=16727044177065489451775763283" as="style" rel="preload">\n<link href="//www.decathlon.com/cdn/shop/t/374/assets/base.css?v=110558660533795380521775763283" rel="stylesheet" type="text/css" media="all" />\n\n<link\n    rel="preload"\n    as="font"\n    href="//www.decathlon.com/cdn/fonts/inter/inter_n4.b2a3f24c19b4de56e8871f609e73ca7f6d2e2bb9.woff2"\n    type="font/woff2"\n    crossorigin\n    fetchpriority="low"\n  ><link\n    rel="preload"\n    as="font"\n    href="//www.decathlon.com/cdn/fonts/inter/inter_n5.d7101d5e168594dd06f56f290dd759fba5431d97.woff2"\n    type="font/woff2"\n    crossorigin\n    fetchpriority="low"\n  ><link\n    rel="preload"\n    as="font"\n    href="//www.decathlon.com/cdn/fonts/inter/inter_n7.02711e6b374660cfc7915d1afc1c204e633421e4.woff2"\n    type="font/woff2"\n    crossorigin\n    fetchpriority="low"\n  ><link\n    rel="preload"\n    as="font"\n    href="//www.decathlon.com/cdn/fonts/inter/inter_n7.02711e6b374660cfc7915d1afc1c204e633421e4.woff2"\n    type="font/woff2"\n    crossorigin\n    fetchpriority="low"\n  >\n\n\n<script type="importmap">\n  {\n    "imports": {\n      "@theme/overflow-list": "//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.js?v=46858356770684902511775763283",\n      "@theme/product-title": "//www.decathlon.com/cdn/shop/t/374/assets/product-title-truncation.js?v=81744426891537421781775763283",\n      "@theme/component": "//www.decathlon.com/cdn/shop/t/374/assets/component.js?v=184240237101443119871775763283",\n      "@theme/dialog": "//www.decathlon.com/cdn/shop/t/374/assets/dialog.js?v=150888536568694194021775763283",\n      "@theme/events": "//www.decathlon.com/cdn/shop/t/374/assets/events.js?v=1118589085892804011775763283",\n      "@theme/focus": "//www.decathlon.com/cdn/shop/t/374/assets/focus.js?v=60436577539430446401775763283",\n      "@theme/morph": "//www.decathlon.com/cdn/shop/t/374/assets/morph.js?v=104045809772310330131775763283",\n      "@theme/paginated-list": "//www.decathlon.com/cdn/shop/t/374/assets/paginated-list.js?v=95298315036233333871775763283",\n      "@theme/performance": "//www.decathlon.com/cdn/shop/t/374/assets/performance.js?v=171015751390534793081775763283",\n      "@theme/product-form": "//www.decathlon.com/cdn/shop/t/374/assets/product-form.js?v=142170751179338062901775763283",\n      "@theme/recently-viewed-products": "//www.decathlon.com/cdn/shop/t/374/assets/recently-viewed-products.js?v=94729125001750262651775763283",\n      "@theme/scrolling": "//www.decathlon.com/cdn/shop/t/374/assets/scrolling.js?v=162288454571026455011775763283",\n      "@theme/section-renderer": "//www.decathlon.com/cdn/shop/t/374/assets/section-renderer.js?v=123311117485513785771775763283",\n      "@theme/section-hydration": "//www.decathlon.com/cdn/shop/t/374/assets/section-hydration.js?v=108434990705342316311775763283",\n      "@theme/money-formatting": "//www.decathlon.com/cdn/shop/t/374/assets/money-formatting.js?v=182191346160333327151775763283",\n      "@theme/utilities": "//www.decathlon.com/cdn/shop/t/374/assets/utilities.js?v=28506172887375975941775763283",\n      "@theme/variant-picker": "//www.decathlon.com/cdn/shop/t/374/assets/variant-picker.js?v=24924540959574313291775763283",\n      "@theme/media-gallery": "//www.decathlon.com/cdn/shop/t/374/assets/media-gallery.js?v=14624021005636302161775763283",\n      "@theme/quick-add": "//www.decathlon.com/cdn/shop/t/374/assets/quick-add.js?v=114575661933533593881775763283",\n      "@theme/paginated-list-aspect-ratio": "//www.decathlon.com/cdn/shop/t/374/assets/paginated-list-aspect-ratio.js?v=25254270272143792451775763283",\n      "@theme/popover-polyfill": "//www.decathlon.com/cdn/shop/t/374/assets/popover-polyfill.js?v=119029313658895111201775763283",\n      "@theme/component-quantity-selector": "//www.decathlon.com/cdn/shop/t/374/assets/component-quantity-selector.js?v=67906657287482036641775763283",\n      "@theme/comparison-slider": "//www.decathlon.com/cdn/shop/t/374/assets/comparison-slider.js?v=106705562947035711941775763283",\n      "@theme/sticky-add-to-cart": "//www.decathlon.com/cdn/shop/t/374/assets/sticky-add-to-cart.js?v=48956925339276737091775763283",\n      "@theme/fly-to-cart": "//www.decathlon.com/cdn/shop/t/374/assets/fly-to-cart.js?v=48483246440248933081775763283"\n    }\n  }\n</script>\n\n<script\n  src="//www.decathlon.com/cdn/shop/t/374/assets/view-transitions.js?v=7106414069516106341775763283"\n  async\n  \n></script>\n\n<link\n  rel="modulepreload"\n  href="//www.decathlon.com/cdn/shop/t/374/assets/utilities.js?v=28506172887375975941775763283"\n  fetchpriority="low"\n>\n<link\n  rel="modulepreload"\n  href="//www.decathlon.com/cdn/shop/t/374/assets/component.js?v=184240237101443119871775763283"\n  fetchpriority="low"\n>\n<link\n  rel="modulepreload"\n  href="//www.decathlon.com/cdn/shop/t/374/assets/section-renderer.js?v=123311117485513785771775763283"\n  fetchpriority="low"\n>\n<link\n  rel="modulepreload"\n  href="//www.decathlon.com/cdn/shop/t/374/assets/section-hydration.js?v=108434990705342316311775763283"\n  fetchpriority="low"\n>\n<link\n  rel="modulepreload"\n  href="//www.decathlon.com/cdn/shop/t/374/assets/morph.js?v=104045809772310330131775763283"\n  fetchpriority="low"\n>\n\n\n  <link\n    rel="modulepreload"\n    href="//www.decathlon.com/cdn/shop/t/374/assets/paginated-list-aspect-ratio.js?v=25254270272143792451775763283"\n    fetchpriority="low"\n  >\n  <link\n    rel="modulepreload"\n    href="//www.decathlon.com/cdn/shop/t/374/assets/paginated-list.js?v=95298315036233333871775763283"\n    fetchpriority="low"\n  >\n\n  <link\n    rel="modulepreload"\n    href="//www.decathlon.com/cdn/shop/t/374/assets/product-title-truncation.js?v=81744426891537421781775763283"\n    fetchpriority="low"\n  >\n\n\n<link\n  rel="modulepreload"\n  href="//www.decathlon.com/cdn/shop/t/374/assets/focus.js?v=60436577539430446401775763283"\n  fetchpriority="low"\n>\n<link\n  rel="modulepreload"\n  href="//www.decathlon.com/cdn/shop/t/374/assets/recently-viewed-products.js?v=94729125001750262651775763283"\n  fetchpriority="low"\n>\n<link\n  rel="modulepreload"\n  href="//www.decathlon.com/cdn/shop/t/374/assets/scrolling.js?v=162288454571026455011775763283"\n  fetchpriority="low"\n>\n<link\n  rel="modulepreload"\n  href="//www.decathlon.com/cdn/shop/t/374/assets/events.js?v=1118589085892804011775763283"\n  fetchpriority="low"\n>\n<script\n  src="//www.decathlon.com/cdn/shop/t/374/assets/popover-polyfill.js?v=119029313658895111201775763283"\n  type="module"\n  fetchpriority="low"\n></script>\n<script\n  src="//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.js?v=46858356770684902511775763283"\n  type="module"\n  fetchpriority="low"\n></script>\n<script\n  src="//www.decathlon.com/cdn/shop/t/374/assets/quick-add.js?v=114575661933533593881775763283"\n  type="module"\n  fetchpriority="low"\n></script>\n\n  <script\n    src="//www.decathlon.com/cdn/shop/t/374/assets/cart-discount.js?v=107077853990124422021775763283"\n    type="module"\n    fetchpriority="low"\n  ></script>\n\n\n<script\n  src="//www.decathlon.com/cdn/shop/t/374/assets/dialog.js?v=150888536568694194021775763283"\n  type="module"\n  fetchpriority="low"\n></script>\n<script\n  src="//www.decathlon.com/cdn/shop/t/374/assets/variant-picker.js?v=24924540959574313291775763283"\n  type="module"\n  fetchpriority="low"\n></script>\n<script\n  src="//www.decathlon.com/cdn/shop/t/374/assets/product-card.js?v=28695665944407642501775763283"\n  type="module"\n  fetchpriority="low"\n></script>\n<script\n  src="//www.decathlon.com/cdn/shop/t/374/assets/product-form.js?v=142170751179338062901775763283"\n  type="module"\n  fetchpriority="low"\n></script>\n<script\n  src="//www.decathlon.com/cdn/shop/t/374/assets/fly-to-cart.js?v=48483246440248933081775763283"\n  type="module"\n  fetchpriority="low"\n></script>\n<script\n  src="//www.decathlon.com/cdn/shop/t/374/assets/accordion-custom.js?v=97588419883090

In [9]:
response.headers # Response headers (as a Python dictionary)

{'Date': 'Thu, 30 Apr 2026 09:55:11 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '96718', 'Connection': 'keep-alive', 'CF-RAY': '9f45ab5d9b4f79cf-LAX', 'etag': '"page_cache:13306287:CollectionDetailsController:1bf6b0acb3c2260988acfb71df1d925f"', 'content-encoding': 'br', 'link': '<https://cdn.shopify.com>; rel="preconnect", <https://cdn.shopify.com>; rel="preconnect"; crossorigin, <//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.css?v=16727044177065489451775763283>; as="style"; rel="preload", <//www.decathlon.com/cdn/shop/t/374/assets/base.css?v=110558660533795380521775763283>; as="style"; rel="preload", <//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Brand-SemiBold.woff2?v=4101535601310826581777060469>; as="font"; type="font/woff2"; crossorigin; rel="preload", <//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Display-SemiBold.woff2?v=100345316253960588891777060469>; as="font"; type="font/woff2"; crossorigin; rel="preload", <//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Text-Medium.woff2?v=52324173899180483681777060469>; as="font"; type="font/woff2"; crossorigin; rel="preload", <//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Text-SemiBold.woff2?v=2220433650020876521777060469>; as="font"; type="font/woff2"; crossorigin; rel="preload"', 'set-cookie': 'localization=US; path=/; expires=Fri, 30 Apr 2027 09:55:11 GMT, cart_currency=USD; path=/; expires=Thu, 14 May 2026 09:55:11 GMT, _shopify_y=5cd0a3af-f897-4a71-ae7f-30c55f45dd9e; domain=decathlon.com; path=/; expires=Fri, 30 Apr 2027 15:55:11 GMT; SameSite=Lax, _shopify_s=4e1e6b0c-0cba-4c8b-8774-b19d6f0e8dc4; domain=decathlon.com; path=/; expires=Thu, 30 Apr 2026 10:25:11 GMT; SameSite=Lax, _shopify_essential=:AZ3d0FayAAEAJHGjZ4V3Al95K3SvhfSZgXK5pFkywiEZi8RNBCFeSYBvsi9wf1wXIJLXpe59j0jrflGC-AwGTCJle8Kxzjd_wWJ1hlbAOLztucFXztCABKk4fvkt3ZK720Lw3LV8cE__AkxbBVTN9WLziKHY97kpMHzeUztCDBK43jKKxjAx0yrb6Z2CHFyTljBlVkz7gT3hFUBk-HTLRaUyy7SCLHF5hViW87vDdIluuBOIAfTiSF8LNoccxepF-XBpzfP3Dw8eqR-B7Bn7hWsxEH0huXvJbVVdvPykk3SQ-OrN_M642K8dKDDh1sgaK5k62rjGLU9icTV4UbKtLY7NIv9hdlj-L3uPkhc37Nq99pYkX4Shj82qgWPRO32xG7MDPLZmTjfQquPEAnOfEKDBadrggY6U6YMzpNWelwdXlxowK7lteF2h:; Max-Age=31536000; Path=/; HttpOnly; Secure; Priority=High; SameSite=None, _shopify_analytics=:AZ3d0FbRAAEA81UJp1gvavDPb-hxl8Rhu1scJ0KO6wHjhKt_G11v-PphepY7XwTUe0D99b5Zi7E_LEWeSekuv3Kn_ANHPqWoloVVSiyUldcy902OhZ5TtdFfbzf1QxqeuVOadN7fwMuPcMe1dNpWTd8HATEbxmb4LTNiWmdBmA:; Max-Age=31536000; Path=/; HttpOnly; Secure; Priority=High; SameSite=None, _shopify_marketing=:AZ3d0FbRAAEAY7MygJ-Z6hH-NW_ki5XE9k2032RuXargFfuOzUFHarBd6bRxzlywySlLTlp1mFG4sMVwjIK5g9f4YYuTQQiLvCIef_6JTuUyumBHxydc0rN5gEh0NN96uw:; Max-Age=31536000; Path=/; HttpOnly; Secure; Priority=High; SameSite=None', 'shopify-complexity-score': '37', 'content-security-policy': 'block-all-mixed-content; frame-ancestors *; upgrade-insecure-requests;', 'strict-transport-security': 'max-age=7889238', 'vary': 'Accept, accept-encoding', 'Alt-Svc': 'h3=":443"; ma=86400', 'content-language': 'en-US', 'powered-by': 'Shopify', 'server-timing': 'processing;dur=42, db;dur=19, asn;desc="396982", edge;desc="LAX", country;desc="US", theme;desc="139295424574", pageType;desc="collection", servedBy;desc="thxd", requestID;desc="3a7f8eff-c758-4b7b-beac-45d009c70406-1777542911", _y;desc="5cd0a3af-f897-4a71-ae7f-30c55f45dd9e", _s;desc="4e1e6b0c-0cba-4c8b-8774-b19d6f0e8dc4", _cmp;desc="3.AMPS_USUT_f_f_C2bnKi1aQ2qZmFQFRwRqPg", compressionLevel;desc="5", cfRequestDuration;dur=107.000113', 'x-dc': 'gcp-us-west1,gcp-us-west1,gcp-us-west1', 'x-request-id': '3a7f8eff-c758-4b7b-beac-45d009c70406-1777542911', 'cf-cache-status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=1CHzvlsadI%2Bxn481jGDQZSHgOQ2k4arSWAbk%2F0UknHkUx8phKSeCvhKYFzhkHrI397ENLNaMZ%2FpsGZTtKA8yhxPGnwrUGYUfQ5xdP4v6arKXJTkSlyAJdsSBRuDCbTlVvh55"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-Download-Options': 'noopen', 'Server': 'cloudflare'}

In [10]:
print(response.headers['Content-Type'])

text/html; charset=utf-8

When interacting with APIs, we typically receive data in JSON format. However, web scraping provides us with HTML, which can be challenging to navigate. Fortunately, Beautiful Soup simplifies this process, making our work more manageable!

### Parsing HTML with Beautiful Soup

To parse the HTML, we'll employ the renowned Python library, [Beautiful Soup 4](https://www.crummy.com/software/BeautifulSoup/bs4/doc/). For a deeper understanding of its functionalities, explore the [official documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/).

In [11]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.content, "html.parser")

The code above parses the HTML (stored in `response.content`) into a special object called `soup` that the Beautiful Soup library understands. In other words, Beautiful Soup is **reading the HTML and making sense of its structure.**

In [12]:
type(soup)

bs4.BeautifulSoup

In [13]:
print(soup.prettify())  # This formats the HTML in a readable way

<!DOCTYPE html>
<html lang="en">
 <head>
  <link href="//www.decathlon.com/cdn/shop/files/favicon-large.png?crop=center&amp;height=32&amp;v=1749504383&amp;width=32" rel="icon" type="image/png"/>
  <!-- Preload Decathon fonts ================================================== -->
  <link as="font" crossorigin="anonymous" href="//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Brand-SemiBold.woff2?v=4101535601310826581777060469" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="anonymous" href="//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Display-SemiBold.woff2?v=100345316253960588891777060469" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="anonymous" href="//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Text-Medium.woff2?v=52324173899180483681777060469" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="anonymous" href="//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Text-SemiBold.woff2?v=2220433650020876521777060469" rel="preload" type="font/woff2"/>
  <style data-shopify="">
   @font-face {
      font-family: 'Decathlon Display';
      src: url(//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Display-SemiBold.woff2?v=100345316253960588891777060469)format('woff2');
      font-weight: 700;
      font-style: normal;
      font-display: swap;
    }
    @font-face {
      font-family: 'Decathlon Brand';
      src: url(//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Brand-SemiBold.woff2?v=4101535601310826581777060469)format('woff2');
      font-weight: 700;
      font-style: normal;
      font-display: swap;
    }
    @font-face {
      font-family: 'Decathlon Text';
      src: url(//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Text-SemiBold.woff2?v=2220433650020876521777060469)format('woff2');
      font-weight: 700;
      font-style: normal;
      font-display: swap;
    }
    @font-face {
      font-family: 'Decathlon Text';
      src: url(//www.decathlon.com/cdn/shop/t/374/assets/Decathlon-Text-Medium.woff2?v=52324173899180483681777060469)format('woff2');
      font-weight: 500;
      font-style: normal;
      font-display: swap;
    }

    .font-sub-l {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 600;
    font-size: 20px;
    line-height: 150%;
    letter-spacing: 0;
    max-width: 720px;
  }
  .font-sub-m {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 600;
    font-size: 16px;
    line-height: 150%;
    letter-spacing: 0;
    max-width: 640px;
  }
  .font-body-l {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 500;
    font-size: 20px;
    line-height: 150%;
    letter-spacing: 0;
    max-width: 720px;
  }
  .font-body-m {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 500;
    font-size: 16px;
    line-height: 150%;
    letter-spacing: 0;
    max-width: 640px;
  }
  .font-body-s {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 500;
    font-size: 14px;
    line-height: 143%;
    letter-spacing: 0;
    max-width: 480px;
  }
  .font-cap {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 500;
    font-size: 12px;
    line-height: 133%;
    letter-spacing: 0;
  }
  .font-link-l {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 500;
    font-size: 20px;
    line-height: 150%;
    letter-spacing: 0;
  }
  .font-link-m {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 500;
    font-size: 16px;
    line-height: 150%;
    letter-spacing: 0;
  }
  .font-link-s {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 500;
    font-size: 14px;
    line-height: 143%;
    letter-spacing: 0;
  }
  .font-link-cap {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 500;
    font-size: 12px;
    line-height: 133%;
    letter-spacing: 0;
  }
  .font-btn-m {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 500;
    font-size: 14px;
    line-height: 170%;
    letter-spacing: 0;
  }
  .font-btn-s {
    font-family: 'Decathlon Text', sans-serif;
    font-weight: 500;
    font-size: 12px;
    line-height: 130%;
    letter-spacing: 0;
  }
  .font-brand-xl {
    font-family: 'Decathlon Brand', sans-serif;
    font-weight: 600;
    font-size: 48px;
    line-height: 108%;
    letter-spacing: 0;
  }
  .font-title-xl {
    font-family: 'Decathlon Display', sans-serif;
    font-weight: 600;
    font-size: 48px;
    line-height: 108%;
    letter-spacing: 0;
  }
  .font-title-l {
    font-family: 'Decathlon Display', sans-serif;
    font-weight: 600;
    font-size: 36px;
    line-height: 111%;
    letter-spacing: 0;
  }
  .font-title-m {
    font-family: 'Decathlon Display', sans-serif;
    font-weight: 600;
    font-size: 26px;
    line-height: 123%;
    letter-spacing: 0;
  }
  .font-title-s {
    font-family: 'Decathlon Display', sans-serif;
    font-weight: 600;
    font-size: 22px;
    line-height: 118%;
    letter-spacing: 0;
  }
  .font-overline {
    font-family: 'Decathlon Display', sans-serif;
    font-weight: 600;
    font-size: 14px;
    line-height: 117%;
    letter-spacing: 0;
  }
  /* Large Screens */
  @media screen and (min-width: 390px) {
    .font-brand-xl {
      font-family: 'Decathlon Brand', sans-serif;
      font-weight: 600;
      font-size: 56px;
      line-height: 107%;
      letter-spacing: 0;
    }
    .font-title-xl {
      font-family: 'Decathlon Display', sans-serif;
      font-weight: 600;
      font-size: 56px;
      line-height: 107%;
      letter-spacing: 0;
    }
    .font-title-l {
      font-family: 'Decathlon Display', sans-serif;
      font-weight: 600;
      font-size: 40px;
      line-height: 110%;
      letter-spacing: 0;
    }
    .font-title-m {
      font-family: 'Decathlon Display', sans-serif;
      font-weight: 600;
      font-size: 26px;
      line-height: 123%;
      letter-spacing: 0;
    }
    .font-title-s {
      font-family: 'Decathlon Display', sans-serif;
      font-weight: 600;
      font-size: 22px;
      line-height: 118%;
      letter-spacing: 0;
    }
    .font-overline {
      font-family: 'Decathlon Display', sans-serif;
      font-weight: 600;
      font-size: 16px;
      line-height: 117%;
      letter-spacing: 0;
    }
  }
  /* Large Screens */
  @media screen and (min-width: 1024px) {
    .font-brand-xl {
      font-family: 'Decathlon Brand', sans-serif;
      font-weight: 600;
      font-size: 74px;
      line-height: 108%;
      letter-spacing: 0;
    }
    .font-title-xl {
      font-family: 'Decathlon Display', sans-serif;
      font-weight: 600;
      font-size: 74px;
      line-height: 108%;
      letter-spacing: 0;
    }
    .font-title-l {
      font-family: 'Decathlon Display', sans-serif;
      font-weight: 600;
      font-size: 48px;
      line-height: 117%;
      letter-spacing: 0;
    }
    .font-title-m {
      font-family: 'Decathlon Display', sans-serif;
      font-weight: 600;
      font-size: 32px;
      line-height: 119%;
      letter-spacing: 0;
    }
    .font-title-s {
      font-family: 'Decathlon Display', sans-serif;
      font-weight: 600;
      font-size: 22px;
      line-height: 118%;
      letter-spacing: 0;
    }
    .font-overline {
      font-family: 'Decathlon Display', sans-serif;
      font-weight: 600;
      font-size: 16px;
      line-height: 129%;
      letter-spacing: 0;
    }
  }

  /*================== Decathlon Buttons ==================*/
  /* Base */
  .btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    padding: 20px 32px; /* default size */
    border: 0;
    cursor: pointer;
    transition: background-color 0.15s ease, color 0.15s ease;
  }

  /* Shape modifiers */
  .btn--sqaure {
    padding: 20px 32px;
  }
  .btn--pill {
    padding: 12px 16px;
    border-radius: 100px;
  }

  /* Color Variants */
  .btn--brand {
    background: var(--color-brand);
    color: var(--color-white);
  }
  .btn--white {
    background: var(--color-white);
    color: var(--color-brand);
    border: 1px solid var(--color-brand);
  }
  .btn--catchy {
    background: var(--color-catchy);
    color: var(--color-black);
  }

  /* Hover & active */
  .btn--brand:hover {
    background: var(--color-brand-hover);
  }
  .btn--brand:active {
    background: var(--color-brand-active);
  }

  .btn--white:hover {
    background: var(--color-white-hover);
  }
  .btn--white:active {
    background: var(--color-white-active);
  }

  .btn--catchy:hover {
    background: var(--color-catchy-hover);
  }
  .btn--catchy:active {
    background: var(--color-catchy-active);
  }

  /* Disabled */
  .btn[disabled],
  .btn:disabled {
    background: var(--color-gray-10);
    color: var(--color-gray-40);
    border-color: var(--color-gray-20);
    cursor: not-allowed;
  }

  /* Focus-visible (keyboard) */
  .btn:focus-visible {
    outline: 2px solid var(--color-brand);
    outline-offset: 2px;
  }
  </style>
  <!-- Microsft Calrity Script -->
  <script async="" crossorigin="" fetchpriority="high" src="/cdn/shopifycloud/importmap-polyfill/es-modules-shim.2.4.0.js">
  </script>
  <script type="text/javascript">
   (function (c, l, a, r, i, t, y) {
        c[a] =
          c[a] ||
          function () {
            (c[a].q = c[a].q || []).push(arguments);
          };
        t = l.createElement(r);
        t.async = 1;
        t.src = 'https://www.clarity.ms/tag/' + i;
        y = l.getElementsByTagName(r)[0];
        y.parentNode.insertBefore(t, y);
      })(window, document, 'clarity', 'script', 's55kwp0oug');
  </script>
  <meta charset="utf-8"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width,initial-scale=1" name="viewport"/>
  <meta content="same-origin" name="view-transition"/>
  <meta content="" name="theme-color"/>
  <meta content="Decathlon" property="og:site_name"/>
  <meta content="https://www.decathlon.com/collections/camp-hike" property="og:url"/>
  <meta content="Hiking &amp; Backpacking Gear" property="og:title"/>
  <meta content="website" property="og:type"/>
  <meta content="Shop our selection of hiking and backpacking equipment designed by Decathlon. Enjoy free U.S. standard shipping on orders over $49! Free returns up to 90 days!" property="og:description"/>
  <meta content="http://www.decathlon.com/cdn/shop/collections/Collections-Herobanner-Camp-_-hike.jpg?v=1759928429" property="og:image"/>
  <meta content="https://www.decathlon.com/cdn/shop/collections/Collections-Herobanner-Camp-_-hike.jpg?v=1759928429" property="og:image:secure_url"/>
  <meta content="969" property="og:image:width"/>
  <meta content="646" property="og:image:height"/>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="Hiking &amp; Backpacking Gear" name="twitter:title"/>
  <meta content="Shop our selection of hiking and backpacking equipment designed by Decathlon. Enjoy free U.S. standard shipping on orders over $49! Free returns up to 90 days!" name="twitter:description"/>
  <title>
   Hiking &amp; Backpacking Gear
 – Decathlon
  </title>
  <link href="https://www.decathlon.com/collections/camp-hike" rel="canonical"/>
  <meta content="Shop our selection of hiking and backpacking equipment designed by Decathlon. Enjoy free U.S. standard shipping on orders over $49! Free returns up to 90 days!" name="description"/>
  <link as="style" href="//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.css?v=16727044177065489451775763283" rel="preload"/>
  <link href="//www.decathlon.com/cdn/shop/t/374/assets/base.css?v=110558660533795380521775763283" media="all" rel="stylesheet" type="text/css">
   <link as="font" crossorigin="" fetchpriority="low" href="//www.decathlon.com/cdn/fonts/inter/inter_n4.b2a3f24c19b4de56e8871f609e73ca7f6d2e2bb9.woff2" rel="preload" type="font/woff2"/>
   <link as="font" crossorigin="" fetchpriority="low" href="//www.decathlon.com/cdn/fonts/inter/inter_n5.d7101d5e168594dd06f56f290dd759fba5431d97.woff2" rel="preload" type="font/woff2"/>
   <link as="font" crossorigin="" fetchpriority="low" href="//www.decathlon.com/cdn/fonts/inter/inter_n7.02711e6b374660cfc7915d1afc1c204e633421e4.woff2" rel="preload" type="font/woff2"/>
   <link as="font" crossorigin="" fetchpriority="low" href="//www.decathlon.com/cdn/fonts/inter/inter_n7.02711e6b374660cfc7915d1afc1c204e633421e4.woff2" rel="preload" type="font/woff2"/>
   <script type="importmap">
    {
    "imports": {
      "@theme/overflow-list": "//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.js?v=46858356770684902511775763283",
      "@theme/product-title": "//www.decathlon.com/cdn/shop/t/374/assets/product-title-truncation.js?v=81744426891537421781775763283",
      "@theme/component": "//www.decathlon.com/cdn/shop/t/374/assets/component.js?v=184240237101443119871775763283",
      "@theme/dialog": "//www.decathlon.com/cdn/shop/t/374/assets/dialog.js?v=150888536568694194021775763283",
      "@theme/events": "//www.decathlon.com/cdn/shop/t/374/assets/events.js?v=1118589085892804011775763283",
      "@theme/focus": "//www.decathlon.com/cdn/shop/t/374/assets/focus.js?v=60436577539430446401775763283",
      "@theme/morph": "//www.decathlon.com/cdn/shop/t/374/assets/morph.js?v=104045809772310330131775763283",
      "@theme/paginated-list": "//www.decathlon.com/cdn/shop/t/374/assets/paginated-list.js?v=95298315036233333871775763283",
      "@theme/performance": "//www.decathlon.com/cdn/shop/t/374/assets/performance.js?v=171015751390534793081775763283",
      "@theme/product-form": "//www.decathlon.com/cdn/shop/t/374/assets/product-form.js?v=142170751179338062901775763283",
      "@theme/recently-viewed-products": "//www.decathlon.com/cdn/shop/t/374/assets/recently-viewed-products.js?v=94729125001750262651775763283",
      "@theme/scrolling": "//www.decathlon.com/cdn/shop/t/374/assets/scrolling.js?v=162288454571026455011775763283",
      "@theme/section-renderer": "//www.decathlon.com/cdn/shop/t/374/assets/section-renderer.js?v=123311117485513785771775763283",
      "@theme/section-hydration": "//www.decathlon.com/cdn/shop/t/374/assets/section-hydration.js?v=108434990705342316311775763283",
      "@theme/money-formatting": "//www.decathlon.com/cdn/shop/t/374/assets/money-formatting.js?v=182191346160333327151775763283",
      "@theme/utilities": "//www.decathlon.com/cdn/shop/t/374/assets/utilities.js?v=28506172887375975941775763283",
      "@theme/variant-picker": "//www.decathlon.com/cdn/shop/t/374/assets/variant-picker.js?v=24924540959574313291775763283",
      "@theme/media-gallery": "//www.decathlon.com/cdn/shop/t/374/assets/media-gallery.js?v=14624021005636302161775763283",
      "@theme/quick-add": "//www.decathlon.com/cdn/shop/t/374/assets/quick-add.js?v=114575661933533593881775763283",
      "@theme/paginated-list-aspect-ratio": "//www.decathlon.com/cdn/shop/t/374/assets/paginated-list-aspect-ratio.js?v=25254270272143792451775763283",
      "@theme/popover-polyfill": "//www.decathlon.com/cdn/shop/t/374/assets/popover-polyfill.js?v=119029313658895111201775763283",
      "@theme/component-quantity-selector": "//www.decathlon.com/cdn/shop/t/374/assets/component-quantity-selector.js?v=67906657287482036641775763283",
      "@theme/comparison-slider": "//www.decathlon.com/cdn/shop/t/374/assets/comparison-slider.js?v=106705562947035711941775763283",
      "@theme/sticky-add-to-cart": "//www.decathlon.com/cdn/shop/t/374/assets/sticky-add-to-cart.js?v=48956925339276737091775763283",
      "@theme/fly-to-cart": "//www.decathlon.com/cdn/shop/t/374/assets/fly-to-cart.js?v=48483246440248933081775763283"
    }
  }
   </script>
   <script async="" src="//www.decathlon.com/cdn/shop/t/374/assets/view-transitions.js?v=7106414069516106341775763283">
   </script>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/utilities.js?v=28506172887375975941775763283" rel="modulepreload"/>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/component.js?v=184240237101443119871775763283" rel="modulepreload"/>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/section-renderer.js?v=123311117485513785771775763283" rel="modulepreload"/>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/section-hydration.js?v=108434990705342316311775763283" rel="modulepreload"/>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/morph.js?v=104045809772310330131775763283" rel="modulepreload"/>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/paginated-list-aspect-ratio.js?v=25254270272143792451775763283" rel="modulepreload"/>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/paginated-list.js?v=95298315036233333871775763283" rel="modulepreload"/>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/product-title-truncation.js?v=81744426891537421781775763283" rel="modulepreload"/>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/focus.js?v=60436577539430446401775763283" rel="modulepreload"/>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/recently-viewed-products.js?v=94729125001750262651775763283" rel="modulepreload"/>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/scrolling.js?v=162288454571026455011775763283" rel="modulepreload"/>
   <link fetchpriority="low" href="//www.decathlon.com/cdn/shop/t/374/assets/events.js?v=1118589085892804011775763283" rel="modulepreload"/>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/popover-polyfill.js?v=119029313658895111201775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.js?v=46858356770684902511775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/quick-add.js?v=114575661933533593881775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/cart-discount.js?v=107077853990124422021775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/dialog.js?v=150888536568694194021775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/variant-picker.js?v=24924540959574313291775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/product-card.js?v=28695665944407642501775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/product-form.js?v=142170751179338062901775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/fly-to-cart.js?v=48483246440248933081775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/accordion-custom.js?v=97588419883090888471775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/media.js?v=37825095869491791421775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/product-price.js?v=83480980452100801711775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/product-sku.js?v=121804655373531320511775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/product-title-truncation.js?v=81744426891537421781775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/product-inventory.js?v=81520546963552472391775763283" type="module">
   </script>
   <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/show-more.js?v=94563802205717136101775763283" type="module">

With the parsed HTML, we can now extract specific elements.

#### Extracting Data

`find` and `findAll` (or its equivalent `find_all`) are methods used to search the soup tree for tags that match a certain criterion.

1. **find**:
    - Returns only the **first** tag that matches a given set of criteria.
    - Useful when you know there's only one tag of interest or you only want the first occurrence.
    - Example: If you have multiple `<p>` tags on a page and you use `soup.find('p')`, you'll get only the first `<p>` tag.

2. **findAll (or find_all)**:
    - Returns a **list** of tags that match the given criteria.
    - Useful when you want to capture all occurrences of a particular tag or set of tags.
    - Example: Using `soup.find_all('p')` will give you a list containing all `<p>` tags on the page.

Here's a simple illustration:

```html
<html>
    <body>
        <p>First paragraph.</p>
        <p>Second paragraph.</p>
        <div>Some div.</div>
    </body>
</html>
```

Using `find('p')` would return the "First paragraph." while `find_all('p')` would return a list containing both "First paragraph." and "Second paragraph.".

Let's look at different ways of extracting data.

##### **By Tag**

Let's start with a popular tag: `title`.

In [14]:
soup.find("title") # Find the first <title> tag on the page

<title>
  Hiking &amp; Backpacking Gear
 – Decathlon</title>

In [15]:
soup.find_all("title") # Find the all <title> tags on the page

[<title>
   Hiking &amp; Backpacking Gear
  – Decathlon</title>]

##### **By Class**

To search for HTML elements by class in a webpage using BeautifulSoup, you can also use the `find` and `find_all` methods.

1. **Using `find` method to get the first matching element**:
   
   ```python
   result = soup.find(class_='your-class-name')
   ```

2. **Using `find_all` method to get a list of all matching elements**:

   ```python
   results = soup.find_all(class_='your-class-name')
   ```
   
Note that we are using the `class_` parameter because `class` is a reserved keyword in Python.

Let's dive into our target URL and explore its structure. Our objective is to craft a dataframe populated with bicycle names and their corresponding prices.

To pinpoint the exact tags housing this information, follow these steps:
1. Navigate to the website in your browser.
2. Locate a bicycle name, right-click on it, and choose 'Inspect'. This action will direct you to the element within the site's HTML. Identify the tags so we can extract our desired data.
3. Repeat the same process for the price.

Note: the bicycle names and prices will change depending on the newest bikes in the shop.

Let's filter all elements which `class` is `product-grid product-grid--template--18434715222078__main product-grid--grid`.

In [19]:
soup.find_all(class_="product-grid product-grid--template--18434715222078__main product-grid--grid")#"product__info-container product__column-sticky")

[<ul class="product-grid product-grid--template--18434715222078__main product-grid--grid" data-last-page="13" data-product-card-size="large" data-testid="product-grid" product-grid-view="default" ref="grid" role="list" style="--mobile-columns: 2;">
 <script>
             (() => {
               const grid = document.querySelector('.product-grid');
               if (!grid) return;

               const storedLayoutMobile = sessionStorage.getItem('product-grid-view-mobile') || 'default';
               const storedLayoutDesktop = sessionStorage.getItem('product-grid-view-desktop') || 'default';

               // No need to read the window width if no custom layouts were saved.
               if (storedLayoutMobile === 'default' && storedLayoutDesktop === 'default') return;

               const storedLayout = window.innerWidth >= 750 ? storedLayoutDesktop : storedLayoutMobile;
               if (storedLayout === 'default') return;

               grid.setAttribute('product-grid-view', storedLayout);

               const options = document.querySelectorAll(
                 'input[type="radio"][name="grid"], input[type="radio"][name="grid-mobile"]'
               );
               for (const option of options) {
                 option.checked = option.value === storedLayout;
               }
             })();
           </script>
 <li class="product-grid__item product-grid__item--0" data-page="1" data-product-id="4417342308414" id="template--18434715222078__main-4417342308414" ref="cards[]">
 <style data-shopify="">
 </style>
 <product-card class="product-card size-style" data-product-id="4417342308414" id="product-card-AZk1wN2hFVFQ2ZmJCc__product-card" style="--size-style-width: ;--size-style-height: ;">
 <a class="product-card__link" href="/products/simond-mt100-hooded-down-puffer-jacket-167571?variant=41320423063614" id="36cefc935f0b0a254f317ab98f544407" ref="productCardLink">
 <span class="visually-hidden">
       Simond Men's MT100 Hooded Down Puffer Jacket
     </span>
 </a>
 <div class="product-card__content layout-panel-flex layout-panel-flex--column product-grid__card spacing-style border-style gap-style" style="
       --border-width: 1px; --border-style: none; --border-color:
 rgb(var(--color-border-rgb) / 1.0); --border-radius:
 0px;

       --flex-direction: column; --flex-wrap: nowrap; --flex-wrap-mobile: wrap;



 --horizontal-alignment: ; --vertical-alignment: ;
 --vertical-alignment-mobile: ;

       --padding-block-start: 0px;--padding-block-end: 0px;--padding-inline-start: 0px;--padding-inline-end: 0px;
       --product-card-gap: 4px;
       --quick-add-display: none;
       --quick-add-mobile-display: none;
       --quick-add-mobile-opacity: 0;




     ">
 <div class="card-gallery card-gallery-AODAvcVh6b3p1OG5zN__card-gallery spacing-style border-style" data-image-ratio="square" data-product-id="4417342308414" on:pointerenter="/previewImage" on:pointerleave="/resetImage" ref="cardGallery" style="
     --border-width: 1px; --border-style: none; --border-color:
 rgb(var(--color-border-rgb) / 1.0); --border-radius:
 0px;

     --padding-block-start: 0px;--padding-block-end: 0px;--padding-inline-start: 0px;--padding-inline-end: 0px;
     --gallery-aspect-ratio: 1;
   ">
 <a aria-label="Simond Men's MT100 Hooded Down Puffer Jacket" class="contents" href="/products/simond-mt100-hooded-down-puffer-jacket-167571?variant=41320423063614" ref="cardGalleryLink">
 <slideshow-component data-generic-media-size="37" disabled="true" infinite="" initial-slide="0" ref="slideshow" style="--slideshow-timeline: --slide-0, --slide-1, --slide-2, --slide-3, --slide-4, --slide-5, --slide-6, --slide-7, --slide-8, --slide-9, --slide-10, --slide-11, --slide-12, --slide-13, --slide-14, --slide-15, --slide-16, --slide-17, --slide-18, --slide-19, --slide-20, --slide-21, --slide-22, --slide-23, --slide-24, --slide-25, --slide-26, --slide-27, --slide-28, --slide-29, --slide-30, --slide-31, --slide-32, --slide-33, --slide-34, --slide-35, --slide-36, --slide-37, --slide-38, --slide-39, --slide-40;--slide-min-height: auto;--slide-min-height-desktop: auto;">
 <slideshow-container ref="slideshowContainer">
 <slideshow-arrows position="center"><button aria-label="Previous slide" class="slideshow-control slideshow-control--previous slideshow-control--style-arrow button button-unstyled button-unstyled--transparent flip-x" on:click="/previous" ref="previous">
 <span class="svg-wrapper icon-arrow"><svg aria-hidden="true" fill="none" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M4.25 10h11.5m0 0-4-4m4 4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)" vector-effect="non-scaling-stroke"></path></svg>
 </span>
 </button>
 <button aria-label="Next slide" class="slideshow-control slideshow-control--next slideshow-control--style-arrow button button-unstyled button-unstyled--transparent" on:click="/next" ref="next">
 <span class="svg-wrapper icon-arrow"><svg aria-hidden="true" fill="none" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M4.25 10h11.5m0 0-4-4m4 4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)" vector-effect="non-scaling-stroke"></path></svg>
 </span>
 </button>
 </slideshow-arrows>
 <slideshow-slides ref="scroller" tabindex="-1">
 <slideshow-slide aria-hidden="false" class="product-media-container media-fit product-media-container--image" ref="slides[]" slide-id="24955728592958" style="--slideshow-timeline: --slide-0; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
 <div class="product-media" data-media-id="24955728592958" style="--ratio: 1.0">
 <img alt="{*asphalt-blue-8858286*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840" fetchpriority="auto" height="3840" loading="eager" sizes="(min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
 </div>
 </slideshow-slide>
 <slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" ref="slides[]" slide-id="24955730657342" style="--slideshow-timeline: --slide-1; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;">
 <div class="product-media" data-media-id="24955730657342" style="--ratio: 1.0">
 <img alt="{*asphalt-blue-8858286*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
 </div>
 </slideshow-slide>
 <slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="26172575580222" style="--slideshow-timeline: --slide-13; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
 <div class="product-media" data-media-id="26172575580222" style="--ratio: 1.0">
 <img alt="{*smoked-black-8858287*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
 </div>
 </slideshow-slide>
 <slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="24955734655038" style="--slideshow-timeline: --slide-20; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
 <div class="product-media" data-media-id="24955734655038" style="--ratio: 1.0">
 <img alt="{*olive-green-8595408*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
 </div>
 </slideshow-slide>
 <slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="26173860479038" style="--slideshow-timeline: --slide-33; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
 <div class="product-media" data-media-id="26173860479038" style="--ratio: 1.0">
 <img alt="Simond Men's MT100 Hooded Down Puffer Jacket" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
 </div>
 </slideshow-slide>
 </slideshow-slides>
 </slideshow-container>
 </slideshow-component>
 </a>
 <div class="product-badges product-badges--top-right" style="
         --badge-border-radius: 100px;
         --badge-font-family: var(--font-body--family); --badge-font-weight: var(--font-body--weight); --badge-text-transform: none;
       "></div>
 </div>
 <div class="product-grid-view-zoom-out--details">
 <h3 class="h4">Simond Men's MT100 Hooded Down Puffer Jacket</h3>
 </div>
 <product-swatches data-product-id="4417342308414" data-product-url="/products/simond-mt100-hooded-down-puffer-jacket-167571" style="
       --overflow-list-alignment: flex-start;
       --overflow-list-alignment-mobile: flex-start;
       --product-swatches-alignment: start;
       --product-swatches-alignment-mobile: start;
       --product-swatches-padding-block-start: 0px;
       --product-swatches-padding-block-end: 0px;
       --product-swatches-padding-inline-start: 0px;
       --product-swatches-padding-inline-end: 0px;
     ">
 <swatches-variant-picker-component data-product-id="4417342308414" data-product-url="/products/simond-mt100-hooded-down-puffer-jacket-167571" ref="swatchesVariantPicker">
 <form>
 <fieldset class="variant-option variant-option--buttons variant-option--swatches">
 <overflow-list ref="overflowList">
 <template shadowrootmode="open">
 <link href="//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.css?v=16727044177065489451775763283" media="all" rel="stylesheet" type="text/css">
 <ul part="list">
 <slot></slot>
 <slot hidden="" name="more" part="more">
 <li part="more">
 <button class="button" tabindex="0" type="button">
             More
           </button>
 </li>
 </slot>
 <li hidden="" part="placeholder"></li>
 </ul>
 <div part="overflow">
 <ul part="overflow-list">
 <slot name="overflow"></slot>
 </ul>
 </div>
 </link></template>
 <li class="variant-option__swatch">
 <label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="24955728592958" on:pointerenter="product-card/previewVariant/24955728592958" on:pointerleave="product-card/resetVariant">
 <input aria-label="Asphalt Blue" data-connected-product-url="" data-first-available-or-first-variant-id="41320423063614" data-input-id="1-0" data-option-available="true" data-option-media-id="24955728592958" data-option-value-id="2344181727294" data-variant-id="41320423063614" name="Color-4417342308414-swatch" type="radio" value="Asphalt Blue"/>
 <span class="swatch swatch--variant-image" style="
     --swatch-background: url(//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=100);

   ">
 </span>
 </label>
 </li>
 <li class="variant-option__swatch">
 <label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="24955734655038" on:pointerenter="product-card/previewVariant/24955734655038" on:pointerleave="product-card/resetVariant">
 <input aria-label="Olive Green" data-connected-product-url="" data-first-available-or-first-variant-id="32494250295358" data-input-id="1-1" data-option-available="true" data-option-media-id="24955734655038" data-option-value-id="1454888255550" data-variant-id="32494250295358" name="Color-4417342308414-swatch" type="radio" value="Olive Green"/>
 <span class="swatch swatch--variant-image" style="
     --swatch-background: url(//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=100);

   ">
 </span>
 </label>
 </li>
 <li class="variant-option__swatch">
 <label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="26173860479038" on:pointerenter="product-card/previewVariant/26173860479038" on:pointerleave="product-card/resetVariant">
 <input aria-label="Dark Sepia" data-connected-product-url="" data-first-available-or-first-variant-id="41912831344702" data-input-id="1-2" data-option-available="true" data-option-media-id="26173860479038" data-option-value-id="2875192705086" data-variant-id="41912831344702" name="Color-4417342308414-swatch" type="radio" value="Dark Sepia"/>
 <span class="swatch swatch--variant-image" style="
     --swatch-background: url(//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=100);

   ">
 </span>
 </label>
 </li>
 <li class="variant-option__swatch">
 <label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="26172575580222" on:pointerenter="product-card/previewVariant/26172575580222" on:pointerleave="product-card/resetVariant">
 <input aria-label="Smoked Black" data-connected-product-url="" data-first-available-or-first-variant-id="41912831148094" data-input-id="1-3" data-option-available="true" data-option-media-id="26172575580222" data-option-value-id="2875192672318" data-variant-id="41912831148094" name="Color-4417342308414-swatch" type="radio" value="Smoked Black"/>

In this case, the results of `class` `de-ProductTile-title` are all inside `h4` tags and we actually got the information we wanted. But what if the `class` `de-ProductTile-title` was inside different `tags` and we only want the results of the `tag h4`?

##### **By Tag and Class**

BeautifulSoup allows filtering results using combinations, such as filtering by tag and class.

```python
tags = soup.find_all(name=tag_name, class_=class_name)
```

We can use a for loop to iterate over the results and do whatever we need to do.

Analyzing the website using the Chrome Inspector, we can see that all the products from the provided HTML content can be found in the tag "product-card" that belongs to the classes "product-card"m and  "size-style"

1. Use the `find_all` or `findAll` method to locate the `<product-card>` tags with the specific class (`product-card size-style` in this case).
2. Extract the text from the found tag.

In [40]:
# Find all <h4> tags with class "de-ProductTile-title"
items_tags = soup.find_all('product-card', class_="product-card size-style")

# How manu products we can find in this website (not taking into account the
# pagination)
len(items_tags)

24

In [41]:
# find_all returns a list
items_tags[0]

<product-card class="product-card size-style" data-product-id="4417342308414" id="product-card-AZk1wN2hFVFQ2ZmJCc__product-card" style="--size-style-width: ;--size-style-height: ;">
<a class="product-card__link" href="/products/simond-mt100-hooded-down-puffer-jacket-167571?variant=41320423063614" id="36cefc935f0b0a254f317ab98f544407" ref="productCardLink">
<span class="visually-hidden">
      Simond Men's MT100 Hooded Down Puffer Jacket
    </span>
</a>
<div class="product-card__content layout-panel-flex layout-panel-flex--column product-grid__card spacing-style border-style gap-style" style="
      --border-width: 1px; --border-style: none; --border-color:
rgb(var(--color-border-rgb) / 1.0); --border-radius:
0px;

      --flex-direction: column; --flex-wrap: nowrap; --flex-wrap-mobile: wrap;



--horizontal-alignment: ; --vertical-alignment: ;
--vertical-alignment-mobile: ;

      --padding-block-start: 0px;--padding-block-end: 0px;--padding-inline-start: 0px;--padding-inline-end: 0px;
      --product-card-gap: 4px;
      --quick-add-display: none;
      --quick-add-mobile-display: none;
      --quick-add-mobile-opacity: 0;




    ">
<div class="card-gallery card-gallery-AODAvcVh6b3p1OG5zN__card-gallery spacing-style border-style" data-image-ratio="square" data-product-id="4417342308414" on:pointerenter="/previewImage" on:pointerleave="/resetImage" ref="cardGallery" style="
    --border-width: 1px; --border-style: none; --border-color:
rgb(var(--color-border-rgb) / 1.0); --border-radius:
0px;

    --padding-block-start: 0px;--padding-block-end: 0px;--padding-inline-start: 0px;--padding-inline-end: 0px;
    --gallery-aspect-ratio: 1;
  ">
<a aria-label="Simond Men's MT100 Hooded Down Puffer Jacket" class="contents" href="/products/simond-mt100-hooded-down-puffer-jacket-167571?variant=41320423063614" ref="cardGalleryLink">
<slideshow-component data-generic-media-size="37" disabled="true" infinite="" initial-slide="0" ref="slideshow" style="--slideshow-timeline: --slide-0, --slide-1, --slide-2, --slide-3, --slide-4, --slide-5, --slide-6, --slide-7, --slide-8, --slide-9, --slide-10, --slide-11, --slide-12, --slide-13, --slide-14, --slide-15, --slide-16, --slide-17, --slide-18, --slide-19, --slide-20, --slide-21, --slide-22, --slide-23, --slide-24, --slide-25, --slide-26, --slide-27, --slide-28, --slide-29, --slide-30, --slide-31, --slide-32, --slide-33, --slide-34, --slide-35, --slide-36, --slide-37, --slide-38, --slide-39, --slide-40;--slide-min-height: auto;--slide-min-height-desktop: auto;">
<slideshow-container ref="slideshowContainer">
<slideshow-arrows position="center"><button aria-label="Previous slide" class="slideshow-control slideshow-control--previous slideshow-control--style-arrow button button-unstyled button-unstyled--transparent flip-x" on:click="/previous" ref="previous">
<span class="svg-wrapper icon-arrow"><svg aria-hidden="true" fill="none" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M4.25 10h11.5m0 0-4-4m4 4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)" vector-effect="non-scaling-stroke"></path></svg>
</span>
</button>
<button aria-label="Next slide" class="slideshow-control slideshow-control--next slideshow-control--style-arrow button button-unstyled button-unstyled--transparent" on:click="/next" ref="next">
<span class="svg-wrapper icon-arrow"><svg aria-hidden="true" fill="none" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M4.25 10h11.5m0 0-4-4m4 4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)" vector-effect="non-scaling-stroke"></path></svg>
</span>
</button>
</slideshow-arrows>
<slideshow-slides ref="scroller" tabindex="-1">
<slideshow-slide aria-hidden="false" class="product-media-container media-fit product-media-container--image" ref="slides[]" slide-id="24955728592958" style="--slideshow-timeline: --slide-0; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
<div class="product-media" data-media-id="24955728592958" style="--ratio: 1.0">
<img alt="{*asphalt-blue-8858286*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840" fetchpriority="auto" height="3840" loading="eager" sizes="(min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>
<slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" ref="slides[]" slide-id="24955730657342" style="--slideshow-timeline: --slide-1; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;">
<div class="product-media" data-media-id="24955730657342" style="--ratio: 1.0">
<img alt="{*asphalt-blue-8858286*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>
<slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="26172575580222" style="--slideshow-timeline: --slide-13; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
<div class="product-media" data-media-id="26172575580222" style="--ratio: 1.0">
<img alt="{*smoked-black-8858287*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>
<slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="24955734655038" style="--slideshow-timeline: --slide-20; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
<div class="product-media" data-media-id="24955734655038" style="--ratio: 1.0">
<img alt="{*olive-green-8595408*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>
<slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="26173860479038" style="--slideshow-timeline: --slide-33; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
<div class="product-media" data-media-id="26173860479038" style="--ratio: 1.0">
<img alt="Simond Men's MT100 Hooded Down Puffer Jacket" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>
</slideshow-slides>
</slideshow-container>
</slideshow-component>
</a>
<div class="product-badges product-badges--top-right" style="
        --badge-border-radius: 100px;
        --badge-font-family: var(--font-body--family); --badge-font-weight: var(--font-body--weight); --badge-text-transform: none;
      "></div>
</div>
<div class="product-grid-view-zoom-out--details">
<h3 class="h4">Simond Men's MT100 Hooded Down Puffer Jacket</h3>
</div>
<product-swatches data-product-id="4417342308414" data-product-url="/products/simond-mt100-hooded-down-puffer-jacket-167571" style="
      --overflow-list-alignment: flex-start;
      --overflow-list-alignment-mobile: flex-start;
      --product-swatches-alignment: start;
      --product-swatches-alignment-mobile: start;
      --product-swatches-padding-block-start: 0px;
      --product-swatches-padding-block-end: 0px;
      --product-swatches-padding-inline-start: 0px;
      --product-swatches-padding-inline-end: 0px;
    ">
<swatches-variant-picker-component data-product-id="4417342308414" data-product-url="/products/simond-mt100-hooded-down-puffer-jacket-167571" ref="swatchesVariantPicker">
<form>
<fieldset class="variant-option variant-option--buttons variant-option--swatches">
<overflow-list ref="overflowList">
<template shadowrootmode="open">
<link href="//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.css?v=16727044177065489451775763283" media="all" rel="stylesheet" type="text/css">
<ul part="list">
<slot></slot>
<slot hidden="" name="more" part="more">
<li part="more">
<button class="button" tabindex="0" type="button">
            More
          </button>
</li>
</slot>
<li hidden="" part="placeholder"></li>
</ul>
<div part="overflow">
<ul part="overflow-list">
<slot name="overflow"></slot>
</ul>
</div>
</link></template>
<li class="variant-option__swatch">
<label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="24955728592958" on:pointerenter="product-card/previewVariant/24955728592958" on:pointerleave="product-card/resetVariant">
<input aria-label="Asphalt Blue" data-connected-product-url="" data-first-available-or-first-variant-id="41320423063614" data-input-id="1-0" data-option-available="true" data-option-media-id="24955728592958" data-option-value-id="2344181727294" data-variant-id="41320423063614" name="Color-4417342308414-swatch" type="radio" value="Asphalt Blue"/>
<span class="swatch swatch--variant-image" style="
    --swatch-background: url(//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=100);

  ">
</span>
</label>
</li>
<li class="variant-option__swatch">
<label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="24955734655038" on:pointerenter="product-card/previewVariant/24955734655038" on:pointerleave="product-card/resetVariant">
<input aria-label="Olive Green" data-connected-product-url="" data-first-available-or-first-variant-id="32494250295358" data-input-id="1-1" data-option-available="true" data-option-media-id="24955734655038" data-option-value-id="1454888255550" data-variant-id="32494250295358" name="Color-4417342308414-swatch" type="radio" value="Olive Green"/>
<span class="swatch swatch--variant-image" style="
    --swatch-background: url(//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=100);

  ">
</span>
</label>
</li>
<li class="variant-option__swatch">
<label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="26173860479038" on:pointerenter="product-card/previewVariant/26173860479038" on:pointerleave="product-card/resetVariant">
<input aria-label="Dark Sepia" data-connected-product-url="" data-first-available-or-first-variant-id="41912831344702" data-input-id="1-2" data-option-available="true" data-option-media-id="26173860479038" data-option-value-id="2875192705086" data-variant-id="41912831344702" name="Color-4417342308414-swatch" type="radio" value="Dark Sepia"/>
<span class="swatch swatch--variant-image" style="
    --swatch-background: url(//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=100);

  ">
</span>
</label>
</li>
<li class="variant-option__swatch">
<label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="26172575580222" on:pointerenter="product-card/previewVariant/26172575580222" on:pointerleave="product-card/resetVariant">
<input aria-label="Smoked Black" data-connected-product-url="" data-first-available-or-first-variant-id="41912831148094" data-input-id="1-3" data-option-available="true" data-option-media-id="26172575580222" data-option-value-id="2875192672318" data-variant-id="41912831148094" name="Color-4417342308414-swatch" type="radio" value="Smoked Black"/>
<span class="swatch swatch--variant-image" style="
    --swatch-background: url(//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=100);

  ">
</span>
</label>
</li><li slot="more">
<button aria-label="Show all options" class="hidden-swatches__count" on:click="/showAllSwatches"></button>
</li>
</overflow-list>
</fieldset>
<script type="application/json">

In [23]:
type(items_tags) # What type is it?

bs4.element.ResultSet

In [42]:
# Lets look at how many elements we retrieved
len(items_tags)

24

In [44]:
# We can get the actual text using .text, .getText() or .get_text()
print(items_tags[0].text)
#print(bike_names_tags[0].getText())
#print(bike_names_tags[0].get_text())

      Simond Men's MT100 Hooded Down Puffer Jacket

















































Simond Men's MT100 Hooded Down Puffer Jacket













































Simond Men's MT100 Hooded Down Puffer Jacket





$119.00



Sale price
$119.00


Regular price

In [51]:
# Lets get rid of all the white spaces
[elem.getText().replace("\n","").strip() for elem in items_tags[0] if elem.getText().replace("\n","").strip()!= ""]

["Simond Men's MT100 Hooded Down Puffer Jacket",
 "Simond Men's MT100 Hooded Down Puffer JacketSimond Men's MT100 Hooded Down Puffer Jacket$119.00Sale price\xa0$119.00Regular price"]

In [77]:
import re

def extract_product_title(elem):
    # collapse "\n" + any following whitespace down to a single "\n" -- raw .getText() on a
    # whole card is full of stray whitespace/indentation between the nested tags
    item = re.sub(r'\n+\s+', '\n', elem.getText()).split("\n")
    return item

# Create a new list only with item names
extract_product_title(items_tags[0])

['',
 "Simond Men's MT100 Hooded Down Puffer Jacket",
 "Simond Men's MT100 Hooded Down Puffer Jacket",
 "Simond Men's MT100 Hooded Down Puffer Jacket",
 '$119.00',
 'Sale price\xa0',
 '$119.00',
 'Regular price\xa0',
 '']

To extract the price from the provided HTML content, we can use a modified version of the previous function to return a dictionary with the product title and price:

In [80]:
def extract_product_info(elem):
    item = re.sub(r'\n+\s+', '\n', elem.getText()).split("\n")
    # index-based, not name-based -- fragile: relies on every card having the exact same
    # number of text lines in the exact same order, which is why some products (see the
    # note below) don't parse cleanly
    return {"product-title": item[1], "product-price": item[4], "product-sale-price": item[6]}

extract_product_info(items_tags[0])

{'product-title': "Simond Men's MT100 Hooded Down Puffer Jacket",
 'product-price': '$119.00',
 'product-sale-price': '$119.00'}

Now, we can iterate over all the propducts using list comprehension and create a list of dictionaries with each product info.

In [81]:
[extract_product_info(item) for item in items_tags]

[{'product-title': "Simond Men's MT100 Hooded Down Puffer Jacket",
  'product-price': '$119.00',
  'product-sale-price': '$119.00'},
 {'product-title': "Simond Women's MT100 Hooded Down Puffer Jacket",
  'product-price': '$119.00',
  'product-sale-price': '$119.00'},
 {'product-title': "Quechua Men's MH100 Hiking Fleece",
  'product-price': '$24.99',
  'product-sale-price': '$24.99'},
 {'product-title': "Quechua Women's MH120 Fleece Jacket",
  'product-price': '$34.99',
  'product-sale-price': '$34.99'},
 {'product-title': 'Quechua 2 Second Fresh & Black Waterproof Pop Up Camping Tent 3 Person',
  'product-price': '$179.00',
  'product-sale-price': '$179.00'},
 {'product-title': 'Quechua NH100 Arpenaz 10 L Hiking Backpack',
  'product-price': 'Quechua NH100 Arpenaz 10 L Hiking Backpack',
  'product-sale-price': 'Sale price\xa0'},
 {'product-title': 'Quechua NH50 Arpenaz 10 L Hiking Backpack',
  'product-price': '$5.99',
  'product-sale-price': '$5.99'},
 {'product-title': "Simond  Men's MT100 Easyfit 70L Backpacking Pack",
  'product-price': '$129.00',
  'product-sale-price': '$129.00'},
 {'product-title': 'Simond 500 Extend 40-60 L Duffel Bag',
  'product-price': '$99.99',
  'product-sale-price': '$99.99'},
 {'product-title': 'Simond 500 Extend 30-40 L Duffel Bag',
  'product-price': 'Simond 500 Extend 30-40 L Duffel Bag',
  'product-sale-price': 'Sale price\xa0'},
 {'product-title': "Forclaz Men's MT100 Hooded Synthetic Jacket",
  'product-price': '$69.99',
  'product-sale-price': '$69.99'},
 {'product-title': "Forclaz Women's MT100 Hooded Synthetic Jacket",
  'product-price': "Forclaz Women's MT100 Hooded Synthetic Jacket",
  'product-sale-price': 'Sale price\xa0'},
 {'product-title': 'Quechua NH500 Escape Rolltop 23 L Backpack',
  'product-price': '$59.99',
  'product-sale-price': '$59.99'},
 {'product-title': 'Quechua NH500 Escape 23 L Hiking Backpack',
  'product-price': '$54.99',
  'product-sale-price': '$54.99'},
 {'product-title': 'Simond Adult MT500 Merino Wool Beanie',
  'product-price': 'Simond Adult MT500 Merino Wool Beanie',
  'product-sale-price': 'Sale price\xa0'},
 {'product-title': "Simond Men's Travel 500 Merino Wool T-Shirt",
  'product-price': "Simond Men's Travel 500 Merino Wool T-Shirt",
  'product-sale-price': 'Sale price\xa0'},
 {'product-title': 'Forclaz ONNIGHT 100 Battery-Powered 80 Lumens Hiking Head Lamp',
  'product-price': '$14.99',
  'product-sale-price': '$14.99'},
 {'product-title': "Wedze Kids' BL100 Thermal Ski Base Layer Top",
  'product-price': '$9.99',
  'product-sale-price': '$9.99'},
 {'product-title': "Quechua Men's SH100 U-Warm Waterproof Snow Boots",
  'product-price': "Quechua Men's SH100 U-Warm Waterproof Snow Boots",
  'product-sale-price': 'Sale price\xa0'},
 {'product-title': "Quechua Women's MH100 T-Shirt",
  'product-price': "Quechua Women's MH100 T-Shirt",
  'product-sale-price': 'Sale price\xa0'},
 {'product-title': 'Quechua NH100 Arpenaz 20 L Hiking Backpack',
  'product-price': '$19.99',
  'product-sale-price': '$19.99'},
 {'product-title': "Wedze Kids' BL100 Thermal Ski Base Layer Bottom",
  'product-price': '$9.99',
  'product-sale-price': '$9.99'},
 {'product-title': "Simond Men's MT500 Down Puffer Jacket",
  'product-price': '$149.00',
  'product-sale-price': '$149.00'},
 {'product-title': 'Quechua 2 Second Easy Fresh & Black Waterproof Pop Up Camping Tent 2 Person',
  'product-price': '$249.00',
  'product-sale-price': '$249.00'}]

Once we have this information, we can store it into a Pandas DataFrame

In [82]:
# Find the <span> tag and get its text
import pandas as pd

pd.DataFrame([extract_product_info(item) for item in items_tags])

,product-title,product-price,product-sale-price
0,Simond Men's MT100 Hooded Down Puffer Jacket,$119.00,$119.00
1,Simond Women's MT100 Hooded Down Puffer Jacket,$119.00,$119.00
2,Quechua Men's MH100 Hiking Fleece,$24.99,$24.99
3,Quechua Women's MH120 Fleece Jacket,$34.99,$34.99
4,Quechua 2 Second Fresh & Black Waterproof Pop ...,$179.00,$179.00
5,Quechua NH100 Arpenaz 10 L Hiking Backpack,Quechua NH100 Arpenaz 10 L Hiking Backpack,Sale price
6,Quechua NH50 Arpenaz 10 L Hiking Backpack,$5.99,$5.99
7,Simond Men's MT100 Easyfit 70L Backpacking Pack,$129.00,$129.00
8,Simond 500 Extend 40-60 L Duffel Bag,$99.99,$99.99
9,Simond 500 Extend 30-40 L Duffel Bag,Simond 500 Extend 30-40 L Duffel Bag,Sale price
10,Forclaz Men's MT100 Hooded Synthetic Jacket,$69.99,$69.99
11,Forclaz Women's MT100 Hooded Synthetic Jacket,Forclaz Women's MT100 Hooded Synthetic Jacket,Sale price
12,Quechua NH500 Escape Rolltop 23 L Backpack,$59.99,$59.99
13,Quechua NH500 Escape 23 L Hiking Backpack,$54.99,$54.99
14,Simond Adult MT500 Merino Wool Beanie,Simond Adult MT500 Merino Wool Beanie,Sale price
15,Simond Men's Travel 500 Merino Wool T-Shirt,Simond Men's Travel 500 Merino Wool T-Shirt,Sale price
16,Forclaz ONNIGHT 100 Battery-Powered 80 Lumens ...,$14.99,$14.99
17,Wedze Kids' BL100 Thermal Ski Base Layer Top,$9.99,$9.99
18,Quechua Men's SH100 U-Warm Waterproof Snow Boots,Quechua Men's SH100 U-Warm Waterproof Snow Boots,Sale price
19,Quechua Women's MH100 T-Shirt,Quechua Women's MH100 T-Shirt,Sale price
20,Quechua NH100 Arpenaz 20 L Hiking Backpack,$19.99,$19.99
21,Wedze Kids' BL100 Thermal Ski Base Layer Bottom,$9.99,$9.99
22,Simond Men's MT500 Down Puffer Jacket,$149.00,$149.00
23,Quechua 2 Second Easy Fresh & Black Waterproof...,$249.00,$249.00

As we can see, our strategy worked for all the products with a few exception as products: 5, 9, 11, 14, 15, 18, and 19. Very likely, the HMTL code of those product had a different pattern that prevented our code to work properly.

##### **Getting other attributes**

To access other attribute values such as hyperlinks (which are usually contained in the `href` attribute of `a` tags), you first locate the element using BeautifulSoup methods such as `find` or `find_all`, and then use the `.get()` method to retrieve the value of the attribute you're interested in. Here is a step-by-step explanation:

1. **Locate the element**: Use `find` or `find_all` to locate the element(s) that contain the attribute you want to access.

    ```python
    link_element = soup.find('a', class_='link-class')
    ```

2. **Access the attribute**: Once you have the element, use the `.get()` method to access the attribute value.

    ```python
    link_url = link_element.get('href')
    ```

In the above snippet:
- We first find the `a` element with the class `'link-class'`.
- We then get the value of the `href` attribute which contains the hyperlink.

If we pay attention to the website, and the Chrome inspector, we can see that each product has an "a" tag inside with an href.

In [85]:
items_tags[0].find("a")["href"]

'/products/simond-mt100-hooded-down-puffer-jacket-167571?variant=41320423063614'

However, this website stored in the "href" attribute, it's not full. It's relative to the main page! Therefore, in order to have the corresponding url of each product we only need to concatenate the base url with the relative url.

In [86]:
url + items_tags[0].find("a")["href"]

'https://www.decathlon.com/collections/camp-hike/products/simond-mt100-hooded-down-puffer-jacket-167571?variant=41320423063614'

#### More filtering options

##### Filtering by Multiple Tags

To find elements with multiple possible tags, you can pass a list of tag names to `find_all`.

In [87]:
# Find all <div> and <span> tags
soup.find_all(['div', 'span'])

Output hidden; open in https://colab.research.google.com to view.

##### Filtering by Multiple Classes

To find elements with multiple possible classes, you can pass a list of class names.

In [88]:
# Find all elements with class 'collection-wrapper', 'grid gap-style'
soup.find_all(class_=['collection-wrapper', 'grid gap-style'])

[<div class="collection-wrapper grid gap-style">
 <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/facets.js?v=177903033754413523221775763283" type="module"></script>
 <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/scrolling.js?v=162288454571026455011775763283" type="module"></script>
 <div class="facets-block-wrapper facets-block-wrapper--horizontal" style="
       --grid-column--desktop:var(--centered);
       --facets-margin: 0px  0px 8px 0px;
       --facets-inner-padding-block: 8px 8px;
       --facets-inner-padding-inline: var(--padding-lg);
     ">
 <div aria-label="Filters" class="facets facets--horizontal spacing-style" style="--padding-block-start: 8px;--padding-block-end: 8px;--padding-inline-start: 0px;--padding-inline-end: 0px;">
 <facets-form-component class="facets__form-wrapper" form-style="horizontal" section-id="template--18434715222078__main">
 <form action="/collections/camp-hike" class="facets__form" id="FacetFiltersForm--template--18434715222078__main-desktop" ref="facetsForm">
 <div class="facets-remove facets-remove--mobile-and-vertical"><h3 class="visually-hidden">Active filters:</h3>
 </div>
 <div class="facets__filters-wrapper">
 <overflow-list class="facets__overflow-list" data-testid="horizontal-filters-overflow-list" minimum-items="2">
 <template shadowrootmode="open">
 <link href="//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.css?v=16727044177065489451775763283" media="all" rel="stylesheet" type="text/css">
 <ul part="list">
 <slot></slot>
 <slot hidden="" name="more" on:click="#filters-drawer/showDialog" part="more">
 <li part="more">
 <button aria-haspopup="dialog" class="button" tabindex="0" type="button">
             More
           </button>
 </li>
 </slot>
 <li hidden="" part="placeholder"></li>
 </ul>
 <div part="overflow">
 <ul part="overflow-list">
 <slot name="overflow"></slot>
 </ul>
 </div>
 </link></template>
 <accordion-custom class="facets__item" data-close-with-escape="true" data-disable-animation-on-desktop="true" data-filter-param-name="filter-p-product_type">
 <details class="facets__panel" data-auto-close-details="desktop" id="Facet-Details-template--18434715222078__main-filter-p-product_type">
 <summary class="facets__summary">
 <span class="facets__label">Category</span>
 <div class="facets__status-wrapper">
 <facet-status-component class="facets__status" data-filter-style="horizontal" facet-type="list">
 <span class="hide-when-empty" ref="facetStatus"></span>
 </facet-status-component>
 <span class="svg-wrapper icon-caret icon-animated"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
 <path d="M11 5.5L7 9.5L3 5.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 </span>
 </div>
 </summary>
 <floating-panel-component class="facets__inputs facets__panel-content details-content color-scheme-1" data-close-on-resize="" id="facet-inputs-filter-p-product_type">
 <facet-inputs-component id="facet-inputs-component-filter-p-product_type" on:change="/updateFilters">
 <show-more-component class="show-more" data-disable-on-desktop="true" data-expanded="false" data-skip-node-update="true">
 <div class="facets__inputs-wrapper" ref="showMoreContent">
 <ul class="facets__inputs-list list-unstyled" id="filters-list-template--18434715222078__main-filter-p-product_type" name="Category">
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="3 in 1 jacket" id="Filter-filter-p-product_type-1-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="3 in 1 jacket"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-1-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">3 in 1 jacket</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Backpack" id="Filter-filter-p-product_type-2-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Backpack"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-2-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Backpack</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Bag protector" id="Filter-filter-p-product_type-3-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Bag protector"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-3-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Bag protector</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Base layer" id="Filter-filter-p-product_type-4-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Base layer"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-4-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Base layer</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Baselayer bottom" id="Filter-filter-p-product_type-5-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Baselayer bottom"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-5-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Baselayer bottom</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Beanie" id="Filter-filter-p-product_type-6-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Beanie"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-6-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Beanie</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Bed base" id="Filter-filter-p-product_type-7-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Bed base"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-7-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Bed base</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Belt bag" id="Filter-filter-p-product_type-8-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Belt bag"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-8-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Belt bag</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Bottle cap" id="Filter-filter-p-product_type-9-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Bottle cap"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-9-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Bottle cap</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Boxer shorts" id="Filter-filter-p-product_type-10-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Boxer shorts"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-10-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Boxer shorts</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Boxers" id="Filter-filter-p-product_type-11-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Boxers"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-11-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Boxers</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Cap" id="Filter-filter-p-product_type-12-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Cap"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-12-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Cap</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Chest strap" id="Filter-filter-p-product_type-13-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Chest strap"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-13-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Chest strap</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Cookset" id="Filter-filter-p-product_type-14-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Cookset"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-14-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Cookset</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Down jacket" id="Filter-filter-p-product_type-15-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Down jacket"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-15-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Down jacket</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Fastener" id="Filter-filter-p-product_type-16-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Fastener"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-16-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Fastener</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Fleece" id="Filter-filter-p-product_type-17-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Fleece"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-17-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">

##### Combining Multiple Criteria

You can combine multiple criteria by using the `attrs` argument.

In [90]:
# Find all <h4> or <span> tags with class "class1" or "class2"
soup.find_all('div', attrs={"class": ['collection-wrapper', 'grid gap-style']})

[<div class="collection-wrapper grid gap-style">
 <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/facets.js?v=177903033754413523221775763283" type="module"></script>
 <script fetchpriority="low" src="//www.decathlon.com/cdn/shop/t/374/assets/scrolling.js?v=162288454571026455011775763283" type="module"></script>
 <div class="facets-block-wrapper facets-block-wrapper--horizontal" style="
       --grid-column--desktop:var(--centered);
       --facets-margin: 0px  0px 8px 0px;
       --facets-inner-padding-block: 8px 8px;
       --facets-inner-padding-inline: var(--padding-lg);
     ">
 <div aria-label="Filters" class="facets facets--horizontal spacing-style" style="--padding-block-start: 8px;--padding-block-end: 8px;--padding-inline-start: 0px;--padding-inline-end: 0px;">
 <facets-form-component class="facets__form-wrapper" form-style="horizontal" section-id="template--18434715222078__main">
 <form action="/collections/camp-hike" class="facets__form" id="FacetFiltersForm--template--18434715222078__main-desktop" ref="facetsForm">
 <div class="facets-remove facets-remove--mobile-and-vertical"><h3 class="visually-hidden">Active filters:</h3>
 </div>
 <div class="facets__filters-wrapper">
 <overflow-list class="facets__overflow-list" data-testid="horizontal-filters-overflow-list" minimum-items="2">
 <template shadowrootmode="open">
 <link href="//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.css?v=16727044177065489451775763283" media="all" rel="stylesheet" type="text/css">
 <ul part="list">
 <slot></slot>
 <slot hidden="" name="more" on:click="#filters-drawer/showDialog" part="more">
 <li part="more">
 <button aria-haspopup="dialog" class="button" tabindex="0" type="button">
             More
           </button>
 </li>
 </slot>
 <li hidden="" part="placeholder"></li>
 </ul>
 <div part="overflow">
 <ul part="overflow-list">
 <slot name="overflow"></slot>
 </ul>
 </div>
 </link></template>
 <accordion-custom class="facets__item" data-close-with-escape="true" data-disable-animation-on-desktop="true" data-filter-param-name="filter-p-product_type">
 <details class="facets__panel" data-auto-close-details="desktop" id="Facet-Details-template--18434715222078__main-filter-p-product_type">
 <summary class="facets__summary">
 <span class="facets__label">Category</span>
 <div class="facets__status-wrapper">
 <facet-status-component class="facets__status" data-filter-style="horizontal" facet-type="list">
 <span class="hide-when-empty" ref="facetStatus"></span>
 </facet-status-component>
 <span class="svg-wrapper icon-caret icon-animated"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
 <path d="M11 5.5L7 9.5L3 5.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 </span>
 </div>
 </summary>
 <floating-panel-component class="facets__inputs facets__panel-content details-content color-scheme-1" data-close-on-resize="" id="facet-inputs-filter-p-product_type">
 <facet-inputs-component id="facet-inputs-component-filter-p-product_type" on:change="/updateFilters">
 <show-more-component class="show-more" data-disable-on-desktop="true" data-expanded="false" data-skip-node-update="true">
 <div class="facets__inputs-wrapper" ref="showMoreContent">
 <ul class="facets__inputs-list list-unstyled" id="filters-list-template--18434715222078__main-filter-p-product_type" name="Category">
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="3 in 1 jacket" id="Filter-filter-p-product_type-1-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="3 in 1 jacket"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-1-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">3 in 1 jacket</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Backpack" id="Filter-filter-p-product_type-2-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Backpack"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-2-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Backpack</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Bag protector" id="Filter-filter-p-product_type-3-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Bag protector"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-3-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Bag protector</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Base layer" id="Filter-filter-p-product_type-4-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Base layer"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-4-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Base layer</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Baselayer bottom" id="Filter-filter-p-product_type-5-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Baselayer bottom"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-5-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Baselayer bottom</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Beanie" id="Filter-filter-p-product_type-6-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Beanie"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-6-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Beanie</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Bed base" id="Filter-filter-p-product_type-7-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Bed base"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-7-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Bed base</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Belt bag" id="Filter-filter-p-product_type-8-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Belt bag"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-8-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Belt bag</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Bottle cap" id="Filter-filter-p-product_type-9-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Bottle cap"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-9-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Bottle cap</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item" data-skip-node-update="true">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Boxer shorts" id="Filter-filter-p-product_type-10-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Boxer shorts"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-10-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Boxer shorts</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Boxers" id="Filter-filter-p-product_type-11-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Boxers"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-11-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Boxers</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Cap" id="Filter-filter-p-product_type-12-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Cap"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-12-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Cap</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Chest strap" id="Filter-filter-p-product_type-13-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Chest strap"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-13-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Chest strap</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Cookset" id="Filter-filter-p-product_type-14-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Cookset"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-14-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Cookset</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Down jacket" id="Filter-filter-p-product_type-15-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Down jacket"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-15-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Down jacket</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Fastener" id="Filter-filter-p-product_type-16-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Fastener"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-16-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">
 <path d="M4.75439 10.7485L7.68601 14.5888C7.79288 14.7288 7.84632 14.7988 7.91174 14.8242C7.96907 14.8466 8.03262 14.8469 8.09022 14.8253C8.15596 14.8007 8.21026 14.7314 8.31886 14.5927L15.2475 5.74658" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 <span class="checkbox__label-text">Fastener</span>
 </label>
 </div>
 </li>
 <li class="facets__inputs-list-item mobile:hidden" data-skip-node-update="true" ref="showMoreItems[]">
 <div class="checkbox" on:pointerenter="/prefetchPage" on:pointerleave="/cancelPrefetchPage">
 <input class="checkbox__input" data-label="Fleece" id="Filter-filter-p-product_type-17-horizontal-" name="filter.p.product_type" ref="facetInputs[]" type="checkbox" value="Fleece"/>
 <label class="checkbox__label" for="Filter-filter-p-product_type-17-horizontal-">
 <svg aria-hidden="true" class="icon-checkmark" fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">

##### Limiting the Results

You can limit the number of results returned by `find_all` using the `limit` parameter.

In [91]:
# Only get the first 5 <h4> tags
soup.find_all('h4', limit=5)

[<h4 class="predictive-search-results__title">
       Products
     </h4>]

##### Navigating through the "Tree" of HTML Elements

Beautiful Soup provides a robust set of tools that allow you to traverse and explore the hierarchical structure of an HTML document, often referred to as the "tree".

To access child elements directly:

In [92]:
#soup.find_all('section', attrs={"class": ["product__info-container", "product__column-sticky"]})
for tag in soup.find_all('product-card', class_="product-card size-style"):
    print(tag.find_all("a"))
#    print()

[<a class="product-card__link" href="/products/simond-mt100-hooded-down-puffer-jacket-167571?variant=41320423063614" id="36cefc935f0b0a254f317ab98f544407" ref="productCardLink">
<span class="visually-hidden">
      Simond Men's MT100 Hooded Down Puffer Jacket
    </span>
</a>, <a aria-label="Simond Men's MT100 Hooded Down Puffer Jacket" class="contents" href="/products/simond-mt100-hooded-down-puffer-jacket-167571?variant=41320423063614" ref="cardGalleryLink">
<slideshow-component data-generic-media-size="37" disabled="true" infinite="" initial-slide="0" ref="slideshow" style="--slideshow-timeline: --slide-0, --slide-1, --slide-2, --slide-3, --slide-4, --slide-5, --slide-6, --slide-7, --slide-8, --slide-9, --slide-10, --slide-11, --slide-12, --slide-13, --slide-14, --slide-15, --slide-16, --slide-17, --slide-18, --slide-19, --slide-20, --slide-21, --slide-22, --slide-23, --slide-24, --slide-25, --slide-26, --slide-27, --slide-28, --slide-29, --slide-30, --slide-31, --slide-32, --slide-33, --slide-34, --slide-35, --slide-36, --slide-37, --slide-38, --slide-39, --slide-40;--slide-min-height: auto;--slide-min-height-desktop: auto;">
<slideshow-container ref="slideshowContainer">
<slideshow-arrows position="center"><button aria-label="Previous slide" class="slideshow-control slideshow-control--previous slideshow-control--style-arrow button button-unstyled button-unstyled--transparent flip-x" on:click="/previous" ref="previous">
<span class="svg-wrapper icon-arrow"><svg aria-hidden="true" fill="none" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M4.25 10h11.5m0 0-4-4m4 4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)" vector-effect="non-scaling-stroke"></path></svg>
</span>
</button>
<button aria-label="Next slide" class="slideshow-control slideshow-control--next slideshow-control--style-arrow button button-unstyled button-unstyled--transparent" on:click="/next" ref="next">
<span class="svg-wrapper icon-arrow"><svg aria-hidden="true" fill="none" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M4.25 10h11.5m0 0-4-4m4 4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)" vector-effect="non-scaling-stroke"></path></svg>
</span>
</button>
</slideshow-arrows>
<slideshow-slides ref="scroller" tabindex="-1">
<slideshow-slide aria-hidden="false" class="product-media-container media-fit product-media-container--image" ref="slides[]" slide-id="24955728592958" style="--slideshow-timeline: --slide-0; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
<div class="product-media" data-media-id="24955728592958" style="--ratio: 1.0">
<img alt="{*asphalt-blue-8858286*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840" fetchpriority="auto" height="3840" loading="eager" sizes="(min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>
<slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" ref="slides[]" slide-id="24955730657342" style="--slideshow-timeline: --slide-1; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;">
<div class="product-media" data-media-id="24955730657342" style="--ratio: 1.0">
<img alt="{*asphalt-blue-8858286*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>
<slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="26172575580222" style="--slideshow-timeline: --slide-13; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
<div class="product-media" data-media-id="26172575580222" style="--ratio: 1.0">
<img alt="{*smoked-black-8858287*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>
<slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="24955734655038" style="--slideshow-timeline: --slide-20; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
<div class="product-media" data-media-id="24955734655038" style="--ratio: 1.0">
<img alt="{*olive-green-8595408*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>
<slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="26173860479038" style="--slideshow-timeline: --slide-33; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
<div class="product-media" data-media-id="26173860479038" style="--ratio: 1.0">
<img alt="Simond Men's MT100 Hooded Down Puffer Jacket" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>
</slideshow-slides>
</slideshow-container>
</slideshow-component>
</a>, <a class="contents user-select-text" href="/products/simond-mt100-hooded-down-puffer-jacket-167571?variant=41320423063614" ref="productTitleLink">
<div class="spacing-style text-block text-block--AZW1GSHBlK0owZEZTV__product_title_4nY4eT custom text-block--align-left custom-typography custom-font-size custom-color" style="    --padding-block-start: 0px; --padding-block-end:0px; --padding-inline-start:0px; --padding-inline-end:0px;     --color: var(--color-foreground);--font-size: 1rem;      --font-weight: var(--font-heading--weight);--font-family: var(--font-heading--family);    --text-transform: none;    --text-wrap: pretty;          --line-height: var(--line-height--body-normal);        --letter-spacing: var(--letter-spacing--body-normal);    --width: 100%;    --max-width: var(--max-width--body-normal);          --text-align: left;          ">
<p aria-level="3" role="heading">Simond Men's MT100 Hooded Down Puffer Jacket</p>
</div>
</a>]
[<a class="product-card__link" href="/products/simond-trek-100-23-f-down-packable-puffer-backpacking-jacket-167572?variant=41255240925246" id="0ec86d9e04b5e167698201d25153f6ea" ref="productCardLink">
<span class="visually-hidden">
      Simond Women's MT100 Hooded Down Puffer Jacket
    </span>
</a>, <a aria-label="Simond Women's MT100 Hooded Down Puffer Jacket" class="contents" href="/products/simond-trek-100-23-f-down-packable-puffer-backpacking-jacket-167572?variant=41255240925246" ref="cardGalleryLink">
<slideshow-component data-generic-media-size="35" disabled="true" infinite="" initial-slide="0" ref="slideshow" style="--slideshow-timeline: --slide-0, --slide-1, --slide-2, --slide-3, --slide-4, --slide-5, --slide-6, --slide-7, --slide-8, --slide-9, --slide-10, --slide-11, --slide-12, --slide-13, --slide-14, --slide-15, --slide-16, --slide-17, --slide-18, --slide-19, --slide-20, --slide-21, --slide-22, --slide-23, --slide-24, --slide-25, --slide-26, --slide-27, --slide-28, --slide-29, --slide-30, --slide-31, --slide-32, --slide-33, --slide-34, --slide-35, --slide-36, --slide-37, --slide-38;--slide-min-height: auto;--slide-min-height-desktop: auto;">
<slideshow-container ref="slideshowContainer">
<slideshow-arrows position="center"><button aria-label="Previous slide" class="slideshow-control slideshow-control--previous slideshow-control--style-arrow button button-unstyled button-unstyled--transparent flip-x" on:click="/previous" ref="previous">
<span class="svg-wrapper icon-arrow"><svg aria-hidden="true" fill="none" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M4.25 10h11.5m0 0-4-4m4 4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)" vector-effect="non-scaling-stroke"></path></svg>
</span>
</button>
<button aria-label="Next slide" class="slideshow-control slideshow-control--next slideshow-control--style-arrow button button-unstyled button-unstyled--transparent" on:click="/next" ref="next">
<span class="svg-wrapper icon-arrow"><svg aria-hidden="true" fill="none" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M4.25 10h11.5m0 0-4-4m4 4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)" vector-effect="non-scaling-stroke"></path></svg>
</span>
</button>
</slideshow-arrows>
<slideshow-slides ref="scroller" tabindex="-1">
<slideshow-slide aria-hidden="false" class="product-media-container media-fit product-media-container--image" ref="slides[]" slide-id="26268973695038" style="--slideshow-timeline: --slide-0; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
<div class="product-media" data-media-id="26268973695038" style="--ratio: 1.0">
<img alt="{*asphalt-blue-8858267*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858267-product_image-p2688040_15b806ce-a1f3-4bef-abfb-db3d0c705ad6.jpg?v=1757454981&amp;width=3840" fetchpriority="auto" height="3840" loading="eager" sizes="(min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858267-product_image-p2688040_15b806ce-a1f3-4bef-abfb-db3d0c705ad6.jpg?v=1757454981&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858267-product_image-p2688040_15b806ce-a1f3-4bef-abfb-db3d0c705ad6.jpg?v=1757454981&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2688040_15b806ce-a1f3-4bef-abfb-db3d0c705ad6.jpg?v=1757454981&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2688040_15b806ce-a1f3-4bef-abfb-db3d0c705ad6.jpg?v=1757454981&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2688040_15b806ce-a1f3-4bef-abfb-db3d0c705ad6.jpg?v=1757454981&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2688040_15b806ce-a1f3-4bef-abfb-db3d0c705ad6.jpg?v=1757454981&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2688040_15b806ce-a1f3-4bef-abfb-db3d0c705ad6.jpg?v=1757454981&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2688040_15b806ce-a1f3-4bef-abfb-db3d0c705ad6.jpg?v=1757454981&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2688040_15b806ce-a1f3-4bef-abfb-db3d0c705ad6.jpg?v=1757454981&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>
<slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" ref="slides[]" slide-id="26268973727806" style="--slideshow-timeline: --slide-1; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;">
<div class="product-media" data-media-id="26268973727806" style="--ratio: 1.0">
<img alt="{*asphalt-blue-8858267*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858267-product_image-p2690826_454a682b-6e8a-4ab9-8c9f-234f4e6d524b.jpg?v=1757454984&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858267-product_image-p2690826_454a682b-6e8a-4ab9-8c9f-234f4e6d524b.jpg?v=1757454984&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858267-product_image-p2690826_454a682b-6e8a-4ab9-8c9f-234f4e6d524b.jpg?v=1757454984&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2690826_454a682b-6e8a-4ab9-8c9f-234f4e6d524b.jpg?v=1757454984&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2690826_454a682b-6e8a-4ab9-8c9f-234f4e6d524b.jpg?v=1757454984&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2690826_454a682b-6e8a-4ab9-8c9f-234f4e6d524b.jpg?v=1757454984&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2690826_454a682b-6e8a-4ab9-8c9f-234f4e6d524b.jpg?v=1757454984&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2690826_454a682b-6e8a-4ab9-8c9f-234f4e6d524b.jpg?v=1757454984&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2690826_454a682b-6e8a-4ab9-8c9f-234f4e6d524b.jpg?v=1757454984&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858267-product_image-p2690826_454a682b-6e8a-4ab9-8c9f-234f4e6d524b.jpg?v=1757454984&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
</div>
</slideshow-slide>

The code above will first locate the initial `div` element present in the Beautiful Soup object. Subsequently, it will fetch all `h4` elements contained within that `div`.

But what if you need to retrieve a specific child by its position, say the second child?

In [97]:
soup.ul.find_all("li")[0]

<li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 1;"><details class="menu-drawer__menu-container menu-drawer__menu-container--divider" id="Details-menu-drawer-menu-item-1">
<summary class="menu-drawer__menu-item menu-drawer__menu-item--mainlist menu-drawer__animated-element focus-inset menu-drawer__menu-item--active" id="HeaderDrawer-all-sports" on:click="header-drawer/open/submenu">
<span class="menu-drawer__menu-item-text wrap-text">All Sports</span>
<span class="svg-wrapper icon-caret icon-caret--forward"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
<path d="M11 5.5L7 9.5L3 5.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
</svg>
</span>
</summary>
<div class="menu-drawer__submenu has-submenu" id="link-all-sports" style="--menu-drawer-animation-index: 1;" tabindex="-1">
<div class="menu-drawer__inner-submenu">
<div class="menu-drawer__nav-buttons">
<button aria-label="Back to All Sports" class="button menu-drawer__back-button focus-inset" on:click="header-drawer/back">
<span class="svg-wrapper icon-caret icon-caret--backward"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
<path d="M11 5.5L7 9.5L3 5.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
</svg>
</span>
<span class="menu-drawer__menu-item-text wrap-text">All Sports</span>
</button>
<button aria-label="Close" class="button button-unstyled close-button menu-drawer__close-button" on:click="header-drawer/close" type="button">
<span class="svg-wrapper header-drawer-icon header-drawer-icon--close"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
<path d="M12 2L2 12" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
<path d="M12 12L2 2" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
</svg>
</span>
</button>
</div>
<ul class="menu-drawer__menu menu-drawer__menu--childlist" role="list" tabindex="-1">
<li class="menu-drawer__list-item menu-drawer__list-item--deep menu-drawer__list-item--divider">
<accordion-custom>
<details id="Details-menu-drawer-all-sports-hiking-backpacking">
<summary class="menu-drawer__menu-item menu-drawer__menu-item--parent focus-inset" id="HeaderDrawer-all-sports-hiking-backpacking">
<span class="menu-drawer__menu-item-text wrap-text">Hiking &amp; Backpacking</span>
<span class="svg-wrapper icon-plus"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
<path class="vertical" d="M2.75 7H11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
<path class="horizontal" d="M7 2.75L7 11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
</svg>
</span>
</summary>
<ul class="menu-drawer__menu menu-drawer__menu--grandchildlist details-content menu-drawer__menu--grid" role="list" tabindex="-1"><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 1;">
<a aria-current="page" class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset menu-drawer__menu-item--active" href="/collections/camp-hike" id="HeaderDrawer-all-sports-hiking-backpacking-all-hiking-backpacking">
<img alt="Hiking &amp; Backpacking" class="menu-drawer__link-image" height="533" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/Collections-Herobanner-Camp-_-hike.jpg?v=1759928429&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/Collections-Herobanner-Camp-_-hike.jpg?v=1759928429&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/Collections-Herobanner-Camp-_-hike.jpg?v=1759928429&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">All Hiking &amp; Backpacking</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 2;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/backpacks-bags" id="HeaderDrawer-all-sports-hiking-backpacking-bags-backpacks">
<img alt="Bags &amp; Backpacks" class="menu-drawer__link-image" height="533" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/QUECHUA_SAC_A_DOS_NH_ESCAPE_500_ROLLTOP_23L_JAUN_SS25_-_8736386_8787846_8803959_8803962_8826782_8871194_8920375_-_181_---_Expires_on_13-12-2028.jpg?v=1776978555&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/QUECHUA_SAC_A_DOS_NH_ESCAPE_500_ROLLTOP_23L_JAUN_SS25_-_8736386_8787846_8803959_8803962_8826782_8871194_8920375_-_181_---_Expires_on_13-12-2028.jpg?v=1776978555&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/QUECHUA_SAC_A_DOS_NH_ESCAPE_500_ROLLTOP_23L_JAUN_SS25_-_8736386_8787846_8803959_8803962_8826782_8871194_8920375_-_181_---_Expires_on_13-12-2028.jpg?v=1776978555&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Bags &amp; Backpacks</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 3;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/hiking-jackets" id="HeaderDrawer-all-sports-hiking-backpacking-jackets">
<img alt="Hiking Jackets" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/8595408-context_image-p1901879.jpg?v=1777355001&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/8595408-context_image-p1901879.jpg?v=1777355001&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/8595408-context_image-p1901879.jpg?v=1777355001&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Jackets</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 4;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/hiking-clothing" id="HeaderDrawer-all-sports-hiking-backpacking-hiking-clothing">
<img alt="Hiking Clothing" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/QUECHUA_POLAIRE_MH_BEIGE_500_F_-_8917597_8920370_-_206_---_Expires_on_11-12-2029.jpg?v=1777356925&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/QUECHUA_POLAIRE_MH_BEIGE_500_F_-_8917597_8920370_-_206_---_Expires_on_11-12-2029.jpg?v=1777356925&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/QUECHUA_POLAIRE_MH_BEIGE_500_F_-_8917597_8920370_-_206_---_Expires_on_11-12-2029.jpg?v=1777356925&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Hiking Clothing</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 5;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/base-layers-thermal-underwear" id="HeaderDrawer-all-sports-hiking-backpacking-base-layers">
<img alt="Base Layers &amp; Thermal Underwear" class="menu-drawer__link-image" height="533" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/WEDZE_BL_SKI_500_TIMELESS_HAUT_H_NOIR_AH23_-_8759460_-_076_---_Expires_on_13-04-2027_dca3729d-78cf-42d6-8445-47fbd3de0e9b.jpg?v=1777385304&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/WEDZE_BL_SKI_500_TIMELESS_HAUT_H_NOIR_AH23_-_8759460_-_076_---_Expires_on_13-04-2027_dca3729d-78cf-42d6-8445-47fbd3de0e9b.jpg?v=1777385304&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/WEDZE_BL_SKI_500_TIMELESS_HAUT_H_NOIR_AH23_-_8759460_-_076_---_Expires_on_13-04-2027_dca3729d-78cf-42d6-8445-47fbd3de0e9b.jpg?v=1777385304&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Base Layers</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 6;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/footwear" id="HeaderDrawer-all-sports-hiking-backpacking-footwear">
<img alt="" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/files/QUECHUA_MH500_LIGHT_H_SS25_-_8917985_-_003_---_Expires_on_13-01-2034.jpg?v=1746491081&amp;width=800" srcset="//www.decathlon.com/cdn/shop/files/QUECHUA_MH500_LIGHT_H_SS25_-_8917985_-_003_---_Expires_on_13-01-2034.jpg?v=1746491081&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/QUECHUA_MH500_LIGHT_H_SS25_-_8917985_-_003_---_Expires_on_13-01-2034.jpg?v=1746491081&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Footwear</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 7;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/hiking-camp-accessories" id="HeaderDrawer-all-sports-hiking-backpacking-hiking-poles">
<img alt="Kiprun 3-piece Carbon Folding Trail Running Poles" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/files/8858208-default_b7b3231b-979e-4390-a820-29c6a6c4caca.jpg?v=1774270200&amp;width=800" srcset="//www.decathlon.com/cdn/shop/files/8858208-default_b7b3231b-979e-4390-a820-29c6a6c4caca.jpg?v=1774270200&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858208-default_b7b3231b-979e-4390-a820-29c6a6c4caca.jpg?v=1774270200&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Hiking Poles</span>
</a>
</li></ul>
</details>
</accordion-custom>
</li><li class="menu-drawer__list-item menu-drawer__list-item--deep menu-drawer__list-item--divider">
<accordion-custom>
<details id="Details-menu-drawer-all-sports-camping">
<summary class="menu-drawer__menu-item menu-drawer__menu-item--parent focus-inset" id="HeaderDrawer-all-sports-camping">
<span class="menu-drawer__menu-item-text wrap-text">Camping</span>
<span class="svg-wrapper icon-plus"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
<path class="vertical" d="M2.75 7H11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
<path class="horizontal" d="M7 2.75L7 11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
</svg>
</span>
</summary>
<ul class="menu-drawer__menu menu-drawer__menu--grandchildlist details-content menu-drawer__menu--grid" role="list" tabindex="-1"><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 1;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/camp-ready-all-your-outdoor-essentials" id="HeaderDrawer-all-sports-camping-all-camping">
<img alt="Camping" class="menu-drawer__link-image" height="600" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/QUECHUA_2_SECONDS_FB_2P_-_8801560_-_099_---_Expires_on_01-03-2028_e8706c48-03ee-43ee-9f24-563182996765.jpg?v=1759928388&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/QUECHUA_2_SECONDS_FB_2P_-_8801560_-_099_---_Expires_on_01-03-2028_e8706c48-03ee-43ee-9f24-563182996765.jpg?v=1759928388&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/QUECHUA_2_SECONDS_FB_2P_-_8801560_-_099_---_Expires_on_01-03-2028_e8706c48-03ee-43ee-9f24-563182996765.jpg?v=1759928388&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">All Camping</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 2;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/camping-tents" id="HeaderDrawer-all-sports-camping-tents">
<img alt="Camping Tents" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/24-App-Collections-08.jpg?v=1777358562&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/24-App-Collections-08.jpg?v=1777358562&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/24-App-Collections-08.jpg?v=1777358562&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Tents</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 3;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/sleeping" id="HeaderDrawer-all-sports-camping-sleeping-bags-pads">
<img alt="Camping Sleeping Gear" class="menu-drawer__link-image" height="640" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/Untitled_design_18.jpg?v=1777396892&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/Untitled_design_18.jpg?v=1777396892&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/Untitled_design_18.jpg?v=1777396892&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Sleeping Bags &amp; Pads</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 4;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/kitchen" id="HeaderDrawer-all-sports-camping-camp-kitchen">
<img alt="Camp Kitchen" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/POPOTE_500_2P_VERTE_-_8901656_-_006_---_Expires_on_30-12-2033.jpg?v=1777362549&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/POPOTE_500_2P_VERTE_-_8901656_-_006_---_Expires_on_30-12-2033.jpg?v=1777362549&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/POPOTE_500_2P_VERTE_-_8901656_-_006_---_Expires_on_30-12-2033.jpg?v=1777362549&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Camp Kitchen</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 5;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/camp-furniture" id="HeaderDrawer-all-sports-camping-camp-chairs">
<img alt="Camp Furniture" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/Untitled_design_15.jpg?v=1777362588&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/Untitled_design_15.jpg?v=1777362588&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/Untitled_design_15.jpg?v=1777362588&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Camp Chairs</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 6;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/hydration" id="HeaderDrawer-all-sports-camping-hydration">
<img alt="Hydration" class="menu-drawer__link-image" height="533" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/MOUNTAIN_HIKING_CAMP_PE20_-_8207355_8554868_8554867_8574755_-_125_---_Expires_on_02-05-2030.jpg?v=1777397235&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/MOUNTAIN_HIKING_CAMP_PE20_-_8207355_8554868_8554867_8574755_-_125_---_Expires_on_02-05-2030.jpg?v=1777397235&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/MOUNTAIN_HIKING_CAMP_PE20_-_8207355_8554868_8554867_8574755_-_125_---_Expires_on_02-05-2030.jpg?v=1777397235&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Hydration</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 7;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/lighting" id="HeaderDrawer-all-sports-camping-lighting">
<img alt="Lighting" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/8600660-product_image-p2497872.jpg?v=1777363504&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/8600660-product_image-p2497872.jpg?v=1777363504&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/8600660-product_image-p2497872.jpg?v=1777363504&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Lighting</span>
</a>
</li></ul>
</details>
</accordion-custom>
</li><li class="menu-drawer__list-item menu-drawer__list-item--deep menu-drawer__list-item--divider">
<accordion-custom>
<details id="Details-menu-drawer-all-sports-running">
<summary class="menu-drawer__menu-item menu-drawer__menu-item--parent focus-inset" id="HeaderDrawer-all-sports-running">
<span class="menu-drawer__menu-item-text wrap-text">Running</span>
<span class="svg-wrapper icon-plus"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
<path class="vertical" d="M2.75 7H11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
<path class="horizontal" d="M7 2.75L7 11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
</svg>
</span>
</summary>
<ul class="menu-drawer__menu menu-drawer__menu--grandchildlist details-content menu-drawer__menu--grid" role="list" tabindex="-1"><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 1;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/running" id="HeaderDrawer-all-sports-running-all-running">
<img alt="Running" class="menu-drawer__link-image" height="533" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/KIPRUN_TANK_RACER_PREMIUM_SS24_PE24_-_8841302_8841309_8801426_8817440_8553331_8801428_8488395_8817446_8831031_8831040_8756320_8841245_8817439_8751038_-_005_---_Expires_on_15-11-2027.jpg?v=1759928515&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/KIPRUN_TANK_RACER_PREMIUM_SS24_PE24_-_8841302_8841309_8801426_8817440_8553331_8801428_8488395_8817446_8831031_8831040_8756320_8841245_8817439_8751038_-_005_---_Expires_on_15-11-2027.jpg?v=1759928515&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/KIPRUN_TANK_RACER_PREMIUM_SS24_PE24_-_8841302_8841309_8801426_8817440_8553331_8801428_8488395_8817446_8831031_8831040_8756320_8841245_8817439_8751038_-_005_---_Expires_on_15-11-2027.jpg?v=1759928515&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">All Running</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 2;">
<a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/kiprun-shoes" id="HeaderDrawer-all-sports-running-shoes">
<img alt="Kiprun Shoes" class="menu-drawer__link-image" height="640" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/KIPRUN_TS_RUN_500_F_CONFORT_BLEU_F20A_PE26_-_8968567_8969730_8960649_-_005_---_Expires_on_17-10-2029.jpg?v=1777397860&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/KIPRUN_TS_RUN_500_F_CONFORT_BLEU_F20A_PE26_-_8968567_8969730_8960649_-_005_---_Expires_on_17-10-2029.jpg?v=1777397860&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/KIPRUN_TS_RUN_500_F_CONFORT_BLEU_F20A_PE26_-_8968567_8969730_8960649_-_005_---_Expires_on_17-10-2029.jpg?v=1777397860&amp;width=800 800w" width="800"/>
<span class="menu-drawer__menu-item-text wrap-text">Shoes</span>
</a>
</li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 3;">

#### Creating a DataFrame with the data

Instead of getting names and prices separately, we can target the whole component, and extract the name and price from each item in a more structured manner. By targeting this whole component tag, we can ensure that we are extracting information for the same product (i.e., the name and price correspond to the same bicycle).

Here's how we can achieve this:

1. **Targeting the Whole Component**:
   - Instead of targeting individual tags for names and prices, we target the main component that contains both the name and price.
   - By visually inspecting the HTML, we can see that:
       - The information for each item (name, price, etc.) is grouped together under a `<product-card>` tag.
       - The `class` attribute of this `<product-card>` tag is `product-card size-style`. This class seemed specific to the product tile and thus, a good candidate to use for extraction.
   
2. **Iterating through Components**:
   - For each such component, extract the name and the price.
   
3. **Storing Data**:
   - We have two options:
     * Store all the information about each single item inside a dictionary. Then create a list of dictionaries
     * Store the extracted data in lists, which can then be used to create a DataFrame.

In [112]:
import pandas as pd

# Lists to store extracted data
item_names = []
sale_prices = []
regular_prices = []
urls = []

# Find all components
components = soup.find_all('product-card', class_="product-card size-style")


for component in components:
    # Extract item name
    #component
    # "visually-hidden" -- text meant for screen readers, not visible on the page, but it's
    # the cleanest place to grab the plain product name from (no extra markup/whitespace around it)
    name = component.find('span', class_="visually-hidden").text.strip()
    item_names.append(name)

    # Extract prices
    price = re.sub(r'\n+\s+', ' ',component.find('product-price').text.strip()).split()
    sale_prices.append(price[0])
    regular_prices.append(price[3])

    # Urls
    relative_url = component.find("a")["href"]
    full_url = url + relative_url
    urls.append(full_url)

# Create DataFrame
df = pd.DataFrame({
    'Item_Name': item_names,
    'Sale_Price': sale_prices,
    'Regular_Price': regular_prices,
    'Url': urls
})

df

,Item_Name,Sale_Price,Regular_Price,Url
0,Simond Men's MT100 Hooded Down Puffer Jacket,$119.00,$119.00,https://www.decathlon.com/collections/camp-hik...
1,Simond Women's MT100 Hooded Down Puffer Jacket,$119.00,$119.00,https://www.decathlon.com/collections/camp-hik...
2,Quechua Men's MH100 Hiking Fleece,$24.99,$24.99,https://www.decathlon.com/collections/camp-hik...
3,Quechua Women's MH120 Fleece Jacket,$34.99,$34.99,https://www.decathlon.com/collections/camp-hik...
4,Quechua 2 Second Fresh & Black Waterproof Pop ...,$179.00,$179.00,https://www.decathlon.com/collections/camp-hik...
5,Quechua NH100 Arpenaz 10 L Hiking Backpack,$9.99,$9.99,https://www.decathlon.com/collections/camp-hik...
6,Quechua NH50 Arpenaz 10 L Hiking Backpack,$5.99,$5.99,https://www.decathlon.com/collections/camp-hik...
7,Simond Men's MT100 Easyfit 70L Backpacking Pack,$129.00,$129.00,https://www.decathlon.com/collections/camp-hik...
8,Simond 500 Extend 40-60 L Duffel Bag,$99.99,$99.99,https://www.decathlon.com/collections/camp-hik...
9,Simond 500 Extend 30-40 L Duffel Bag,$79.99,$79.99,https://www.decathlon.com/collections/camp-hik...
10,Forclaz Men's MT100 Hooded Synthetic Jacket,$69.99,$69.99,https://www.decathlon.com/collections/camp-hik...
11,Forclaz Women's MT100 Hooded Synthetic Jacket,$40.00,$40.00,https://www.decathlon.com/collections/camp-hik...
12,Quechua NH500 Escape Rolltop 23 L Backpack,$59.99,$59.99,https://www.decathlon.com/collections/camp-hik...
13,Quechua NH500 Escape 23 L Hiking Backpack,$54.99,$54.99,https://www.decathlon.com/collections/camp-hik...
14,Simond Adult MT500 Merino Wool Beanie,$17.00,$17.00,https://www.decathlon.com/collections/camp-hik...
15,Simond Men's Travel 500 Merino Wool T-Shirt,$44.99,$44.99,https://www.decathlon.com/collections/camp-hik...
16,Forclaz ONNIGHT 100 Battery-Powered 80 Lumens ...,$14.99,$14.99,https://www.decathlon.com/collections/camp-hik...
17,Wedze Kids' BL100 Thermal Ski Base Layer Top,$9.99,$9.99,https://www.decathlon.com/collections/camp-hik...
18,Quechua Men's SH100 U-Warm Waterproof Snow Boots,$40.00,$40.00,https://www.decathlon.com/collections/camp-hik...
19,Quechua Women's MH100 T-Shirt,$5.00,$5.00,https://www.decathlon.com/collections/camp-hik...
20,Quechua NH100 Arpenaz 20 L Hiking Backpack,$19.99,$19.99,https://www.decathlon.com/collections/camp-hik...
21,Wedze Kids' BL100 Thermal Ski Base Layer Bottom,$9.99,$9.99,https://www.decathlon.com/collections/camp-hik...
22,Simond Men's MT500 Down Puffer Jacket,$149.00,$149.00,https://www.decathlon.com/collections/camp-hik...
23,Quechua 2 Second Easy Fresh & Black Waterproof...,$249.00,$249.00,https://www.decathlon.com/collections/camp-hik...

We could further clean our dataset to ensure the price is a float, facilitating arithmetic operations. This implies prices shouldn't be in a range.

#### 💡 Check for understanding

You are given a raw HTML content of a product list from an online store. Your task is to extract the following details for each product:

- Item Name
- Item Regular Price
- Item Sale Price
- URL for the product details

Write a function extract_bike_info that takes in the HTML content and returns a pandas DataFrame with the above columns.

**Hint:**

In order to get the product image, it might be a good idea to use the `article` tag with the class `de-ProductTile` since based on the HTML structure, this `article` tag encapsulates the entire product, including both the image and the product details. This allows us to more easily access all the relevant details for each product without having to jump around different sections.

If we were to only use `soup.find_all('section', class_='de-ProductTile-info')`, we'd be focusing solely on the product details section and would then need a separate approach to extract the image URL. By starting with the `article` tag, we're able to extract all the needed data in a more cohesive and streamlined manner.

**Bonus:** clean the price column so you can make numerical operations.

In [120]:
def extract_item_info(soup):

    # Lists to store extracted data
    item_names = []
    sale_prices = []
    regular_prices = []
    urls = []

    # Find all components
    components = soup.find_all('product-card', class_="product-card size-style")


    for component in components:
        # Extract item name
        #component
        name = component.find('span', class_="visually-hidden").text.strip()
        item_names.append(name)

        # Extract prices
        price = re.sub(r'\n+\s+', ' ',component.find('product-price').text.strip()).split()
        sale_prices.append(price[0])
        regular_prices.append(price[3])

        # Urls
        relative_url = component.find("a")["href"]
        full_url = url + relative_url
        urls.append(full_url)

    # Create DataFrame
    df = pd.DataFrame({
        'Item_Name': item_names,
        'Sale_Price': sale_prices,
        'Regular_Price': regular_prices,
        'Url': urls
    })


    return df

In [124]:
df = extract_item_info(soup)
df

,Item_Name,Sale_Price,Regular_Price,Url
0,Simond Men's MT100 Hooded Down Puffer Jacket,$119.00,$119.00,https://www.decathlon.com/collections/camp-hik...
1,Simond Women's MT100 Hooded Down Puffer Jacket,$119.00,$119.00,https://www.decathlon.com/collections/camp-hik...
2,Quechua Men's MH100 Hiking Fleece,$24.99,$24.99,https://www.decathlon.com/collections/camp-hik...
3,Quechua Women's MH120 Fleece Jacket,$34.99,$34.99,https://www.decathlon.com/collections/camp-hik...
4,Quechua 2 Second Fresh & Black Waterproof Pop ...,$179.00,$179.00,https://www.decathlon.com/collections/camp-hik...
5,Quechua NH100 Arpenaz 10 L Hiking Backpack,$9.99,$9.99,https://www.decathlon.com/collections/camp-hik...
6,Quechua NH50 Arpenaz 10 L Hiking Backpack,$5.99,$5.99,https://www.decathlon.com/collections/camp-hik...
7,Simond Men's MT100 Easyfit 70L Backpacking Pack,$129.00,$129.00,https://www.decathlon.com/collections/camp-hik...
8,Simond 500 Extend 40-60 L Duffel Bag,$99.99,$99.99,https://www.decathlon.com/collections/camp-hik...
9,Simond 500 Extend 30-40 L Duffel Bag,$79.99,$79.99,https://www.decathlon.com/collections/camp-hik...
10,Forclaz Men's MT100 Hooded Synthetic Jacket,$69.99,$69.99,https://www.decathlon.com/collections/camp-hik...
11,Forclaz Women's MT100 Hooded Synthetic Jacket,$40.00,$40.00,https://www.decathlon.com/collections/camp-hik...
12,Quechua NH500 Escape Rolltop 23 L Backpack,$59.99,$59.99,https://www.decathlon.com/collections/camp-hik...
13,Quechua NH500 Escape 23 L Hiking Backpack,$54.99,$54.99,https://www.decathlon.com/collections/camp-hik...
14,Simond Adult MT500 Merino Wool Beanie,$17.00,$17.00,https://www.decathlon.com/collections/camp-hik...
15,Simond Men's Travel 500 Merino Wool T-Shirt,$44.99,$44.99,https://www.decathlon.com/collections/camp-hik...
16,Forclaz ONNIGHT 100 Battery-Powered 80 Lumens ...,$14.99,$14.99,https://www.decathlon.com/collections/camp-hik...
17,Wedze Kids' BL100 Thermal Ski Base Layer Top,$9.99,$9.99,https://www.decathlon.com/collections/camp-hik...
18,Quechua Men's SH100 U-Warm Waterproof Snow Boots,$40.00,$40.00,https://www.decathlon.com/collections/camp-hik...
19,Quechua Women's MH100 T-Shirt,$5.00,$5.00,https://www.decathlon.com/collections/camp-hik...
20,Quechua NH100 Arpenaz 20 L Hiking Backpack,$19.99,$19.99,https://www.decathlon.com/collections/camp-hik...
21,Wedze Kids' BL100 Thermal Ski Base Layer Bottom,$9.99,$9.99,https://www.decathlon.com/collections/camp-hik...
22,Simond Men's MT500 Down Puffer Jacket,$149.00,$149.00,https://www.decathlon.com/collections/camp-hik...
23,Quechua 2 Second Easy Fresh & Black Waterproof...,$249.00,$249.00,https://www.decathlon.com/collections/camp-hik...

#### Scraping many pages

When dealing with a limited number of bicycles, all products are conveniently displayed on a single page. But what if there were numerous products necessitating pagination across multiple pages?

Consider the 'deals' collection. By navigating to the end of its first page on the website, we can observe pagination links. Transitioning to the second page results in a change in the URL:

From:
"https://www.decathlon.com/collections/camp-hike"
To:
"https://www.decathlon.com/collections/camp-hike?page=2"

This pattern in the URL can be leveraged to generate a series of URLs for web scraping.

Please note: Depending on the current offers available at the time of this lesson, pagination might not be present. If that's the case, explore other product categories that have a substantial number of items, resulting in multiple pages.

In [ ]:
"https://www.decathlon.com/collections/camp-hike?page=2"
"https://www.decathlon.com/collections/camp-hike?page=3"

In [122]:
pages = [f"https://www.decathlon.com/collections/camp-hike?page={pag}" for pag in range(1,int(308/25)+1)]

In [123]:
pages

['https://www.decathlon.com/collections/camp-hike?page=1',
 'https://www.decathlon.com/collections/camp-hike?page=2',
 'https://www.decathlon.com/collections/camp-hike?page=3',
 'https://www.decathlon.com/collections/camp-hike?page=4',
 'https://www.decathlon.com/collections/camp-hike?page=5',
 'https://www.decathlon.com/collections/camp-hike?page=6',
 'https://www.decathlon.com/collections/camp-hike?page=7',
 'https://www.decathlon.com/collections/camp-hike?page=8',
 'https://www.decathlon.com/collections/camp-hike?page=9',
 'https://www.decathlon.com/collections/camp-hike?page=10',
 'https://www.decathlon.com/collections/camp-hike?page=11',
 'https://www.decathlon.com/collections/camp-hike?page=12']

In [125]:
def get_df_from_url(url):

    response = requests.get(url)

    soup = BeautifulSoup(response.content, 'html.parser')

    df = extract_item_info(soup)

    return df

In [127]:
dfs = [get_df_from_url(page) for page in pages]

In [128]:
dfs[1]

,Item_Name,Sale_Price,Regular_Price,Url
0,Wedze Men's BL100 Base Layer Top,$12.99,$12.99,https://www.decathlon.com/collections/camp-hik...
1,Men's SH100 Warm Waterproof Snow Boots,$25.00,$25.00,https://www.decathlon.com/collections/camp-hik...
2,Wedze Men's BL100 Ski Base Layer Bottoms,$12.99,$12.99,https://www.decathlon.com/collections/camp-hik...
3,Forclaz Trek Pad Outdoor Foam Seat,$14.99,$14.99,https://www.decathlon.com/collections/camp-hik...
4,Simond Men's MT100 Easyfit 50 L Backpacking Pack,$109.00,$109.00,https://www.decathlon.com/collections/camp-hik...
5,Forclaz Travel 500 Organizer 40 L Backpack,$99.99,$99.99,https://www.decathlon.com/collections/camp-hik...
6,Quechua Women's MH100 Hiking Fleece,$17.00,$17.00,https://www.decathlon.com/collections/camp-hik...
7,Quechua NH500 Escape 32 L Hiking Backpack,$69.99,$69.99,https://www.decathlon.com/collections/camp-hik...
8,Quechua Stainless steel non-stick camping cook...,$69.99,$69.99,https://www.decathlon.com/collections/camp-hik...
9,Forclaz MT100 Foam Sleeping Pad,$24.99,$24.99,https://www.decathlon.com/collections/camp-hik...
10,Simond Men's MT500 Hooded Down Puffer Jacket,$179.00,$179.00,https://www.decathlon.com/collections/camp-hik...
11,Simond Women's Travel 500 Merino Wool T-Shirt,$44.99,$44.99,https://www.decathlon.com/collections/camp-hik...
12,Forclaz MT100 Fleece Gloves,$7.99,$7.99,https://www.decathlon.com/collections/camp-hik...
13,Quechua Women's Raincut Waterproof Over-Pants,$29.99,$29.99,https://www.decathlon.com/collections/camp-hik...
14,Wedze Women's BL100 Thermal Base Layer Top,$12.99,$12.99,https://www.decathlon.com/collections/camp-hik...
15,Simond Men's MT500 Merino Wool Boxer Briefs,$34.99,$34.99,https://www.decathlon.com/collections/camp-hik...
16,Forclaz Women's MT100 2-in-1 Zip-Off Hiking Pants,$59.99,$59.99,https://www.decathlon.com/collections/camp-hik...
17,Quechua Women's NH500 Hiking Skort,$25.00,$25.00,https://www.decathlon.com/collections/camp-hik...
18,Simond 500 Extend 80-120 L Duffel Bag,$129.00,$129.00,https://www.decathlon.com/collections/camp-hik...
19,Forclaz MT500 Lightweight Packable Hiking Sandals,$40.00,$40.00,https://www.decathlon.com/collections/camp-hik...
20,Quechua Men's MH100 Waterproof Mid Hiking Boots,$89.99,$89.99,https://www.decathlon.com/collections/camp-hik...
21,Forclaz Men's Travel 100 Cargo Pants,$59.99,$59.99,https://www.decathlon.com/collections/camp-hik...
22,Quechua Men's MH120 Fleece Hiking Jacket,$24.00,$24.00,https://www.decathlon.com/collections/camp-hik...
23,Quechua Hike 50 High Socks 2-Pack,$9.99,$9.99,https://www.decathlon.com/collections/camp-hik...

In [129]:
# Concatenate all DataFrames in the list
result_df = pd.concat(dfs, ignore_index=True)
result_df

,Item_Name,Sale_Price,Regular_Price,Url
0,Simond Men's MT100 Hooded Down Puffer Jacket,$119.00,$119.00,https://www.decathlon.com/collections/camp-hik...
1,Simond Women's MT100 Hooded Down Puffer Jacket,$119.00,$119.00,https://www.decathlon.com/collections/camp-hik...
2,Quechua Men's MH100 Hiking Fleece,$24.99,$24.99,https://www.decathlon.com/collections/camp-hik...
3,Quechua Women's MH120 Fleece Jacket,$34.99,$34.99,https://www.decathlon.com/collections/camp-hik...
4,Quechua 2 Second Fresh & Black Waterproof Pop ...,$179.00,$179.00,https://www.decathlon.com/collections/camp-hik...
...,...,...,...,...
283,Ultra Compact Swimming Microfiber towel - XL 1...,$24.99,$24.99,https://www.decathlon.com/collections/camp-hik...
284,SIMOND Men's Travel 500 Merino Wool T-Shirt,$49.99,$49.99,https://www.decathlon.com/collections/camp-hik...
285,SIMOND Women's Travel 500 Merino Wool T-Shirt,$49.99,$49.99,https://www.decathlon.com/collections/camp-hik...
286,Ultra Compact Swimming Microfiber towel - XL 1...,$24.99,$24.99,https://www.decathlon.com/collections/camp-hik...
287,Ultra Compact Swimming Microfiber towel - XL 1...,$24.99,$24.99,https://www.decathlon.com/collections/camp-hik...

If you look at our results, and compare it with the website, you'll see that its not returning all the products. Each page has more than 9 products, and its only returning 9 on each page.

This could be because the content is dynamic.

**Dynamic Content**: Many modern websites use JavaScript to load content dynamically. When you make a request using libraries like requests, you only retrieve the initial HTML content. Content loaded dynamically via JavaScript after this won't be captured. In such cases, tools like Selenium are used because they can interact with the JavaScript of the page.

#### CSS selectors

CSS selectors are patterns used to select and manipulate one or more elements in an HTML or XML document. When web scraping with Python, CSS selectors can be used to target specific elements of interest within the page's content.

The `select` method in BeautifulSoup allows you to pass a CSS selector and returns a list of elements matching that selector.

1. **Tag Selector**: Targets elements by their tag name.
   - `p`: selects all `<p>` elements.
   - `soup.select("p")` will retrieve all `<p>` elements

2. **Class Selector**: Targets elements by their class attribute.
   - `.classname`: selects all elements with `class="classname"`.
   - If class name has spaces, they must be changed by `.`
   - `soup.select(".classname")`
   - To combine both, we can have `soup.select("tagname.classname")`

3. **Descendant Selector**: Targets an element that is a descendant of another element.
   - `div p`: selects all `<p>` elements inside a `<div>` element.
   - `.class1 .class2`: selects all elements with class2 that is a descendant of an element with class1.
   
4. **Attribute Selector**: Targets elements based on their attributes and values.
   - `a[href]`: selects all `<a>` elements with an `href` attribute.
   - `a[href="https://www.example.com"]`: selects all `<a>` elements with an `href` value of "https://www.example.com".

And more...

1. **Tag Selector**:
   - **`li`**: This would select all `<li>` elements on the page.

In [136]:
soup.select("li")

[<li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 1;"><details class="menu-drawer__menu-container menu-drawer__menu-container--divider" id="Details-menu-drawer-menu-item-1">
 <summary class="menu-drawer__menu-item menu-drawer__menu-item--mainlist menu-drawer__animated-element focus-inset menu-drawer__menu-item--active" id="HeaderDrawer-all-sports" on:click="header-drawer/open/submenu">
 <span class="menu-drawer__menu-item-text wrap-text">All Sports</span>
 <span class="svg-wrapper icon-caret icon-caret--forward"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
 <path d="M11 5.5L7 9.5L3 5.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 </span>
 </summary>
 <div class="menu-drawer__submenu has-submenu" id="link-all-sports" style="--menu-drawer-animation-index: 1;" tabindex="-1">
 <div class="menu-drawer__inner-submenu">
 <div class="menu-drawer__nav-buttons">
 <button aria-label="Back to All Sports" class="button menu-drawer__back-button focus-inset" on:click="header-drawer/back">
 <span class="svg-wrapper icon-caret icon-caret--backward"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
 <path d="M11 5.5L7 9.5L3 5.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 </span>
 <span class="menu-drawer__menu-item-text wrap-text">All Sports</span>
 </button>
 <button aria-label="Close" class="button button-unstyled close-button menu-drawer__close-button" on:click="header-drawer/close" type="button">
 <span class="svg-wrapper header-drawer-icon header-drawer-icon--close"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
 <path d="M12 2L2 12" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 <path d="M12 12L2 2" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 </span>
 </button>
 </div>
 <ul class="menu-drawer__menu menu-drawer__menu--childlist" role="list" tabindex="-1">
 <li class="menu-drawer__list-item menu-drawer__list-item--deep menu-drawer__list-item--divider">
 <accordion-custom>
 <details id="Details-menu-drawer-all-sports-hiking-backpacking">
 <summary class="menu-drawer__menu-item menu-drawer__menu-item--parent focus-inset" id="HeaderDrawer-all-sports-hiking-backpacking">
 <span class="menu-drawer__menu-item-text wrap-text">Hiking &amp; Backpacking</span>
 <span class="svg-wrapper icon-plus"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
 <path class="vertical" d="M2.75 7H11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
 <path class="horizontal" d="M7 2.75L7 11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 </span>
 </summary>
 <ul class="menu-drawer__menu menu-drawer__menu--grandchildlist details-content menu-drawer__menu--grid" role="list" tabindex="-1"><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 1;">
 <a aria-current="page" class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset menu-drawer__menu-item--active" href="/collections/camp-hike" id="HeaderDrawer-all-sports-hiking-backpacking-all-hiking-backpacking">
 <img alt="Hiking &amp; Backpacking" class="menu-drawer__link-image" height="533" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/Collections-Herobanner-Camp-_-hike.jpg?v=1759928429&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/Collections-Herobanner-Camp-_-hike.jpg?v=1759928429&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/Collections-Herobanner-Camp-_-hike.jpg?v=1759928429&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">All Hiking &amp; Backpacking</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 2;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/backpacks-bags" id="HeaderDrawer-all-sports-hiking-backpacking-bags-backpacks">
 <img alt="Bags &amp; Backpacks" class="menu-drawer__link-image" height="533" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/QUECHUA_SAC_A_DOS_NH_ESCAPE_500_ROLLTOP_23L_JAUN_SS25_-_8736386_8787846_8803959_8803962_8826782_8871194_8920375_-_181_---_Expires_on_13-12-2028.jpg?v=1776978555&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/QUECHUA_SAC_A_DOS_NH_ESCAPE_500_ROLLTOP_23L_JAUN_SS25_-_8736386_8787846_8803959_8803962_8826782_8871194_8920375_-_181_---_Expires_on_13-12-2028.jpg?v=1776978555&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/QUECHUA_SAC_A_DOS_NH_ESCAPE_500_ROLLTOP_23L_JAUN_SS25_-_8736386_8787846_8803959_8803962_8826782_8871194_8920375_-_181_---_Expires_on_13-12-2028.jpg?v=1776978555&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Bags &amp; Backpacks</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 3;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/hiking-jackets" id="HeaderDrawer-all-sports-hiking-backpacking-jackets">
 <img alt="Hiking Jackets" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/8595408-context_image-p1901879.jpg?v=1777355001&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/8595408-context_image-p1901879.jpg?v=1777355001&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/8595408-context_image-p1901879.jpg?v=1777355001&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Jackets</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 4;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/hiking-clothing" id="HeaderDrawer-all-sports-hiking-backpacking-hiking-clothing">
 <img alt="Hiking Clothing" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/QUECHUA_POLAIRE_MH_BEIGE_500_F_-_8917597_8920370_-_206_---_Expires_on_11-12-2029.jpg?v=1777356925&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/QUECHUA_POLAIRE_MH_BEIGE_500_F_-_8917597_8920370_-_206_---_Expires_on_11-12-2029.jpg?v=1777356925&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/QUECHUA_POLAIRE_MH_BEIGE_500_F_-_8917597_8920370_-_206_---_Expires_on_11-12-2029.jpg?v=1777356925&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Hiking Clothing</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 5;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/base-layers-thermal-underwear" id="HeaderDrawer-all-sports-hiking-backpacking-base-layers">
 <img alt="Base Layers &amp; Thermal Underwear" class="menu-drawer__link-image" height="533" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/WEDZE_BL_SKI_500_TIMELESS_HAUT_H_NOIR_AH23_-_8759460_-_076_---_Expires_on_13-04-2027_dca3729d-78cf-42d6-8445-47fbd3de0e9b.jpg?v=1777385304&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/WEDZE_BL_SKI_500_TIMELESS_HAUT_H_NOIR_AH23_-_8759460_-_076_---_Expires_on_13-04-2027_dca3729d-78cf-42d6-8445-47fbd3de0e9b.jpg?v=1777385304&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/WEDZE_BL_SKI_500_TIMELESS_HAUT_H_NOIR_AH23_-_8759460_-_076_---_Expires_on_13-04-2027_dca3729d-78cf-42d6-8445-47fbd3de0e9b.jpg?v=1777385304&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Base Layers</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 6;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/footwear" id="HeaderDrawer-all-sports-hiking-backpacking-footwear">
 <img alt="" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/files/QUECHUA_MH500_LIGHT_H_SS25_-_8917985_-_003_---_Expires_on_13-01-2034.jpg?v=1746491081&amp;width=800" srcset="//www.decathlon.com/cdn/shop/files/QUECHUA_MH500_LIGHT_H_SS25_-_8917985_-_003_---_Expires_on_13-01-2034.jpg?v=1746491081&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/QUECHUA_MH500_LIGHT_H_SS25_-_8917985_-_003_---_Expires_on_13-01-2034.jpg?v=1746491081&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Footwear</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 7;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/hiking-camp-accessories" id="HeaderDrawer-all-sports-hiking-backpacking-hiking-poles">
 <img alt="Kiprun 3-piece Carbon Folding Trail Running Poles" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/files/8858208-default_b7b3231b-979e-4390-a820-29c6a6c4caca.jpg?v=1774270200&amp;width=800" srcset="//www.decathlon.com/cdn/shop/files/8858208-default_b7b3231b-979e-4390-a820-29c6a6c4caca.jpg?v=1774270200&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858208-default_b7b3231b-979e-4390-a820-29c6a6c4caca.jpg?v=1774270200&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Hiking Poles</span>
 </a>
 </li></ul>
 </details>
 </accordion-custom>
 </li><li class="menu-drawer__list-item menu-drawer__list-item--deep menu-drawer__list-item--divider">
 <accordion-custom>
 <details id="Details-menu-drawer-all-sports-camping">
 <summary class="menu-drawer__menu-item menu-drawer__menu-item--parent focus-inset" id="HeaderDrawer-all-sports-camping">
 <span class="menu-drawer__menu-item-text wrap-text">Camping</span>
 <span class="svg-wrapper icon-plus"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
 <path class="vertical" d="M2.75 7H11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
 <path class="horizontal" d="M7 2.75L7 11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 </span>
 </summary>
 <ul class="menu-drawer__menu menu-drawer__menu--grandchildlist details-content menu-drawer__menu--grid" role="list" tabindex="-1"><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 1;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/camp-ready-all-your-outdoor-essentials" id="HeaderDrawer-all-sports-camping-all-camping">
 <img alt="Camping" class="menu-drawer__link-image" height="600" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/QUECHUA_2_SECONDS_FB_2P_-_8801560_-_099_---_Expires_on_01-03-2028_e8706c48-03ee-43ee-9f24-563182996765.jpg?v=1759928388&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/QUECHUA_2_SECONDS_FB_2P_-_8801560_-_099_---_Expires_on_01-03-2028_e8706c48-03ee-43ee-9f24-563182996765.jpg?v=1759928388&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/QUECHUA_2_SECONDS_FB_2P_-_8801560_-_099_---_Expires_on_01-03-2028_e8706c48-03ee-43ee-9f24-563182996765.jpg?v=1759928388&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">All Camping</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 2;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/camping-tents" id="HeaderDrawer-all-sports-camping-tents">
 <img alt="Camping Tents" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/24-App-Collections-08.jpg?v=1777358562&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/24-App-Collections-08.jpg?v=1777358562&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/24-App-Collections-08.jpg?v=1777358562&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Tents</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 3;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/sleeping" id="HeaderDrawer-all-sports-camping-sleeping-bags-pads">
 <img alt="Camping Sleeping Gear" class="menu-drawer__link-image" height="640" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/Untitled_design_18.jpg?v=1777396892&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/Untitled_design_18.jpg?v=1777396892&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/Untitled_design_18.jpg?v=1777396892&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Sleeping Bags &amp; Pads</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 4;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/kitchen" id="HeaderDrawer-all-sports-camping-camp-kitchen">
 <img alt="Camp Kitchen" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/POPOTE_500_2P_VERTE_-_8901656_-_006_---_Expires_on_30-12-2033.jpg?v=1777362549&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/POPOTE_500_2P_VERTE_-_8901656_-_006_---_Expires_on_30-12-2033.jpg?v=1777362549&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/POPOTE_500_2P_VERTE_-_8901656_-_006_---_Expires_on_30-12-2033.jpg?v=1777362549&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Camp Kitchen</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 5;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/camp-furniture" id="HeaderDrawer-all-sports-camping-camp-chairs">
 <img alt="Camp Furniture" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/Untitled_design_15.jpg?v=1777362588&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/Untitled_design_15.jpg?v=1777362588&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/Untitled_design_15.jpg?v=1777362588&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Camp Chairs</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 6;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/hydration" id="HeaderDrawer-all-sports-camping-hydration">
 <img alt="Hydration" class="menu-drawer__link-image" height="533" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/MOUNTAIN_HIKING_CAMP_PE20_-_8207355_8554868_8554867_8574755_-_125_---_Expires_on_02-05-2030.jpg?v=1777397235&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/MOUNTAIN_HIKING_CAMP_PE20_-_8207355_8554868_8554867_8574755_-_125_---_Expires_on_02-05-2030.jpg?v=1777397235&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/MOUNTAIN_HIKING_CAMP_PE20_-_8207355_8554868_8554867_8574755_-_125_---_Expires_on_02-05-2030.jpg?v=1777397235&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Hydration</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 7;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/lighting" id="HeaderDrawer-all-sports-camping-lighting">
 <img alt="Lighting" class="menu-drawer__link-image" height="800" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/8600660-product_image-p2497872.jpg?v=1777363504&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/8600660-product_image-p2497872.jpg?v=1777363504&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/8600660-product_image-p2497872.jpg?v=1777363504&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Lighting</span>
 </a>
 </li></ul>
 </details>
 </accordion-custom>
 </li><li class="menu-drawer__list-item menu-drawer__list-item--deep menu-drawer__list-item--divider">
 <accordion-custom>
 <details id="Details-menu-drawer-all-sports-running">
 <summary class="menu-drawer__menu-item menu-drawer__menu-item--parent focus-inset" id="HeaderDrawer-all-sports-running">
 <span class="menu-drawer__menu-item-text wrap-text">Running</span>
 <span class="svg-wrapper icon-plus"><svg aria-hidden="true" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
 <path class="vertical" d="M2.75 7H11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
 <path class="horizontal" d="M7 2.75L7 11.25" stroke="currentColor" stroke-linecap="round" stroke-width="var(--icon-stroke-width)"></path>
 </svg>
 </span>
 </summary>
 <ul class="menu-drawer__menu menu-drawer__menu--grandchildlist details-content menu-drawer__menu--grid" role="list" tabindex="-1"><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 1;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/running" id="HeaderDrawer-all-sports-running-all-running">
 <img alt="Running" class="menu-drawer__link-image" height="533" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/KIPRUN_TANK_RACER_PREMIUM_SS24_PE24_-_8841302_8841309_8801426_8817440_8553331_8801428_8488395_8817446_8831031_8831040_8756320_8841245_8817439_8751038_-_005_---_Expires_on_15-11-2027.jpg?v=1759928515&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/KIPRUN_TANK_RACER_PREMIUM_SS24_PE24_-_8841302_8841309_8801426_8817440_8553331_8801428_8488395_8817446_8831031_8831040_8756320_8841245_8817439_8751038_-_005_---_Expires_on_15-11-2027.jpg?v=1759928515&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/KIPRUN_TANK_RACER_PREMIUM_SS24_PE24_-_8841302_8841309_8801426_8817440_8553331_8801428_8488395_8817446_8831031_8831040_8756320_8841245_8817439_8751038_-_005_---_Expires_on_15-11-2027.jpg?v=1759928515&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">All Running</span>
 </a>
 </li><li class="menu-drawer__list-item" style="--menu-drawer-animation-index: 2;">
 <a class="menu-drawer__menu-item menu-drawer__menu-item--child focus-inset" href="/collections/kiprun-shoes" id="HeaderDrawer-all-sports-running-shoes">
 <img alt="Kiprun Shoes" class="menu-drawer__link-image" height="640" loading="lazy" sizes="auto, 400px" src="//www.decathlon.com/cdn/shop/collections/KIPRUN_TS_RUN_500_F_CONFORT_BLEU_F20A_PE26_-_8968567_8969730_8960649_-_005_---_Expires_on_17-10-2029.jpg?v=1777397860&amp;width=800" srcset="//www.decathlon.com/cdn/shop/collections/KIPRUN_TS_RUN_500_F_CONFORT_BLEU_F20A_PE26_-_8968567_8969730_8960649_-_005_---_Expires_on_17-10-2029.jpg?v=1777397860&amp;width=352 352w, //www.decathlon.com/cdn/shop/collections/KIPRUN_TS_RUN_500_F_CONFORT_BLEU_F20A_PE26_-_8968567_8969730_8960649_-_005_---_Expires_on_17-10-2029.jpg?v=1777397860&amp;width=800 800w" width="800"/>
 <span class="menu-drawer__menu-item-text wrap-text">Shoes</span>
 </a>

2. **Class Selector**:
   - **`.product-grid__item`**: This would select all elements with the class `product-grid__item`.

In [140]:
soup.select("li.product-grid__item")

[<li class="product-grid__item product-grid__item--0" data-page="1" data-product-id="4417342308414" id="template--18434715222078__main-4417342308414" ref="cards[]">
 <style data-shopify="">
 </style>
 <product-card class="product-card size-style" data-product-id="4417342308414" id="product-card-AZk1wN2hFVFQ2ZmJCc__product-card" style="--size-style-width: ;--size-style-height: ;">
 <a class="product-card__link" href="/products/simond-mt100-hooded-down-puffer-jacket-167571?variant=41320423063614" id="36cefc935f0b0a254f317ab98f544407" ref="productCardLink">
 <span class="visually-hidden">
       Simond Men's MT100 Hooded Down Puffer Jacket
     </span>
 </a>
 <div class="product-card__content layout-panel-flex layout-panel-flex--column product-grid__card spacing-style border-style gap-style" style="
       --border-width: 1px; --border-style: none; --border-color:
 rgb(var(--color-border-rgb) / 1.0); --border-radius:
 0px;

       --flex-direction: column; --flex-wrap: nowrap; --flex-wrap-mobile: wrap;



 --horizontal-alignment: ; --vertical-alignment: ;
 --vertical-alignment-mobile: ;

       --padding-block-start: 0px;--padding-block-end: 0px;--padding-inline-start: 0px;--padding-inline-end: 0px;
       --product-card-gap: 4px;
       --quick-add-display: none;
       --quick-add-mobile-display: none;
       --quick-add-mobile-opacity: 0;




     ">
 <div class="card-gallery card-gallery-AODAvcVh6b3p1OG5zN__card-gallery spacing-style border-style" data-image-ratio="square" data-product-id="4417342308414" on:pointerenter="/previewImage" on:pointerleave="/resetImage" ref="cardGallery" style="
     --border-width: 1px; --border-style: none; --border-color:
 rgb(var(--color-border-rgb) / 1.0); --border-radius:
 0px;

     --padding-block-start: 0px;--padding-block-end: 0px;--padding-inline-start: 0px;--padding-inline-end: 0px;
     --gallery-aspect-ratio: 1;
   ">
 <a aria-label="Simond Men's MT100 Hooded Down Puffer Jacket" class="contents" href="/products/simond-mt100-hooded-down-puffer-jacket-167571?variant=41320423063614" ref="cardGalleryLink">
 <slideshow-component data-generic-media-size="37" disabled="true" infinite="" initial-slide="0" ref="slideshow" style="--slideshow-timeline: --slide-0, --slide-1, --slide-2, --slide-3, --slide-4, --slide-5, --slide-6, --slide-7, --slide-8, --slide-9, --slide-10, --slide-11, --slide-12, --slide-13, --slide-14, --slide-15, --slide-16, --slide-17, --slide-18, --slide-19, --slide-20, --slide-21, --slide-22, --slide-23, --slide-24, --slide-25, --slide-26, --slide-27, --slide-28, --slide-29, --slide-30, --slide-31, --slide-32, --slide-33, --slide-34, --slide-35, --slide-36, --slide-37, --slide-38, --slide-39, --slide-40;--slide-min-height: auto;--slide-min-height-desktop: auto;">
 <slideshow-container ref="slideshowContainer">
 <slideshow-arrows position="center"><button aria-label="Previous slide" class="slideshow-control slideshow-control--previous slideshow-control--style-arrow button button-unstyled button-unstyled--transparent flip-x" on:click="/previous" ref="previous">
 <span class="svg-wrapper icon-arrow"><svg aria-hidden="true" fill="none" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M4.25 10h11.5m0 0-4-4m4 4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)" vector-effect="non-scaling-stroke"></path></svg>
 </span>
 </button>
 <button aria-label="Next slide" class="slideshow-control slideshow-control--next slideshow-control--style-arrow button button-unstyled button-unstyled--transparent" on:click="/next" ref="next">
 <span class="svg-wrapper icon-arrow"><svg aria-hidden="true" fill="none" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M4.25 10h11.5m0 0-4-4m4 4-4 4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--icon-stroke-width)" vector-effect="non-scaling-stroke"></path></svg>
 </span>
 </button>
 </slideshow-arrows>
 <slideshow-slides ref="scroller" tabindex="-1">
 <slideshow-slide aria-hidden="false" class="product-media-container media-fit product-media-container--image" ref="slides[]" slide-id="24955728592958" style="--slideshow-timeline: --slide-0; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
 <div class="product-media" data-media-id="24955728592958" style="--ratio: 1.0">
 <img alt="{*asphalt-blue-8858286*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840" fetchpriority="auto" height="3840" loading="eager" sizes="(min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
 </div>
 </slideshow-slide>
 <slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" ref="slides[]" slide-id="24955730657342" style="--slideshow-timeline: --slide-1; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;">
 <div class="product-media" data-media-id="24955730657342" style="--ratio: 1.0">
 <img alt="{*asphalt-blue-8858286*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858286-product_image-p2690822_4c7f6558-591a-406d-b0ea-a1941de4299e.jpg?v=1755033808&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
 </div>
 </slideshow-slide>
 <slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="26172575580222" style="--slideshow-timeline: --slide-13; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
 <div class="product-media" data-media-id="26172575580222" style="--ratio: 1.0">
 <img alt="{*smoked-black-8858287*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
 </div>
 </slideshow-slide>
 <slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="24955734655038" style="--slideshow-timeline: --slide-20; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
 <div class="product-media" data-media-id="24955734655038" style="--ratio: 1.0">
 <img alt="{*olive-green-8595408*}" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
 </div>
 </slideshow-slide>
 <slideshow-slide aria-hidden="true" class="product-media-container media-fit product-media-container--image" hidden="" ref="slides[]" slide-id="26173860479038" style="--slideshow-timeline: --slide-33; --product-media-fit: cover; --grid-template-rows: 50dvh 1fr; --grid-template-rows-desktop: 70dvh 1fr;" variant-image="">
 <div class="product-media" data-media-id="26173860479038" style="--ratio: 1.0">
 <img alt="Simond Men's MT100 Hooded Down Puffer Jacket" class="product-media__image" data_max_resolution="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840" fetchpriority="auto" height="3840" loading="lazy" sizes="auto, (min-width: 1780px) 20vw, (min-width: 1424px) 25vw, (min-width: 1068px) 33vw, (min-width: 750px) 50vw, 100vw" src="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840" srcset="//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=240 240w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=352 352w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=832 832w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1200 1200w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1600 1600w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=1920 1920w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=2560 2560w, //www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=3840 3840w" style="--focal-point: 50.0% 50.0%;" width="3840"/>
 </div>
 </slideshow-slide>
 </slideshow-slides>
 </slideshow-container>
 </slideshow-component>
 </a>
 <div class="product-badges product-badges--top-right" style="
         --badge-border-radius: 100px;
         --badge-font-family: var(--font-body--family); --badge-font-weight: var(--font-body--weight); --badge-text-transform: none;
       "></div>
 </div>
 <div class="product-grid-view-zoom-out--details">
 <h3 class="h4">Simond Men's MT100 Hooded Down Puffer Jacket</h3>
 </div>
 <product-swatches data-product-id="4417342308414" data-product-url="/products/simond-mt100-hooded-down-puffer-jacket-167571" style="
       --overflow-list-alignment: flex-start;
       --overflow-list-alignment-mobile: flex-start;
       --product-swatches-alignment: start;
       --product-swatches-alignment-mobile: start;
       --product-swatches-padding-block-start: 0px;
       --product-swatches-padding-block-end: 0px;
       --product-swatches-padding-inline-start: 0px;
       --product-swatches-padding-inline-end: 0px;
     ">
 <swatches-variant-picker-component data-product-id="4417342308414" data-product-url="/products/simond-mt100-hooded-down-puffer-jacket-167571" ref="swatchesVariantPicker">
 <form>
 <fieldset class="variant-option variant-option--buttons variant-option--swatches">
 <overflow-list ref="overflowList">
 <template shadowrootmode="open">
 <link href="//www.decathlon.com/cdn/shop/t/374/assets/overflow-list.css?v=16727044177065489451775763283" media="all" rel="stylesheet" type="text/css">
 <ul part="list">
 <slot></slot>
 <slot hidden="" name="more" part="more">
 <li part="more">
 <button class="button" tabindex="0" type="button">
             More
           </button>
 </li>
 </slot>
 <li hidden="" part="placeholder"></li>
 </ul>
 <div part="overflow">
 <ul part="overflow-list">
 <slot name="overflow"></slot>
 </ul>
 </div>
 </link></template>
 <li class="variant-option__swatch">
 <label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="24955728592958" on:pointerenter="product-card/previewVariant/24955728592958" on:pointerleave="product-card/resetVariant">
 <input aria-label="Asphalt Blue" data-connected-product-url="" data-first-available-or-first-variant-id="41320423063614" data-input-id="1-0" data-option-available="true" data-option-media-id="24955728592958" data-option-value-id="2344181727294" data-variant-id="41320423063614" name="Color-4417342308414-swatch" type="radio" value="Asphalt Blue"/>
 <span class="swatch swatch--variant-image" style="
     --swatch-background: url(//www.decathlon.com/cdn/shop/files/8858286-product_image-p2688048_dea6fdbb-43f3-4b78-8e1b-94ab328aec0e.jpg?v=1755033808&amp;width=100);

   ">
 </span>
 </label>
 </li>
 <li class="variant-option__swatch">
 <label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="24955734655038" on:pointerenter="product-card/previewVariant/24955734655038" on:pointerleave="product-card/resetVariant">
 <input aria-label="Olive Green" data-connected-product-url="" data-first-available-or-first-variant-id="32494250295358" data-input-id="1-1" data-option-available="true" data-option-media-id="24955734655038" data-option-value-id="1454888255550" data-variant-id="32494250295358" name="Color-4417342308414-swatch" type="radio" value="Olive Green"/>
 <span class="swatch swatch--variant-image" style="
     --swatch-background: url(//www.decathlon.com/cdn/shop/files/8595408-product_image-p2549663.jpg?v=1776372060&amp;width=100);

   ">
 </span>
 </label>
 </li>
 <li class="variant-option__swatch">
 <label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="26173860479038" on:pointerenter="product-card/previewVariant/26173860479038" on:pointerleave="product-card/resetVariant">
 <input aria-label="Dark Sepia" data-connected-product-url="" data-first-available-or-first-variant-id="41912831344702" data-input-id="1-2" data-option-available="true" data-option-media-id="26173860479038" data-option-value-id="2875192705086" data-variant-id="41912831344702" name="Color-4417342308414-swatch" type="radio" value="Dark Sepia"/>
 <span class="swatch swatch--variant-image" style="
     --swatch-background: url(//www.decathlon.com/cdn/shop/files/8559957-product_image-p2688105.jpg?v=1755039960&amp;width=100);

   ">
 </span>
 </label>
 </li>
 <li class="variant-option__swatch">
 <label class="variant-option__button-label variant-option__button-label--has-swatch" data-media-id="26172575580222" on:pointerenter="product-card/previewVariant/26172575580222" on:pointerleave="product-card/resetVariant">
 <input aria-label="Smoked Black" data-connected-product-url="" data-first-available-or-first-variant-id="41912831148094" data-input-id="1-3" data-option-available="true" data-option-media-id="26172575580222" data-option-value-id="2875192672318" data-variant-id="41912831148094" name="Color-4417342308414-swatch" type="radio" value="Smoked Black"/>
 <span class="swatch swatch--variant-image" style="
     --swatch-background: url(//www.decathlon.com/cdn/shop/files/8858287-product_image-p2688083.jpg?v=1776372060&amp;width=100);

   ">
 </span>
 </label>
 </li><li slot="more">
 <button aria-label="Show all options" class="hidden-swatches__count" on:click="/showAllSwatches"></button>
 </li>
 </overflow-list>
 </fieldset>
 <script type="application/json">

To combine both, we can have `soup.select("tagname.classname")`

Using CSS selectors is quite convenient as we can specify a hierarchy of cards which was not possible with .find_all()

In [142]:

for item in soup.select("li > product-card > a"):
    # Product rating:
    print(item.text.replace("\n"," "))

        Simond Men's MT100 Hooded Down Puffer Jacket
        Simond Women's MT100 Hooded Down Puffer Jacket
        Quechua Men's MH100 Hiking Fleece
        Quechua Women's MH120 Fleece Jacket
        Quechua 2 Second Fresh & Black Waterproof Pop Up Camping Tent 3 Person
        Quechua NH100 Arpenaz 10 L Hiking Backpack
        Quechua NH50 Arpenaz 10 L Hiking Backpack
        Simond  Men's MT100 Easyfit 70L Backpacking Pack
        Simond 500 Extend 40-60 L Duffel Bag
        Simond 500 Extend 30-40 L Duffel Bag
        Forclaz Men's MT100 Hooded Synthetic Jacket
        Forclaz Women's MT100 Hooded Synthetic Jacket
        Quechua NH500 Escape Rolltop 23 L Backpack
        Quechua NH500 Escape 23 L Hiking Backpack
        Simond Adult MT500 Merino Wool Beanie
        Simond Men's Travel 500 Merino Wool T-Shirt
        Forclaz ONNIGHT 100 Battery-Powered 80 Lumens Hiking Head Lamp
        Wedze Kids' BL100 Thermal Ski Base Layer Top
        Quechua Men's SH100 U-Warm Waterproof Snow Boots
        Quechua Women's MH100 T-Shirt
        Quechua NH100 Arpenaz 20 L Hiking Backpack
        Wedze Kids' BL100 Thermal Ski Base Layer Bottom
        Simond Men's MT500 Down Puffer Jacket
        Quechua 2 Second Easy Fresh & Black Waterproof Pop Up Camping Tent 2 Person

Equivalently, using CSS selectors, which is a universal syntax, you can try and find `tag_name.class_name`. If class name has spaces, they must be changed by `.`

In [143]:
# Extracting all links within <a> tags and class 'de-u-linkClean js-de-ProductTile-link'
for link in soup.select('product-card.product-card.size-style'):
    print(link.get('id'))

product-card-AZk1wN2hFVFQ2ZmJCc__product-card
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-1
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-2
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-3
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-4
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-5
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-6
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-7
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-8
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-9
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-10
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-11
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-12
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-13
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-14
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-15
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-16
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-17
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-18
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-19
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-20
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-21
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-22
product-card-AZk1wN2hFVFQ2ZmJCc__product-card-23

3. **Descendant Selector**:
   - **`.de-ProductTile .de-ProductTile-title`**: This would select all elements with the class `de-ProductTile-title` that are descendants of elements with the class `de-ProductTile`.
   - **`article h4`**: This would select all `<h4>` elements that are descendants of `<article>` elements.

In [144]:
soup.select(".de-ProductTile .de-ProductTile-title")

[]

In [145]:
soup.select("article h4")

[]

In [146]:
# how many spans?
len(soup.select("span"))

1096

In [147]:
# how many spans inside spans?
len(soup.select("span span"))

114

In [148]:
# how many spans inside spans inside spans?
len(soup.select("span span span"))

0

In [149]:
# how many span inside div inside div inside div ...
len(soup.select("div div div div div div div div span"))

233

[Beautiful Soup selectors](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)

You can also use a combination of `find`, `find_all`, and `select` methods to navigate and locate the elements you're interested in more efficiently. Here's how you can use them together:

1. **Using `find` or `find_all` to Narrow Down the Search Scope**:
   
   Initially, you can use `find` or `find_all` to narrow down your search to a specific section of the HTML document.

   ```python
   section = soup.find('div', class_='product-section')
   ```

2. **Using `select` to Further Locate Elements**:

   After narrowing down the section, you can use the `select` method to locate elements using CSS selectors, which allow for more complex queries. The `select` method can be used on a BeautifulSoup object or on a Tag object (like the one retrieved in step 1).

   ```python
   product_links = section.select('a.product-link')
   ```

In this snippet:
- First, we locate a section of the webpage using `find`.
- Then, within that section, we locate all `a` elements with the class `'product-link'` using `select`.

In [ ]:
first_product = soup.find('article', class_='de-ProductTile')
first_product.select('h4.de-ProductTile-title')

[<h4 class="de-ProductTile-title de-u-textMedium de-u-textShrink1 de-u-lg-textGrow1 de-u-lineHeight2" data-gtm-actions="click" data-gtm-category="Tiles" data-gtm-delegate="child" data-gtm-event="customer-interaction" data-gtm-id="Product Title | /products/rockrider-race-900s-gx-eagle-xc-mountain-bike-350357" itemprop="name">
           Rockrider RACE 900S GX Eagle XC Mountain Bike
         </h4>]

In [ ]:
# Since its a list we need to access the element to get the text
first_product.select('h4.de-ProductTile-title')[0].text

'\n          Rockrider RACE 900S GX Eagle XC Mountain Bike\n        '

### More examples

#### BBC

Lets scrape the BBC to gather some information.

We'll get the hyperlinks to images from the BBC website.

In [150]:
response = requests.get("https://www.bbc.com/")
response

In [151]:
soup = BeautifulSoup(response.content, "html.parser")

In [152]:
img_tags = soup.find_all("img") # We get all the image elements

In [153]:
len(img_tags) # Lets see how many we got

115

In [154]:
img_tags[0] # For example, lets look at the second one to see how we can get the actual URL

In [155]:
# We can use the get method to get the src attribute which contains the URL to the image
img_tags[1].get("src")

'https://ichef.bbci.co.uk/ace/standard/480/cpsprodpb/51e9/live/81683540-4487-11f1-ac78-2112837ce2aa.png.webp'

In [156]:
# Find the nav element with the specified class
nav_element = soup.find('nav', class_='orbit-header-links international')

# Find all span elements inside the nav element
menu_names = [span.get_text() for span in nav_element.find_all('span')]

# Print the menu names
for name in menu_names:
    print(name)

AttributeError: 'NoneType' object has no attribute 'find_all'

## Comments

It's always recommended to check for the availability of an **API** before resorting to web scraping for the following reasons:
 * It is generally much easier to use
 * APIs are usually well-documented
 * Utilizing APIs is often preferred by server administrators

Refer to the `robots.txt` file on a website (by doing `www.example.com/robots.txt`) to understand the server's guidelines and limitations regarding web scraping.

## Summary

1. **Web Technologies**:
   - **HTML**: This is the standard markup language that holds the content of the webpage. It is the primary target when we engage in web scraping.
   - **CSS**: Cascading Style Sheets are used to describe the look and formatting of a document written in HTML.
   - **JavaScript**: This is a scripting language used to create and interactive and dynamic website content.

2. **HTML Structure**:
   - **Hierarchical**: HTML documents are structured hierarchically, meaning elements are nested within other elements, forming a tree-like structure.
   - **Tags**: These are the building blocks of HTML, defining elements that hold different types of content.
   - **Attributes**: HTML tags can have attributes, which define properties of an element and are used to set various characteristics such as class, ID, and style.

3. **Web Scraping Tools**:
   - **Requests**: A Python library that allows you to send HTTP requests to get the HTML content of a webpage.
   - **Beautiful Soup**: A Python library that facilitates the programmatic analysis of HTML, helping in parsing the HTML and navigating the parse tree.
   - **Selenium**: In cases where the webpage content is dynamic and generated using JavaScript, tools like Selenium are often used. Selenium can interact with JavaScript to load dynamic content, making it accessible for scraping.
   
4. **Finding and Selecting Elements**:
   - **Selection by Tag, Class, and ID**: We can find elements using various attributes such as their tag name, class name, or ID.
   - **CSS Selectors**: These are patterns used to select elements more complexly, leveraging the relationships between different elements to find them in numerous ways.

## Further materials

[Web archive](http://web.archive.org/): Find the historical state of webpages in the past!

### How to Solve a 403 Error

When you get a `403` status code in response to a web request, it means "Forbidden." The server understands your request, but it refuses to fulfill it. This is often a measure by websites to prevent web scraping or automated access.

Here's why you might get a `403 Forbidden` error:

1. **User-Agent**: Many websites block requests that don't have a standard web browser User-Agent. The default User-Agent of the `requests` library often gets blocked.
2. **Robots.txt**: This is a file websites use to guide web crawlers about which pages or sections of the site shouldn't be processed or scanned. Respect it.
3. **Rate Limiting**: Websites might block you if you make too many requests in a short period.
And more...

To solve it, try the following, starting from the user-agent:

1. **Change the User-Agent**:
   You can mimic a request from a web browser by setting a User-Agent header.
   ```python
   headers = {
       "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
   }
   response = requests.get(url, headers=headers)
   ```

2. **Use a Web Scraper Library**:
   Libraries like Scrapy or Selenium can help bypass restrictions, especially when JavaScript rendering is involved.

3. **Respect `robots.txt`**:
   Always check `https://www.example.com/robots.txt` (replace `example.com` with the website's domain) to see which URLs you're allowed to access.

4. **Rate Limiting**:
   Implement delays in your requests using `time.sleep(seconds)` to avoid hitting rate limits.

5. **Use Proxies or VPN**:
   Rotate IP addresses or use a VPN service if the server has blocked your IP.

6. **Sessions & Cookies**:
   Some websites might require maintaining sessions or handling cookies.